### ISSUE TITLE
MPEG-DASH option is inactive

### ISSUE THREAD

**Issue by Ilya87** [jdf76/plugin.video.youtube#1]
On Kodi nightly and beta-5 (android) latest version of your plugin has gray mpeg-dash option always turned off so the highest resolution aviable to me is 720p. In Kodi's extensions all inputstream extensions are enabled.

**Comment by guidosarducci** [comment]
Should be fixed with PR https://github.com/jdf76/plugin.video.youtube/pull/9.

**Comment by guidosarducci** [comment]
PR https://github.com/jdf76/plugin.video.youtube/pull/9 was merged for the next release, so this issue can be closed.

**Comment by Ilya87** [comment]
With latest Kodi 17 nightly and your plugin latest master version I still can select only 720p with MPEG-DASH turned on. Is it OK?

**Comment by jdf76** [comment]
Well the option to select what output you’re getting isn’t handled by the plug-in. it’s handled by inputstream. The option you see where it selects the output of 1080 Live / 720p, thats for the old format which has nothing to do with inputstream and is always going to be 720p.

Please visit the forum as it has all your information on how to configure inputstream.


http://forum.kodi.tv/showthread.php?tid=267160 <http://forum.kodi.tv/showthread.php?tid=267160>

Jeff
