### ISSUE TITLE
API Key Input Mangling, Client Secret

### ISSUE THREAD

**Issue by aphirst** [jdf76/plugin.video.youtube#108]
Steps to reproduce the problem:
* Run Kodi 17.3 on LibreELEC 8.0.2 (rPi 3)
* YouTube Add-On 5.4.1, freshly installed (both of its folders deleted, installed from zip)
* Enter personal YouTube/Google API Key details
* Attempt Sign In

What should happen:
* Sign In successful
* Key info in settings.xml corresponds to that typed

What happens
* Error 401 when logging in
* Client Secret field of settings.xml has a spurious extra character at the start

Sign In does work when manually inputting the details into the file, the problem seems to be when inputting it via the Kodi itself.

This happened to me twice in a row, but I sadly didn't take photographs. If you are unable to reproduce yourself, I can do this again, showing the first few characters of each key on-screen and in the xml file.

If you would like any further info, please don't hesitate to let me know.

**Comment by micnorian14** [comment]
Can confirm this is an issue and should affect everyone soon, All was working fine until one day last week I got a "key expired" error. Got sick of fiddling with things so started out fresh - fresh install, new key/api etc. I can setup the app without API and it works fine for a while before the "Daily Quota" BS kicks in. But when I input my API creds and sign in again I get a 401 error after the first /activate code. 

It would appear something has changed on Google's side of things....

**Comment by jdf76** [comment]
Are you using the latest version of 5.4.2.

Jeff

**Comment by micnorian14** [comment]
@jdf76 Confirmed 5.4.1 last week and 5.4.2 today. I'll try a full reset once more to eliminate anything else. One thing I've noticed is the API Client ID is something like: 
123456789-987654321abcdefg.apps.googleusercontent.com
But the app trims it down to:
123456789-987654321abcdefg
I'm sure that's intended but I'm just mentioning it.

In relation to what OP was saying about the API Secret having a special/odd character:
Mine is something like "abc123-" with a noticeable "-" (dash) at the end. No idea if that's intentional or not.

**Comment by micnorian14** [comment]
Logfile is here: http://paste.ubuntu.com/25310399/

The juicy part is here:
Previous line repeats 1 times.
01:12:25.713 T:1962036176   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/)
01:12:25.713 T:1962036176   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
01:12:25.734 T:1702884256   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.youtube] took 21 ms
01:12:25.735 T:1874850720   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/','1','')
01:12:25.736 T:1239413664   DEBUG: Thread LanguageInvoker start, auto delete: false
01:12:25.736 T:1239413664    INFO: initializing python engine.
01:12:25.736 T:1239413664   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
01:12:25.793 T:1239413664   DEBUG: -->Python Interpreter Initialized<--
01:12:25.793 T:1239413664   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
01:12:25.794 T:1239413664   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.youtube/resources/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
01:12:25.794 T:1239413664   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /storage/.kodi/addons/plugin.video.youtube/resources/lib
01:12:25.795 T:1239413664   DEBUG: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.19.0 of the xbmc.python api
01:12:26.229 T:1962036176   DEBUG: ------ Window Init (DialogBusy.xml) ------
01:12:26.812 T:1239413664   DEBUG: [plugin.video.youtube] Using API key set: own
01:12:26.955 T:1239413664   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
01:12:27.013 T:1239413664  NOTICE: [plugin.video.youtube] Running: YouTube (5.4.2) on Krypton (Kodi-17.3) with Python 2.7.13
01:12:27.013 T:1239413664   DEBUG: [plugin.video.youtube] Path: "/
01:12:27.013 T:1239413664   DEBUG: [plugin.video.youtube] Params: "{}"
01:12:27.078 T:1239413664   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
01:12:27.078 T:1239413664   DEBUG: [plugin.video.youtube] User is not logged in
01:12:27.098 T:1239413664   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
01:12:27.098 T:1239413664   DEBUG: [plugin.video.youtube] User is not logged in
01:12:27.099 T:1239413664   DEBUG: [plugin.video.youtube] Setting content-type: "files" for "/"
01:12:27.460 T:1239413664   DEBUG: [plugin.video.youtube] Shutdown of Kodion
01:12:27.460 T:1239413664    INFO: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
01:12:27.485 T:1962036176   DEBUG: Saving fileitems [plugin://plugin.video.youtube/]
01:12:27.488 T:1962036176   DEBUG:   -- items: 6, sort method: 0, ascending: false
01:12:27.510 T:1247802272   DEBUG: Thread BackgroundLoader start, auto delete: false
01:12:27.572 T:1467409312   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.image_decode input port 320 output port 321 m_handle 0x6ad49fc8
01:12:27.576 T:1702884256   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.image_decode input port 320 output port 321 m_handle 0x63aac5b8
01:12:27.576 T:1467409312   DEBUG: COMXCoreComponent::AllocInputBuffers component(OMX.broadcom.image_decode) - port(320), nBufferCountMin(2), nBufferCountActual(2), nBufferSize(81920), nBufferAlignmen(16)
01:12:27.581 T:1467409312   DEBUG: Previous line repeats 1 times.
01:12:27.581 T:1467409312   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.egl_render input port 220 output port 221 m_handle 0x55eba988
01:12:27.588 T:1467409312   DEBUG: COMXCoreComponent::UseEGLImage component(OMX.broadcom.egl_render) - port(221), nBufferCountMin(1), nBufferCountActual(1), nBufferSize(15360) nBufferAlignmen(16)
01:12:27.590 T:1247802272   DEBUG: Thread BackgroundLoader 1247802272 terminating
01:12:27.616 T:1702884256   DEBUG: COMXCoreComponent::Initialize OMX.broadcom.egl_render input port 220 output port 221 m_handle 0x63af6ae0
01:12:27.617 T:1467409312   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.image_decode handle 0x6ad49fc8
01:12:27.618 T:1702884256   DEBUG: COMXCoreComponent::UseEGLImage component(OMX.broadcom.egl_render) - port(221), nBufferCountMin(1), nBufferCountActual(1), nBufferSize(15360) nBufferAlignmen(16)
01:12:27.620 T:1467409312   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.egl_render handle 0x55eba988
01:12:27.621 T:1467409312   DEBUG: DecodeJpegToTexture: decoded special://masterprofile/Thumbnails/3/3030a3d3.jpg 1280x720
01:12:27.629 T:1702884256   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.image_decode handle 0x63aac5b8
01:12:27.631 T:1702884256   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.egl_render handle 0x63af6ae0
01:12:27.638 T:1702884256   DEBUG: DecodeJpegToTexture: decoded special://masterprofile/Thumbnails/f/f960c75c.jpg 256x256
01:12:27.744 T:1962036176   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
01:12:27.769 T:1239413664    INFO: Python script stopped
01:12:27.770 T:1239413664   DEBUG: Thread LanguageInvoker 1239413664 terminating
01:12:29.181 T:1816130464   DEBUG: BUTTON [ 0 ] on "Xbox 360 Wireless Receiver" pressed
01:12:29.182 T:1816130464   DEBUG: FEATURE [ a ] on game.controller.default pressed
01:12:29.238 T:1962036176   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.youtube/sign/in/)
01:12:29.238 T:1962036176   DEBUG:   ParentPath = [plugin://plugin.video.youtube/]
01:12:29.258 T:1874850720   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.youtube] took 20 ms
01:12:29.259 T:1702884256   DEBUG: StartScript - calling plugin YouTube('plugin://plugin.video.youtube/sign/in/','2','')
01:12:29.260 T:1256190880   DEBUG: Thread LanguageInvoker start, auto delete: false
01:12:29.260 T:1256190880    INFO: initializing python engine.
01:12:29.260 T:1256190880   DEBUG: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): start processing
01:12:29.317 T:1256190880   DEBUG: -->Python Interpreter Initialized<--
01:12:29.318 T:1256190880   DEBUG: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py"
01:12:29.318 T:1256190880   DEBUG: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.youtube/resources/lib:/storage/.kodi/addons/script.module.requests/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
01:12:29.318 T:1256190880   DEBUG: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): entering source directory /storage/.kodi/addons/plugin.video.youtube/resources/lib
01:12:29.319 T:1256190880   DEBUG: CPythonInvoker(11, /storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py): instantiating addon using automatically obtained id of "plugin.video.youtube" dependent on version 2.19.0 of the xbmc.python api
01:12:29.362 T:1816130464   DEBUG: BUTTON [ 0 ] on "Xbox 360 Wireless Receiver" released
01:12:29.363 T:1816130464   DEBUG: FEATURE [ a ] on game.controller.default released
01:12:29.761 T:1962036176   DEBUG: ------ Window Init (DialogBusy.xml) ------
01:12:30.378 T:1256190880   DEBUG: [plugin.video.youtube] Using API key set: own
01:12:30.504 T:1256190880   DEBUG: [plugin.video.youtube] Starting Kodion framework by bromix...
01:12:30.558 T:1256190880  NOTICE: [plugin.video.youtube] Running: YouTube (5.4.2) on Krypton (Kodi-17.3) with Python 2.7.13
01:12:30.558 T:1256190880   DEBUG: [plugin.video.youtube] Path: "/sign/in/
01:12:30.558 T:1256190880   DEBUG: [plugin.video.youtube] Params: "{}"
01:12:30.596 T:1256190880   DEBUG: [plugin.video.youtube] Sign-in: Dual login required |True|
01:12:30.675 T:1962036176   DEBUG: ------ Window Init (DialogConfirm.xml) ------
01:12:30.675 T:1962036176    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
01:12:31.650 T:1816130464   DEBUG: BUTTON [ 0 ] on "Xbox 360 Wireless Receiver" pressed
01:12:31.650 T:1816130464   DEBUG: FEATURE [ a ] on game.controller.default pressed
01:12:31.798 T:1816130464   DEBUG: BUTTON [ 0 ] on "Xbox 360 Wireless Receiver" released
01:12:31.798 T:1816130464   DEBUG: FEATURE [ a ] on game.controller.default released
01:12:31.924 T:1962036176   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
01:12:31.972 T:1256190880   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
01:12:31.973 T:1256190880   DEBUG: [plugin.video.youtube] User is not logged in
01:12:32.765 T:1256190880   DEBUG: DialogProgress::Open called
01:12:32.765 T:1256190880   DEBUG: ------ Window Init (DialogConfirm.xml) ------
01:12:32.765 T:1256190880    INFO: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
01:12:44.073 T:1256190880   DEBUG: [plugin.video.youtube] YouTube-TV Login: Access Token |True| Refresh Token |True| Expires |1502691163.99|
01:12:44.098 T:1256190880   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
01:12:44.099 T:1256190880   DEBUG: [plugin.video.youtube] User is not logged in
01:12:44.418 T:1962036176   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
01:12:44.624 T:1256190880   ERROR: [plugin.video.youtube] YouTube: LoginException: Login Failed: Code 401
01:12:44.626 T:1962036176   DEBUG: ------ Window Init (DialogAddonSettings.xml) ------
01:12:44.627 T:1962036176    INFO: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
01:12:44.660 T:1962036176   DEBUG: ------ Window Init (DialogNotification.xml) ------

**Comment by anxdpanic** [comment]
I've been unable to reproduce this and the logs don't really have much information in that area.
There is only one place that the add-on does a simple strip() to remove whitespace but this should not mangle the string as described. (.apps.googleusercontent.com is also intentionally removed)
I've made a PR changing strip() to an alternate method, would appreciate if either of you can test and confirm if the changes resolve it for you since you are able to reproduce the behaviour.

The PR is #113 , the specific changes are in commit 7a41126577a8907cc5c980e9fdd40ec0b55b4180
Thanks

**Comment by jonathansd1** [comment]
I can confirm this is happening to me.

I recently decided I needed to use my own API keys. Went thru the setup, and when I try to log back in I get this exception. Search appears to work fine, so I know my keys are good. Currently running v5.4.5 of the add-on with Kodi Krypton (LibreElec)

**Comment by anxdpanic** [comment]
Still unable to reproduce, added extra checks to try to catch any mangling that may be happening.
https://github.com/jdf76/plugin.video.youtube/pull/140/commits/064a66ac62381fa06c63b0ae481b6eb26280ba20

**Comment by demonicdragon** [comment]
Getting same login issue. Personal API seems to be working, when it is set to that though I cannot login. Using youtube.com/activate . 'Youtube LoginExeption Error Code: 401'. The code is accepted on youtube/activate and the issue only occurs when trying to login.

On a side note, how do you login with settings.xml? I havent quite worked that one out yet.

**Comment by micnorian14** [comment]
[Bingo:] (https://stackoverflow.com/questions/27483674/youtube-api-v3-shows-access-not-configured)

You need to delete the current client key, disable the YT data API, re-enable it, then create a new client key. Confirmed working meow. Not sure what made it stop one day - methinks YT stopped/started my API and that invalidated my key. Confirmed is working fine. Meow.

**Comment by anxdpanic** [comment]
Key stripping methods have been changed, error messages in this area are improved, and api keys can be edited from web browser in coming v6

if when signing in you get -- invalid_client : oauth client not found -- the client id is incorrect.
if when signing in you get -- invalid_client : unauthorized -- the client secret is incorrect.

Please re-open if still having this issue.
