### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ohmichael** [jdf76/plugin.video.youtube#110]
Youtube subscriptions not showing nor does their videos show-only search works & i even redid my google api youtube sync

**Comment by sjaakvandenberg** [comment]
Same problem here on Android 6.0.1 with Kodi 17.3 with plugin version 5.4.0. Both re-authorizing with the API and reinstalling the plugin yield no results.

**Comment by jdf76** [comment]
You tube changed their API key. We're looking into seeing if we can get the new one. Keep an eye on the forums.

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/releases/tag/5.4.2
