### ISSUE TITLE
Go-to-Page in playlists

### ISSUE THREAD

**Issue by Lathanael** [jdf76/plugin.video.youtube#126]
Scenario:
Playlist from a subsciption with a lot(>500) of items

"Problem":
You need to select "Next page (#)" several times even if 50 items are already displayed to get to the last page(or pages at the end of the list)

Question:
Would it be possible(or is it possible already?) to have a "Go-to-Page #" in the side menu?

**Comment by Twilight0** [comment]
I think such thing is a tiny bit difficult because you have to know the page token and order Kodi to go there.
