### ISSUE TITLE
Multi User Logon

### ISSUE THREAD

**Issue by kgoerbig** [jdf76/plugin.video.youtube#128]
Is it possible to support multi-login? So that multiple Youtube users can login to access their own playlists / Subscriptions?

Or in the API settings add an option to add multiple sets of API Keys for each YouTube login.

**Comment by anxdpanic** [comment]
Not currently within the add-on, should be able to use Kodi profiles to this end though.

**Comment by kgoerbig** [comment]
Is it possible to add multi log support in the youtube addon?

**Comment by anxdpanic** [comment]
Will be looking into this for V6.1.0, the current changes in v6.0.0 moving api/login tokens to json is a precursor to multi-user and developer logins. If you'd like to participate in testing and getting v6 stable, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.0.0-dev

**Comment by anxdpanic** [comment]
Closed by #352

See https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev
