### ISSUE TITLE
Autoplay feature

### ISSUE THREAD

**Issue by Keeo** [jdf76/plugin.video.youtube#136]
Hello,

thanks for amazing plugin. I would like to propose feature that would allow users to use **autoplay** like in normal browser.

How youtube's **autoplay** work? You chose video to be played and when it ends it automatically starts another one.

This has already been [requested](https://github.com/Kolifanes/plugin.video.youtube/issues/34), but forgotten.

**Comment by anxdpanic** [comment]
There is an Autoplay suggested videos setting, under General.

You can also right click on a playlist and choose Play All, or right click a list of videos and choose Play from here.

**Comment by Keeo** [comment]
Thank you!

I was googling if this is possible but found only mentioned issue.
