### ISSUE TITLE
No longer working on kodi 14.2

### ISSUE THREAD

**Issue by pitsi** [jdf76/plugin.video.youtube#141]
After yesterday's (?) update to 5.4.5, youtube no longer works on my kodi 14.2 (openelec 5.0.8, the last 32bit version of openelec). This is what comes out in the log file when trying to launch it.

http://paste.debian.net/987542/
(the paste will be available for 7 more days)

Deleting /storage/.kodi/userdata/addon_data/plugin.video.youtube/ so as to reset the addon's settings results in the same behavior. It does work as it used to on kodi 17.x (on my debian testing x64 and the openelec 8.0.4 on pi zero installation).

**Comment by anxdpanic** [comment]
This is fixed with #139

**Comment by pitsi** [comment]
I just noticed this commit here, which probably means the next update will disable youtube on my installation, am I right?

https://github.com/jdf76/plugin.video.youtube/commit/5d0f0d51950ea28f39127afe169d1f29e834bfd0

Can't you backport the change or ask kodi to remove version 5.4.5 from their official repo of 14.2?


Rolling back is no big deal for me, but autoupdate will update it again, and no, there is no way to disable auto update for a single plugin. Plus, the plugin used to work flawlessly on version 5.4.2, which was released a month ago and I still use it, either on it's own or when it is called from another plugin.

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/tree/helix will be added to official when version is bumped as the last version for Helix. All current fixes are and will be backported so the final helix version will be functional.

**Comment by pitsi** [comment]
Thanks for the clarification :)
I know I have to upgrade to something more recent, but there is nothing similar to openelec for 32bit only cpus.

**Comment by anxdpanic** [comment]
I've posted the alpha zips. https://github.com/jdf76/plugin.video.youtube/releases/tag/5.5.0-alpha 
The 5.4.6 version includes the fix and will work in helix, 5.5.0 is isengard +

**Comment by pitsi** [comment]
It seems to be working as it used to. Thank you very much!
What is the -unofficial version of the addon? Does it provide anything special?

**Comment by anxdpanic** [comment]
Great to hear :) Unofficial versions include view overrides, which is not allowed on the official repo.

**Comment by pitsi** [comment]
A while ago, my kodi 14.2 decided to autoupdate plugin.video.youtube to version 5.4.99, which could not be installed due to missing dependencies. Probably, it was provided by some third party repo, because the main one only hosts up to version 5.4.5, the broken one. 
How can I find which repo provided it? I only use the main repo, the official and unnofficial repos of openelec, twilight0's repo and colossal.

**Comment by jdf76** [comment]
I would just use Kodi’s repository unless you have to use bleeding edge changes.

My repo is designed for earlier tests and access before it pushed to the kodi repo.

The way I do it is

1. Alphas are tested

2. Push to jdf76 repo (youtube repo)

3. If all is well, push to kodi repo.

The latest version from us (jdf76, which is pushed to kodi repo is 5.4.5)

The alphas are 14.x (5.4.6) and 15.x and above 5.5.x

If you plan to use someone else repo I suggest you contact them.

Thank you,

Jeff

**Comment by pitsi** [comment]
It was twilight0's repo that hosts version 5.4.99, just checked it on my pc. Sorry for the inconvenience.

I do not use kodi's main repo anymore for plugin.video.youtube because of this issue here, so I resort to your alpha builds for having a working version of it.

**Comment by Twilight0** [comment]
I arbitrarily bumped youtube on my own repo to 5.4.99 because my flagship addon depends on it and I couldn't wait for an official release. Consider downgrading.

**Comment by pitsi** [comment]
No worries, Twilight0. Thank you for letting us know :)

**Comment by anxdpanic** [comment]
@pitsi can you confirm the latest ~beta1 zip is working for helix? Just double checking before push to official. Thanks in advance.

**Comment by pitsi** [comment]
It seems to be working fine, like it used to :)
I will check the 5.5.0 betas tomorrow though..

**Comment by anxdpanic** [comment]
Thank you, being the last version pushed for helix want to make sure.

**Comment by pitsi** [comment]
Kinda offtopic, but I have let you know...

It has been a few months now that I decided to ditch openelec 5.0.8 and its old kodi 14.2 and move to another distro that will have kodi 16 at least, because thare are addons that I "need" for my everyday routine. The problem is I can not find anything built around the jeos concept (just enough os) like openelec, so I will probably move to a regular linux distro that I will try to keep as slim as possible.

So, once plugin.video.youtube 5.4.6/5.5.0 is released as final, please allow me to make the switch. Thank you for doing all this work of backporting changes from one branch to another just for me, because I really doubt that there will be another one out there using such an old version like I do.

**Comment by anxdpanic** [comment]
Updating is always recommended, please don't wait on account of us. Appreciate the feedback.
If you looking for an up to date JEOS why not Libreelec? 
I personally use OSMC nightlies, but OSMC is also a good choice.

**Comment by pitsi** [comment]
Libreelec is amd64 (x86_64) only and the netbook's cpu (atom n270) does not have the 64bit instruction set. That is why I am stuck with openelec 5.0.8 all these years, because it is the very last version for 32bit cpus. It feels like using xp on 2014+, you just look around to see which app still works for your job, not which one works the best.

Osmc on the other hand is arm only. Excuse my offtopic :)

**Comment by anxdpanic** [comment]
No worries 👍 Going to close this issue now, bumped to release.
https://github.com/jdf76/plugin.video.youtube/releases/tag/5.4.6

**Comment by pitsi** [comment]
Well done :)
When should we expect this in the main repo?
