### ISSUE TITLE
Audio muted for 5 seconds after skip forward

### ISSUE THREAD

**Issue by greystashh** [jdf76/plugin.video.youtube#148]
I have made the experience if you use the Addon with Dash and skip forward or backward, the video continuous but the sound is muted for about five seconds

I am using kodi 18 with android and 5.4.5 but also had this issue with kodi 17

**Comment by greystashh** [comment]
The error in log file is:

ERROR: CDVDAUDIO::AddPacketsRendenderer - timeout adding data to renderer

**Comment by anxdpanic** [comment]
Resolved with inputstream.adaptive 2.1.5
