### ISSUE TITLE
Add watched videos to YouTube history

### ISSUE THREAD

**Issue by blackwind** [jdf76/plugin.video.youtube#150]
Currently, videos I watch through the plugin aren't being added to my YouTube watch history, making it difficult to keep track of what I've watched between devices. Would love to see that change in a future version.

**Comment by anxdpanic** [comment]
https://developers.google.com/youtube/v3/revision_history as of August 11, 2016 watch history and watch later have been removed from the api. This WAS a feature previously, now you need to set up a playlist for the add-on to use as your history.
