### ISSUE TITLE
History playlist should work like Watch Later playlist

### ISSUE THREAD

**Issue by EmmanVazz** [jdf76/plugin.video.youtube#151]
I am aware that the Watch Later playlist works if you make the id WL. If you look at https://developers.google.com/youtube/v3/docs/channels/list that is because that response tells you watchLater is WL. That same response states that watchHistory is HL. I tried that as the custom playlist id and it doesn't error out just a blank playlist. If there any difference that is causing it to not work as these playlist seems to function the same way?

**Comment by anxdpanic** [comment]
https://developers.google.com/youtube/v3/revision_history as of August 11, 2016. Both have been deprecated. Empty list and/or partial function is the best that can be expected and why this is no longer the default behaviour.
