### ISSUE TITLE
Playlists not working in home screen

### ISSUE THREAD

**Issue by robertxgray** [jdf76/plugin.video.youtube#152]
Hi. I've got some strm/nfo files including Youtube playlists with videos for the kids. Here's a sample: [playlist.strm.txt](https://github.com/Kolifanes/plugin.video.youtube/files/1345825/playlist.strm.txt), [playlist.nfo.txt](https://github.com/Kolifanes/plugin.video.youtube/files/1345826/playlist.nfo.txt) (txt extension added because of github).

They can be played via the web interface, or by browsing my movies collection, here's a log: [working.log](https://github.com/Kolifanes/plugin.video.youtube/files/1345833/working.log). But if I try to play them from the home screen via "random videos", "recently added", etc. they never work, ever. Sometimes there's an error shown in the screen, but not always. Here's also a sample log: [not_working.log](https://github.com/Kolifanes/plugin.video.youtube/files/1345837/not_working.log)

Note that if the strm file contains a single video instead of a playlist, everything works OK. I also made tests with different skins including Estuary, Omni, Box and Osmc, but the behaviour is always the same. I would say the problem started with one of the latest plugin updates, but I'm not 100% sure. Thanks.

**Comment by anxdpanic** [comment]
For playlists, &play=1 is required to start playback, otherwise the playlist is created but not played. 
Been that way since before I started on the add-on. 
try:

plugin://plugin.video.youtube/play/?playlist_id=PLF06QSQtcR4ekj67ORmq-XVpKuCtJ3-cZ&order=shuffle&play=1

**Comment by robertxgray** [comment]
Yes, now it works as expected. Thank you very much.
