### ISSUE TITLE
Youtube channel failed in kodi jarvis ubuntu trusty

### ISSUE THREAD

**Issue by susobaco** [jdf76/plugin.video.youtube#18]
The log:
[error.txt](https://github.com/jdf76/plugin.video.youtube/files/745606/error.txt)

**Comment by jdf76** [comment]
Go here

http://forum.kodi.tv/showthread.php?tid=267160 <http://forum.kodi.tv/showthread.php?tid=267160>

There is an active support forum for the plugin

**Comment by anxdpanic** [comment]
closing, version in log is very old v5.2.1. please update and re-post error log here if still an issue to re-open the issue. also ensure pyopenssl is up to date. at least v16.2.0 "pip install pyopenssl==16.2.0"
