### ISSUE TITLE
Please add or backport the missing (greek) translation strings from 5.5.0 to 5.4.6 for helix

### ISSUE THREAD

**Issue by pitsi** [jdf76/plugin.video.youtube#185]
As the title says, please add the missing strings from this file
https://github.com/jdf76/plugin.video.youtube/blob/f217e18aa84f93461423580465dac62b075ec6b4/resources/language/resource.language.el_gr/strings.po

to this file
https://github.com/jdf76/plugin.video.youtube/blob/helix/resources/language/Greek/strings.po

To be more specific, lines 684 to 710 are the ones needed to be copied over. If there are more, I will look them up and repost.

**Comment by jdf76** [comment]
I could add it but then I would have to re-push it out to everything and bump the version. Honestly it’s just easier if you do it to you own.

Thanks
Jeff

**Comment by anxdpanic** [comment]
It's been backported to the helix branch, will be included in the next alpha zips.

**Comment by pitsi** [comment]
Oh ok then, thank you :)
Plus, I just checked for any more missing lines, but there are none.
