### ISSUE TITLE
Youtube playlists

### ISSUE THREAD

**Issue by DiamondMouse** [jdf76/plugin.video.youtube#187]
Is there any way that I can like a YouTube playlist from my phone or pc and have it show up in the playlist tab in the kodi addon, also is there a way of implementing the play on tv option that my Youtube app has on my phone. It requires a 4 didget code from a tv or device that has the Youtube app installed on the same wifi network👌🏻

**Comment by anxdpanic** [comment]
Currently not available via api for playlists. And not able to implement youtube-tv pairing, currently the best way to achieve this is using Kore or Yatse and using the android share feature from the youtube app.

**Comment by DiamondMouse** [comment]
Ok thx man :)
