### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by user460** [jdf76/plugin.video.youtube#192]
How does your addon to continue with the playlist without it being lost? (In terms of programming)

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/yt_play.py

in play_video you can see how it's added to existing, and in play_playlist you can see how a fresh playlist is created and then start playback by playing the first video item.
