### ISSUE TITLE
One or more items failed to play

### ISSUE THREAD

**Issue by oomek** [jdf76/plugin.video.youtube#198]
I'm having problems with the youtube plugin recently. Kodi throws an error: One or more items failed to play. In the log I'm getting the following errors.

`01:44:26.480 T:9620  NOTICE: [plugin.video.youtube] Running: YouTube (5.5.0~alpha9) on Leia (Kodi-18.0) with Python 2.7.13
01:44:26.613 T:9620   ERROR: C:\Users\HT\AppData\Roaming\Kodi\addons\script.module.urllib3\lib\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
`

Any ideas what may be the cause of this?
I'm on the latest x64 nightly and I've tried the official youtube version and your latest 5.5.0 alpha9

**Comment by anxdpanic** [comment]
That message has no impact on playback, to silence that warning enable Settings - Advanced - Force SSL Certificate Verification.
If you haven't already, also try restarting Kodi, if script.module.requests updated to current it can cause issues until after reboot. 
Aside from that, please post a full debug log of the issue.

**Comment by oomek** [comment]
Seems like it's related to other problems that appered in the recent x64 builds of Kodi. Some scrappers and video addons are throwing ssl errors due to incorrect libcurl.dll version

**Comment by oomek** [comment]
Btw, it's not just a message box. Youtube is not playing any videos at all.

**Comment by oomek** [comment]
I think I have found a fix.
I've replaced the libcurl.dll v7.52.1.0 in the C:\Program Files\Kodi folder with v7.56.1.0 from the link below

https://curl.haxx.se/download.html
Win64 - Generic, Win64 ia64 CAB

**Comment by anxdpanic** [comment]
Thanks for the heads up. 👍
