### ISSUE TITLE
Lose video and audio after 3-5 seconds for 3 seconds on Krypton.

### ISSUE THREAD

**Issue by muzicman** [jdf76/plugin.video.youtube#20]
Youtube ver 5.3.8. When starting various videos I temporarily lose video and audio after 3-5 seconds for 3 seconds. For example, timeline goes from 00:00:03 to 00:00:06 while screen is black. Rewinding video to beginning and no issue. Running Libreelec Krypton v7.95.2. MPEG-DASH enabled.

**Comment by anxdpanic** [comment]
Unable to resolve, when playback is started the process is handed off to core/inputstream.adaptive. 

My be related to inputstream.adaptive and/or settings, may also be ffmpeg/core, encoding and/or device related. May find some information in the forum as well regarding other users experiences. http://forum.kodi.tv/showthread.php?tid=267160
