### ISSUE TITLE
this plugin expect the python module 'certifi' to be present, it isn't

### ISSUE THREAD

**Issue by Jildsma** [jdf76/plugin.video.youtube#202]
Since a recent update the plugin requires the "certifi" python module, or since the upgrade to ubuntu 17.10 this module isn't available by default any more.

It needs to be installed separately.
pip install certifi
resolves an issues where the youtube addon throws a python importerror.

**Comment by anxdpanic** [comment]
certifi was made available in Kodi, script.module.certifi and is a dependency of script.module.requests.  Do you have script.module.certifi installed? Settings - System - Add-ons - Manage Dependencies

**Comment by Jildsma** [comment]
We don't, and it wasn't installed on upgrade. Youtube worked before the upgrade, we upgraded from ubuntu 17.04 and the previous kodi setup trough the regular upgrade solution provided by ubuntu.

**Comment by anxdpanic** [comment]
It should be auto installed when script.module.requests updated, my guess would be it failed install. 

Here is the zip for install, https://ftp.heanet.ie/mirrors/xbmc/addons/krypton/script.module.certifi/script.module.certifi-2017.07.27.1.zip should help avoid any unexpected behaviour from possible version mismatches to the system version in the future.
