### ISSUE TITLE
[Feature Request] Remove watched videos from playlist

### ISSUE THREAD

**Issue by slideup-benni** [jdf76/plugin.video.youtube#212]
As of the change, that the watched status of the videos won't transfer to youtube, it is difficult to clear the watch later playlist. 
It would be very nice when you could provide a link in a menu to remove all already watched videos from a playlist.

**Comment by anxdpanic** [comment]
As of what change? 
Watch Later playlists that are not 'WL' can be removed from like a normal playlist, and videos are removed from the watch later playlist after being played if the setting is enabled. 

In the latest alphas if you clear the custom watch later playlist id, the add-on will try to get your real watch later playlist id (which will sync) this may require adding a few videos to the watch later playlist on the web and then accessing watch later in the add-on. Currently no more reliable way, you'll be able to tell it worked by checking the Custom watch later playlist id has been set.

**Comment by slideup-benni** [comment]
Ah okay, i didn't know about setting to auto-remove the videos from watched later.
The link to my watched later playlist is working without setting a custom playlist, but after watching a video it won't be removed.
But i see, that i'm using version 5.3.10 and this is a really old release. Thats why i'll try to update and test this again. Thank you very much.

**Comment by slideup-benni** [comment]
Unfortunately this doen't work for me.
I set the Watch Later playlist to "WL" and i can access it with the menu entry. After i watched a video it gets a tick and doen't disappear. Even after i reload the page it still exists and on youtube it is available in the watch later list too.
I tested this with version 5.4.5 on LibreElec 8.0.2 and Kodi 17.3

**Comment by anxdpanic** [comment]
WL doesn't work, it only shows the videos. In 5.4.5 you can only use custom playlists.

The alphas here, https://github.com/jdf76/plugin.video.youtube/releases/tag/5.5.0-alpha are the only ones with working regular watch later. Make sure to remove the WL and leave that setting blank, then after going into watch later in the add-on check your settings and confirm there is a PL2349025092352 playlist id in your custom watch later playlist setting. If it's still blank add a few videos to the watch later on the web and try again. Once the PL playlist is set all should be able to be synced both ways.
Still looking for a more reliable way as it's not directly supported by YouTube via the api anymore.

**Comment by slideup-benni** [comment]
i will test this soon :smiley:
