### ISSUE TITLE
Support to "rewind" live streams

### ISSUE THREAD

**Issue by rccavalcanti** [jdf76/plugin.video.youtube#225]
Hi!
YouTube enables going back a few hours on live streams. AFAIK it can't be done currently with the add-on. Is it possible to implement?

**Comment by anxdpanic** [comment]
Time shift of live streams is available with Kodi 17.6 and Kodi 18(nightlies), must have inputstream.adaptive installed and enable Settings - General - Use MPEG-DASH

**Comment by rccavalcanti** [comment]
Thanks for the answer.

I actually already had both enabled on Kodi 17.6 (Raspbian), but something doesn't seem to work right. No time shift and the streams are stuck at 720p, regardless of the bandwidth.

The versions Raspbian gives me are:
YouTube add-on: 5.4.5
InputStream Adaptative: 2.0.10

And here are screenshots of my settings.
![InputStream Adaptative](https://user-images.githubusercontent.com/4497566/34615616-a69d0b0e-f21c-11e7-99a6-7f8f36b16b61.png)
![YouTube add-on](https://user-images.githubusercontent.com/4497566/34615618-a6bd1480-f21c-11e7-8a48-2c1830fbad9a.png)

Thanks for your time.

**Comment by anxdpanic** [comment]
The latest version of inputstream.adaptive included with 17.6 (win version) is 2.0.19. Not sure what version is available through raspbian's repos. That would explain it though, inputstream.adaptive >= 2.0.12 is required for youtube live so your live streams are using default playback method. 

Video Quality has a 1080 live/720 option, 1080 does work for live streams using the default playback method (no timeshift though).

**Comment by rccavalcanti** [comment]
Raspbian Stretch is stuck in 2.0.10. So that would be the cause.
Thank you!
