### ISSUE TITLE
No mpeg-dash or streams > 720p

### ISSUE THREAD

**Issue by anxdpanic** [jdf76/plugin.video.youtube#230]
dashmpd url not returned by get_video_info for vods

get_video_info parameter 'el'

no longer working (Invalid Parameters):
'default'
'info'
'vevo'

working w/ no dashmpd url:
'leanback'
'embedded'
'detailpage'
'editpage'
'adunit'
'previewpage'
'profilepage'

**Comment by greystashh** [comment]
Can you say whether this can be fixed?

**Comment by anxdpanic** [comment]
Wish I could. The 'el' parameter values 'default', 'info', and 'vevo' now all return invalid where they worked previously. And the working ones, 'leanback', 'embedded', 'detailpage' are not returning the dash url. It's also not found via the watch?v= page either.

**Comment by anxdpanic** [comment]
It looks like it is still returned for live content and for drm protected content.

**Comment by greystashh** [comment]
Live content was still working with dash.  Can you give an example for DRM content?

**Comment by anxdpanic** [comment]
drm content (Purchases/rentals) is staged but isn't ready for the add-on yet, inputstream.adaptive updates are required first. 

https://github.com/anxdpanic/plugin.video.youtube/releases/tag/purchases-test
https://github.com/anxdpanic/plugin.video.youtube/tree/purchases

**Comment by greystashh** [comment]
Can't you adapt this for the the vods?

**Comment by anxdpanic** [comment]
The request for vod/live/drm are the same, only now for vod there is no dash url being returned with any of the 'el' parameters that I'm aware of.

**Comment by Schtek** [comment]
Is there any reason why it would not be possible to create our own mpd file and feed that to inputstream.adaptive? After all it seams that most of the information is there, with the streams in adaptive_fmts.

**Comment by anxdpanic** [comment]
Not able to dump valid manifest and start playback from the local file, and adaptive_fmts don't have all the necessary information(segment url, ranges) to create the manifest. So as far as I can tell this isn't an option. :\

**Comment by Schtek** [comment]
I managed to generate a MPD file that worked on VLC 3.0.0 rc6. However, I lack the knowledge on how to test it in Kodi.

**Comment by anxdpanic** [comment]
https://github.com/Schtek/plugin.video.youtube/commits/mpd-file is the working generated file?
I can cherry pick and try in kodi.

**Comment by Schtek** [comment]
Yes, I added some code in bottom of  resources/lib/youtube_plugin/youtube/helper/video_info.py that genereates a MPD-file from the data in adaptive_fmts.

**Comment by anxdpanic** [comment]
They are not working in Kodi, also confirmed they are working with 3.0.0 rc6 like you mentioned. https://github.com/anxdpanic/plugin.video.youtube/tree/generated_mpd

**Comment by Schtek** [comment]
https://github.com/anxdpanic/plugin.video.youtube/tree/generated_mpd
That one works for me on kodi, to some degree. Seems that only a few of the streams are working.

I have reason to belive that it is only the stream first selected by inputstream.adaptive that works. So if the stream is switched early in the playback it does not work at all. But don't hold me on that one.

**Comment by anxdpanic** [comment]
Do you have an example of a video id it's working with in Kodi?

**Comment by Schtek** [comment]
https://www.youtube.com/watch?v=sgIqRwvaBw4
Every video I have tried has worked, but most, like this one, start with no audio. This I can work around by toggling the audio stream in the settings.

Maybe it depends on inputstream adaptive settings.

**Comment by anxdpanic** [comment]
inputstream adaptive errors on loading the local file for me everytime. Do you happen to be testing videos under My Channel? Can you post a debug log?

**Comment by Schtek** [comment]
[kodi_part.log](https://github.com/jdf76/plugin.video.youtube/files/1623613/kodi_part.log)

Here is a log from when the playback starts.

I am testing videos from many different channels.

**Comment by anxdpanic** [comment]
Thanks. It's an issue with filesystems that use \'s

**Comment by greystashh** [comment]
Wouldnt that be possible for temporary workaround?

**Comment by anxdpanic** [comment]
Possibly, I've staged a basic proxy for hosting up the local mpd's to overcome the filesystem shortcoming.
https://github.com/anxdpanic/plugin.video.youtube/tree/generated_mpd

Issue now at least for me, all I can get is low quality with no audio.

**Comment by anxdpanic** [comment]
#235 generates the mpd, and serves it by proxy. 

The audio and video issues were due to unsupported codecs. Allowing only 'video/mp4' and 'audio/mp4' resolved issues with quality and sound.

I have another issue to look at and then I will bump the alpha zip. The changes are in master now though if you'd like to try it.

Thanks again @Schtek 👍

**Comment by Schtek** [comment]
It works great on my end now.
Thanks to you too for integrating it so soon!

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/releases

**Comment by Twilight0** [comment]
Still not getting qualities above 720p.

**Comment by csmodfw** [comment]
Please check why resolutions is limited to 2560x1440 itag=264 and never include 3840x2160 itag=313 on generated mpd file
Format 313:
Video Resolution: * x 2160
Video Format: VP9 DASH video

https://www.youtube.com/watch?v=VQy_4Oy-p60
https://www.youtube.com/watch?v=mHUOCxVT5ro

Thanks for last release but still need some research how to support 4K and 8K after last Google update.
