### ISSUE TITLE
Add 4K Quality +load all my subscriptions.

### ISSUE THREAD

**Issue by Mstos** [jdf76/plugin.video.youtube#250]

**Comment by Twilight0** [comment]
4K quality also needs support from inputstream adaptive addon. Subscriptions are loaded as soon as you sign in and allow two "applications" from youtube at youtube.com/activate

**Comment by anxdpanic** [comment]
#257 opened to track, >1440p and additional audio streams. If you're having an issue with subscriptions please open a specific issue and include symptoms and debug log please.
