### ISSUE TITLE
Client ID Truncated

### ISSUE THREAD

**Issue by Tigereye2k6** [jdf76/plugin.video.youtube#259]
I have created my own API Key and Client ID. But the client ID will always be truncated and the login with the credentials is not working.

My Client ID is 72 characters long but will always be truncated to 45 characters.
The part that is being truncated is ".apps.googleusercontent.com".
I think google has generated the client id's without that suffix in the past. I have tried everything to create a Client ID without it but i can't.

Edit: I have tested it with the last version - 5.5.0

**Comment by anxdpanic** [comment]
.apps.googleusercontent.com is not required in the settings. 
It is trimmed off the setting, and re-saved, .apps.googleusercontent.com is added by the add-on when used.
This isn't the cause of your issue.

If you're on the latest release https://github.com/jdf76/plugin.video.youtube/releases , 
if when signing in you get -- invalid_client : oauth client not found -- the client id is incorrect.
if when signing in you get -- invalid_client : unauthorized -- the client secret is incorrect.
if you try to access anything that requires api(logged in or out, ie. Popular right now) and get an error it's the api key.

**Comment by Tigereye2k6** [comment]
I have posted the credentials again directly into the XML via putty and it worked now. I have tried it yesterday via the kodi app on my smartphone and pasted it into the input field directly in kodi and i think that have messed up the string.

Sorry - my bad.

**Comment by anxdpanic** [comment]
No worries, happy to hear it's resolved 👍
