### ISSUE TITLE
Update translation in French of the addon youtube for kodi

### ISSUE THREAD

**Issue by bubuleur** [jdf76/plugin.video.youtube#27]
Hello,
I come to you to give my contribution I updated the translation in French of the addon youtube for kodi
If you could put it in the next update
In thanking you
Have a good day

msgctxt "Addon Summary"
msgid "Plugin for YouTube"
msgstr "Plugin pour YouTube"

msgctxt "Addon Description"
msgid "YouTube is a one of the biggest video-sharing websites of the world."
msgstr "YouTube est l'un des plus grands sites de partage de vidéos du monde."

msgctxt "#30000"
msgid "General"
msgstr "Général"

msgctxt "#30001"
msgid "Username"
msgstr "Identifiant"

msgctxt "#30002"
msgid "Password"
msgstr "Mot de passe"

msgctxt "#30007"
msgid "Use MPEG-DASH"
msgstr "Utiliser MPEG-DASH"

msgctxt "#30008"
msgid "Configure inputstream.adaptive"
msgstr "Configurer inputstream.adaptive"

msgctxt "#30009"
msgid "Always ask for the video quality"
msgstr "Toujours demander la qualité de la vidéo"

msgctxt "#30010"
msgid "Video Quality"
msgstr "Qualité vidéo"

msgctxt "#30011"
msgid "480p"
msgstr "480p"

msgctxt "#30012"
msgid "720p (HD)"
msgstr "720p (HD)"

msgctxt "#30013"
msgid "1080p (HD)"
msgstr "1080p (HD)"

msgctxt "#30014"
msgid "2160p (4k)"
msgstr "2160p (4K)"

msgctxt "#30015"
msgid "4320p (8k)"
msgstr "4320p (8K)"

msgctxt "#30016"
msgid "240p"
msgstr "240p"

msgctxt "#30017"
msgid "360p"
msgstr "360p"

msgctxt "#30018"
msgid "1080p Live / 720p (HD)"
msgstr "1080p Live / 720p (HD)"

msgctxt "#30020"
msgid "Allow 3D"
msgstr "Autoriser la 3D"

msgctxt "#30021"
msgid "Show Fanart"
msgstr "Afficher les fanarts"

msgctxt "#30022"
msgid "Items per page"
msgstr "Nombre d'éléments par page"

msgctxt "#30023"
msgid "Search History Size"
msgstr "Taille de l'historique de recherche"

msgctxt "#30024"
msgid "Cache Size (MB)"
msgstr "Taille du cache (Mo)"

msgctxt "#30025"
msgid "Enable setup-wizard"
msgstr "Activer l'assistant de démarrage"

msgctxt "#30026"
msgid "Override View"
msgstr "Remplacer l'affichage"

msgctxt "#30027"
msgid "View: Default"
msgstr "Affichage par défaut"

msgctxt "#30028"
msgid "View: Episodes"
msgstr "Affichage par épisodes"

msgctxt "#30029"
msgid "View: Movies"
msgstr "Affichage par films"

msgctxt "#30030"
msgid "Execute setup-wizard?"
msgstr "Exécuter l'assistant de démarrage ?"

msgctxt "#30031"
msgid "Advanced"
msgstr "Avancé"

msgctxt "#30032"
msgid "View: TV Shows"
msgstr "Affichage par séries TV"

msgctxt "#30033"
msgid "View: Songs"
msgstr "Affichage par chansons"

msgctxt "#30034"
msgid "View: Artists"
msgstr "Affichage par artistes"

msgctxt "#30035"
msgid "View: Albums"
msgstr "Affichage par albums"

msgctxt "#30036"
msgid "Support alternative player"
msgstr "Support de lecteur alternatif"

msgctxt "#30037"
msgid "Custom Watch Later Playlist ID"
msgstr "Personnaliser l'ID de la Playlist 'Regarder plus tard'"

msgctxt "#30038"
msgid "Custom History Playlist ID"
msgstr "Personnaliser l'ID historique de la liste de lecture"

msgctxt "#30100"
msgid "Favorites"
msgstr "Favoris"

msgctxt "#30101"
msgid "Add to addon favs"
msgstr "Ajouter aux favoris"

msgctxt "#30102"
msgid "Search"
msgstr "Rechercher"

msgctxt "#30103"
msgid "Library"
msgstr "Bibliothèque"

msgctxt "#30104"
msgid "Highlights"
msgstr "En vedette"

msgctxt "#30105"
msgid "Archive"
msgstr "Historique"

msgctxt "#30106"
msgid "Next Page (%d)"
msgstr "Page suivante (%d)"

msgctxt "#30107"
msgid "Watch Later"
msgstr "Regarder plus tard"

msgctxt "#30108"
msgid "Remove"
msgstr "Supprimer"

msgctxt "#30109"
msgid "Latest Videos"
msgstr "Dernières vidéos"

msgctxt "#30110"
msgid "New Search"
msgstr "Nouvelle recherche"

msgctxt "#30111"
msgid "Sign In"
msgstr "Connexion"

msgctxt "#30112"
msgid "Sign Out"
msgstr "Déconnexion"

msgctxt "#30113"
msgid "Rename"
msgstr "Renommer"

msgctxt "#30114"
msgid "Confirm delete"
msgstr "Confirmer la suppression"

msgctxt "#30115"
msgid "Confirm remove"
msgstr "Confirmer la suppression"

msgctxt "#30116"
msgid "Delete \"%s\"?"
msgstr "Supprimer \"%s\"?"

msgctxt "#30117"
msgid "Remove \"%s\"?"
msgstr "Supprimer \"%s\" ?"

msgctxt "#30118"
msgid "Delete"
msgstr "Supprimer"

msgctxt "#30119"
msgid "Please wait..."
msgstr "Veuillez patienter…"

msgctxt "#30120"
msgid "Clear"
msgstr "Nettoyer"

msgctxt "#30200"
msgid "API Key"
msgstr "Clé de l’API"

msgctxt "#30201"
msgid "API Key"
msgstr "Clé de l’API"

msgctxt "#30202"
msgid "API Id"
msgstr "Id de l’API"

msgctxt "#30203"
msgid "API Secret"
msgstr "API secret"

msgctxt "#30204"
msgid "Enable Personal API Keys"
msgstr "Activer les clés API personnelles"

msgctxt "#30205"
msgid "Use preset API key set"
msgstr "Utiliser un ensemble de clés API prédéfinies"

msgctxt "#30500"
msgid "Channels"
msgstr "Chaînes"

msgctxt "#30501"
msgid "Playlists"
msgstr "Listes de lecture"

msgctxt "#30502"
msgid "Go to %s"
msgstr "Aller à %s"

msgctxt "#30503"
msgid "Show channel fanart"
msgstr "Afficher le fanart de la chaîne"

msgctxt "#30504"
msgid "Subscriptions"
msgstr "Abonnements"

msgctxt "#30505"
msgid "Unsubscribe"
msgstr "Se désabonner"

msgctxt "#30506"
msgid "Subscribe"
msgstr "S'abonner"

msgctxt "#30507"
msgid "My Channel"
msgstr "Ma chaîne"

msgctxt "#30508"
msgid "Liked Videos"
msgstr "Vidéos que vous aimez"

msgctxt "#30509"
msgid "History"
msgstr "Historique"

msgctxt "#30510"
msgid "My Subscriptions"
msgstr "Mes abonnements"

msgctxt "#30511"
msgid "Queue video"
msgstr "File d’attente vidéo"

msgctxt "#30512"
msgid "Browse Channels"
msgstr "Parcourir les chaines"

msgctxt "#30513"
msgid "Popular right now"
msgstr "Suggestions de vidéos"

msgctxt "#30514"
msgid "Related Videos"
msgstr "Vidéos similaires"

msgctxt "#30515"
msgid "Auto-Remove from 'Watch Later'"
msgstr "Auto suppression de 'Regarder plus tard'"

msgctxt "#30516"
msgid "Folders"
msgstr "Dossiers"

msgctxt "#30517"
msgid "Subscribe to %s"
msgstr "Souscrire à %s"

msgctxt "#30518"
msgid "Go to '%s'"
msgstr "Aller à '%s'"

msgctxt "#30519"
msgid "and enter the following code:"
msgstr "et entrer le code suivant :"

msgctxt "#30520"
msgid "Add to..."
msgstr "Ajouter à..."

msgctxt "#30521"
msgid "Select playlist"
msgstr "Sélectionner la liste de lecture"

msgctxt "#30522"
msgid "New playlist..."
msgstr "Nouvelle liste de lecture…"

msgctxt "#30523"
msgid "Language"
msgstr "Langue"

msgctxt "#30524"
msgid "Select language"
msgstr "Sélectionner la langue"

msgctxt "#30525"
msgid "Select region"
msgstr "Sélectionner la région"

msgctxt "#30526"
msgid "Adjust"
msgstr "Ajuster"

msgctxt "#30527"
msgid "Language and region?"
msgstr "Langue et région ?"

msgctxt "#30528"
msgid "Rate..."
msgstr "Noter..."

msgctxt "#30529"
msgid "I like this"
msgstr "J'aime"

msgctxt "#30530"
msgid "I dislike this"
msgstr "Je n'aime pas"

msgctxt "#30531"
msgid "Play all"
msgstr "Tout lire"

msgctxt "#30532"
msgid "Default"
msgstr "Défaut"

msgctxt "#30533"
msgid "Reverse"
msgstr "Inverser"

msgctxt "#30534"
msgid "Shuffle"
msgstr "Aléatoire"

msgctxt "#30535"
msgid "Select the order of the playlist"
msgstr "Sélectionner l'ordre de la liste de lecture"

msgctxt "#30536"
msgid "Updating Playlist..."
msgstr "Mettre à jour la liste de lecture…"

msgctxt "#30537"
msgid "Play from here"
msgstr "Lire à partir d'ici"

msgctxt "#30538"
msgid "Disliked Videos"
msgstr "Vidéos que vous n'aimez pas"

msgctxt "#30539"
msgid "Live"
msgstr "Live"

msgctxt "#30540"
msgid "Play with..."
msgstr "Lire avec..."

msgctxt "#30541"
msgid "Show channel name in description"
msgstr "Afficher le nom de la chaîne dans la description"

msgctxt "#30542"
msgid "rtmpe streams are not supported"
msgstr "Le streaming rtmpe n'est pas supporté"

msgctxt "#30543"
msgid "Refresh"
msgstr "Actualiser"

msgctxt "#30544"
msgid "More Links from the description"
msgstr "Plus de liens à partir de la description"

msgctxt "#30545"
msgid "No further links found."
msgstr "Aucun autre lien trouvé."

msgctxt "#30546"
msgid "Please log in twice!"
msgstr "Veuillez vous connecter en deux fois !"

msgctxt "#30547"
msgid "You must enable two applications so that YouTube is functioning properly."
msgstr "Vous devez activer les deux applications pour que YouTube fonctionne correctement."

msgctxt "#30548"
msgid "More..."
msgstr "Plus…"

msgctxt "#30549"
msgid "No videos streams found"
msgstr "Aucun flux vidéos trouvé"

msgctxt "#30550"
msgid "Region"
msgstr "Région"

msgctxt "#30551"
msgid "Recommendations"
msgstr "Recommandations"

msgctxt "#30552"
msgid "Maintenance"
msgstr "Maintenance"

msgctxt "#30553"
msgid "Delete function cache database"
msgstr "Supprimer la base de données du cache"

msgctxt "#30554"
msgid "Delete search history database"
msgstr "Supprimer la base de données de l'historique des recherches"

msgctxt "#30555"
msgid "Clear function cache"
msgstr "Effacer les fonctions du cache"

msgctxt "#30556"
msgid "Clear search history"
msgstr "Effacer l'historique"

msgctxt "#30557"
msgid "function cache"
msgstr "fonctions cache"

msgctxt "#30558"
msgid "search history"
msgstr "historique des recherches"

msgctxt "#30559"
msgid "Delete settings.xml"
msgstr "Supprimer settings.xml"

msgctxt "#30560"
msgid "Subtitle language(s) to download"
msgstr "Sous-titre langue(s) à télécharger"

msgctxt "#30561"
msgid "None"
msgstr "Aucun"

msgctxt "#30562"
msgid "All"
msgstr "Tous"

msgctxt "#30563"
msgid "Setting"
msgstr "Paramètres Kodi"

msgctxt "#30564"
msgid "Setting, English"
msgstr "Paramètres, Anglais"

msgctxt "#30565"
msgid "English"
msgstr "Anglais"

msgctxt "#30566"
msgid "Prompt"
msgstr "Sélection langue"

msgctxt "#30567"
msgid "Set as Watch Later"
msgstr "Définir comme 'Regarder plus tard'"

msgctxt "#30568"
msgid "Remove as Watch Later"
msgstr "Supprimer 'Regarder plus tard'"

msgctxt "#30569"
msgid "Are you sure you want to remove '%s' as your Watch Later list?"
msgstr "Êtes-vous sûr de vouloir supprimer '%s' comme liste 'Regarder plus tard' ?"

msgctxt "#30570"
msgid "Are you sure you want to replace your current Watch Later list with '%s'?"
msgstr "Êtes-vous sûr de vouloir remplacer votre liste 'Regarder plus tard' avec "%s" ?"

msgctxt "#30571"
msgid "Set as History"
msgstr "Définir comme historique"

msgctxt "#30572"
msgid "Remove as History"
msgstr "Supprimer l'historique"

msgctxt "#30573"
msgid "Are you sure you want to remove '%s' as your History list?"
msgstr "Êtes-vous sûr de vouloir supprimer l'historique '%s' de votre liste ?"

msgctxt "#30574"
msgid "Are you sure you want to replace your current History list with '%s'?"
msgstr "Êtes-vous sûr que vous voulez remplacer votre liste historique avec '%s' ?"

msgctxt "#30575"
msgid "Succeeded"
msgstr "Réussi"

msgctxt "#30576"
msgid "Failed"
msgstr "Échoué"

msgctxt "#30577"
msgid "Settings"
msgstr "Paramètres"

msgctxt "#30578"
msgid "Force SSL Certificate verification"
msgstr "Forcer la vérification du certificat SSL"

msgctxt "#30579"
msgid "MPEG-DASH is enabled in the YouTube settings, however inputstream.adaptive appears to be disabled. Would you like to enable inputstream.adaptive now?"
msgstr "MPEG-DASH est activée dans YouTube, cependant inputstream.adaptative semble être désactivé. Voulez-vous activer inputstream.adaptive maintenant ?"

**Comment by anxdpanic** [comment]
Added by @jdf76  1acba60f4fcecd01acc2a4fbed5014c6e1caadd7
