### ISSUE TITLE
SPMC 16.4: Unable to Sign In

### ISSUE THREAD

**Issue by ZacharyFoxx** [jdf76/plugin.video.youtube#284]
Hi,

With version 5.4.5 was perfect but after upgraded to 5.5.0 I am impossibility to sign in to YouTube. API Keys work.

I reverted to version 5.4.5 and everythins is ok again.

**Comment by anxdpanic** [comment]
Need a debug log.

**Comment by ZacharyFoxx** [comment]
Hi,

The log using 5.5.1: [spmc.log](https://github.com/jdf76/plugin.video.youtube/files/1750261/spmc.log)

Because the version 5.4.5 had the problem to play some videos, I upgraded to version 5.5.1 and everything works. But, If i try to do a clean install using 5.5.1, I can't logging into my account.

**Comment by anxdpanic** [comment]
Strange.
It's saying it can't resolve the name to access the login endpoint. Are you using a VPN/proxy by chance?
The connection that is failing is, https://accounts.google.com/o/oauth2/device/code you can test this in a browser, if working it will return.
```
{
  "error" : "invalid_request"
}
```

**Comment by ZacharyFoxx** [comment]
I did the test in my network and It is working:

![screenshot_2018-02-25-08-03-22_com android chrome](https://user-images.githubusercontent.com/23250218/36640680-8e042e98-1a02-11e8-8a06-c67645f5863a.png)

**Comment by ZacharyFoxx** [comment]
Well, the problem persist.
Is there problem use the 5.4.8 with spmc 16.4, based on kodi 16 Jarvis??

**Comment by anxdpanic** [comment]
Not that I'm aware of.

**Comment by ZacharyFoxx** [comment]
Hi,

Sorry for answering so late.

Well, I tried use only the version 5.4.8 but even this version show the same problem. The only way that I found to install the plugin was install the version 5.4.5 and do all the configuration and Sign in into my account without use the API Keys.

After that, I did the upgrade to last version and configured the API keys.

What could be?

**Comment by anxdpanic** [comment]
Closing, unable to provide support SPMC
