### ISSUE TITLE
Once more, videos stopped playing

### ISSUE THREAD

**Issue by pitsi** [jdf76/plugin.video.youtube#287]
Goodmorning guys and sorry to bug you with my old kodi 14.2 again :(

When trying to play a video, here is what I get on 5.4.6 on kodi 14

https://paste.debian.net/1010714/
(paste will be available for 90 days so take your time)

Where have I seen that insecure-blablabla thing? It uses my api keys etc. Videos were playing yesterday or the day before.
Also, videos play as they should on youtube 6.0.0 alpha6 on kodi 17.6 on the desktop (I reset youtube after installation, so no api keys etc installed) but I did not test them on the 5.5.0 on kodi 17.6 (libreelec on pi zero).

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/releases/tag/5.4.8

**Comment by pitsi** [comment]
Wow! Thank you very much for the quick fix.
