### ISSUE TITLE
Skip video forward/backwards will cut the sound for a few seconds

### ISSUE THREAD

**Issue by meoz** [jdf76/plugin.video.youtube#294]
When skipping forward/backwards in Kodi 17, the video will play fine but the sound would only come on after a few seconds. 
Is there a way to make skipping video sync with the audio ?

**Comment by anxdpanic** [comment]
Is this with mpeg-dash enabled? If so this is a known issue with v17 releases of inputstream.adaptive, and is fixed in the Kodi 18 versions.

**Comment by meoz** [comment]
Installed Kodi 18 test vesion and seems to be fixed for now.
