### ISSUE TITLE
Livestream titles never get changed

### ISSUE THREAD

**Issue by Razzeee** [jdf76/plugin.video.youtube#296]
I did an addon where I gab the Metadata on my own and hand off the video to the YouTube addon to be played.
https://github.com/Razzeee/plugin.video.rocketbeans/blob/master/resources/lib/youtube.py#L11

Is there a better way to start a livestream or is this a bug?

**Comment by anxdpanic** [comment]
Not sure what you mean by them never getting changed. Are you able to provide a screenshot to clarify?

If you'd like more control in your add-on, you can use the youtube add-on as a module and use
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_resolver.py#L89
It will return a dict with all streams, headers/cookies, subtitles and metadata. (addon_id is only in v6) Using this you'll have to set the dash properties on the dash playable items as well, https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py#L32-L40
inputstream.adapative >= 2.0.12 is required for working live streams atm

There is also https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_requests.py (again addon_id is only in v6)

With the addon_id param in v6 you'll also be use registered api keys in place of youtube add-on's keys, this lacks login support for the developer keys which I expect to add in a following release.
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_registration.py

**Comment by Razzeee** [comment]
For e.g. this livestream https://www.youtube.com/watch?v=B0x4UjaQIv0
At the moment I'm writing it it has the title: "Zocken mit Denzel - RimWorld E05" whenever you look at this in some minutes, they will change the title of the stream. This title seems to get cached somewhere.
So if I would not do a fist run of my addon on a fresh system, it would get the title from above.
If I come back in some days it will have another title, which I show in the listing. But if I start the playback the player view still has the old name.

This is my listing for right now:
![grafik](https://user-images.githubusercontent.com/5943908/36799930-9584ca52-1cae-11e8-8ac9-762e4e20f6ba.png)

If I now start the playback I get a cached value from when I first started that stream on my system.
![grafik](https://user-images.githubusercontent.com/5943908/36799945-a218f77a-1cae-11e8-8020-bc11b0ec2c21.png)

**Comment by anxdpanic** [comment]
Doesn't seem like the correct behavior, I should have some time this evening to look into it. I've got current master of rocketbeans installed and played the live stream, so hopefully when I come back to it I can reproduce.

**Comment by Razzeee** [comment]
Well to let you know, there is caching in kodi for the thumbnails, which I circumvent for the livestream in the rocketbeans addon master. So it might be a core problem, let me know when you find something.

**Comment by anxdpanic** [comment]
This was our issue, will be fixed for v6. Thanks 👍

**Comment by Razzeee** [comment]
Thank you makes me very happy! 💃
