### ISSUE TITLE
Inputstream.adaptive and mpeg-dash support - check on install?

### ISSUE THREAD

**Issue by Fludizz** [jdf76/plugin.video.youtube#298]
Seen that it is required to use mpeg-dash (and thus inputstream.adaptive) to support live video and 1080p video, it would seem to make sense to always try and enable this by default on installation.

I suppose this would require the plugin to check for presence and version of inputstream.adaptive on the system during installation or upgrade. If it doesn't find it installed, or doesn't have the right version, then don't enable mpeg-dash. If it finds the right version then it should enable mpeg-dash.

Is this a feasible check to do during installation/upgrade? I would assume this would help a lot of users that are not too tech savvy to still get their live streams (and 1080p) working :)

Users that are tech savvy enough to find/know about mpeg-dash will likely be able to get inputstream installed, so this feature would just be for those less tech savvy that buy one of those prebuilt/"out-of-the-box" Kodi systems.

**Comment by anxdpanic** [comment]
I will look at adding a check/prompt to livestreams, and dash-proxy for the next version. Switching to ~beta I don't want to add new code/strings so the translators can do their thing once beta hits and not have to chase changes.

We can enable inputstream.adaptive, we do prompt for that if mpeg-dash is enabled and inputstream.adaptive isn't. However we can't change inputstream.adaptive settings(affects more than our add-on so needs to be configured by the users), so enabling by default would end up in unexpected low quality to the unknowning.

**Comment by Fludizz** [comment]
Understood, it is a low-prio enhancement if you ask me :)
The quality indeed depends on the settings of inputstream. I believe for LibreELEC the default settings are already set to allow for 1080p streaming (I believe it was already set to 'max' by default).

**Comment by anxdpanic** [comment]
For >720 you need to enable mpeg-dash and mpeg-dash proxy in the add-on settings under MPEG-DASH. Then enable and configure InputStream Adaptive, set min bandwidth to 30000000, enable ignore display resolution, and set stream selection to auto.

Also to update InputStream Adaptive on LE I believe it is 'sudo apt-get install kodi-inputstream-adaptive'.

**Comment by Xmetalfanx** [comment]
Ok not sure why that didn't work before but I tried a random video and it IS in 1080P ... thank you.   I MAY have had the min band. set to 3,000,000 vs 30,000,000 like you said .. I am pretty sure I tried the proxy settings but it was only 720p max before ... probably has to do with both of those settings TOGETHER ... anyway unrelated to this, if i could just get the personal API Key working on the addon RELIABLY ... it takes away my PRIMARY use case that I'd be getting an Amazon Firestick for .. now if i could count on the YT addon in LE, there is no need for me to get a Firestick. 

Thanks again.

**Comment by anxdpanic** [comment]
In ~alpha11 I've updated the mpeg-dash settings to separate Videos and Live streams(both default enabled if mpeg-dash is enabled) and provide inputstream adaptive requirements there. Also in the Kodi 18 nightlies the m3u8 live streams appear to be working again.

The additional bits I think are better suited to the FAQ and possibly the README.
