### ISSUE TITLE
livestreams end after 5 seconds of playback

### ISSUE THREAD

**Issue by SimPiko** [jdf76/plugin.video.youtube#299]
Raspberry Pi 2
Kodi 17.6 (from Raspbian repository)
youtube addon 5.5.1, also tried with 6.0.0~beta2
inputstream.adaptive 2.0.10 (newest available on Rasbian repository, so can't use DASH thingy)

For some unknown to me reason, any livestream played through youtube plugin stops playing after about 5 seconds (happens on both video streams, and audio-only streams)
Can't find anything about that bug on google. The only thing that i've deduced is that updating inputstream.adaptive to 2.0.19 could fix it (although i don't know how that could affect non-dash streams), but I can't find any info at all how to compile newer version of it, neither if there already is precompiled update anywhere. I've already tried to compile Kodi itself (krypton branch) but i'm stuck on what to do next...

**Comment by anxdpanic** [comment]
Yea, only dash live streams are working, and they require inputstream.adaptive >= 2.0.12

**Comment by SimPiko** [comment]
drat... so the only way to get streams working is to update to Kodi 18? or it's just Youtube messing up the plugin?

**Comment by anxdpanic** [comment]
You'd need to look into compiling binary add-ons to compile 2.0.19 for Krypton or request the package be updated @ raspbian

The kodi 18 version of inputstream.adaptive should work as well. 

YouTube has changed something with the HLS streams, I've tried resorting back to master playlist but that no longer works either, so the dash counterpart is the only option currently.

**Comment by SimPiko** [comment]
hmmm... okay then, thanks for answers, gonna try compiling again i guess

**Comment by Flavien** [comment]
I have the same problem on Kodi 17.6 on a FireTV with InputStream Adaptive 2.0.19. [This is the video causing problem](https://www.youtube.com/watch?v=J78SdCzzumA).

Are you saying this stream won't work because the video is not DASH?

**Comment by webodan** [comment]
Same problem here on a Pi3 B+running the latest stable LibreELEC based on kodi Krypton.  I tried installing commit f011cb3 and re-activating my YouTube account, didn't fix any livestream I tried.

**Comment by anxdpanic** [comment]
You'll need inputstream.adaptive version 2.0.12 or greater installed, and mpeg-dash enabled for live streams in the YouTube add-on settings(and some videos will still have issues). With Kodi 18 live streams are working with or without mpeg-dash, and Kodi 18 appears to be very close to release.

**Comment by webodan** [comment]
Oh thank you for your swift response! I'll update kodi to v18 later
