### ISSUE TITLE
Mark videos as watched

### ISSUE THREAD

**Issue by R0nd** [jdf76/plugin.video.youtube#303]
Videos played in the plugin are not marked as watched on youtube.

**Comment by Fludizz** [comment]
How are you playing the video's? By selecting them through the plugin or by sending them from another device via the API?

Video's selected via the plugin itself seems to mark everything watched OK - video's send through the API (e.g. via Yatsee on Android or "Send to Kodi" browser plugins) are indeed not being marked as watched.

**Comment by R0nd** [comment]
I play videos by selecting them through the plugin. The videos that I have played in the plugin are marked with a checkmark in the plugin, but not marked as watched on youtube and not added to my youtube history. Conversely, the videos I have played on youtube are not marked with checkmarks in the plugin.

**Comment by anxdpanic** [comment]
Currently in add-on, we are only able to list watch history or clear watch history. The old method of adding to watch history no longer works, and it's not part of the YouTube API which is why playing videos in add-on don't get marked on the web/app.

**Comment by anxdpanic** [comment]
Latest version 6.1.0~beta1 includes a fix for adding to watch history. https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev
