### ISSUE TITLE
Refreshing livestream title & thumb

### ISSUE THREAD

**Issue by greystashh** [jdf76/plugin.video.youtube#306]
Would it be possible to refresh the title and thumbnail for 24/7 livestream channels which have several shows whole day? ATM it is only displayed the thumb which started the stream and the title isn't updated as well.

The meta informations are able to find with `https://www.googleapis.com/youtube/v3/videos?key=YOUR_API_KEY&part=snippet&id=VIDEO_ID` in items:title/thumbnails

The twitch addon already updates the stream infos after you reopen the channel list. Can you adapt it?

**Comment by greystashh** [comment]
Thanks for resolving. Theres another small issue concerning the displayed title which is played at the moment in kodi. I think the text format is not utf8  compared to the video listing items so that umlauts or symbols are indicated correctly

**Comment by anxdpanic** [comment]
Good catch, should be resolved with 9e4c103, going to wait a until at least tomorrow before bumping version.

**Comment by anxdpanic** [comment]
I've posted beta7, can you confirm this is resolved for you as well please.

**Comment by greystashh** [comment]
It's workink, thanks

There's another issue which I have recognized. If I select the 'Live' folder I'm getting different listings compared to desktop mode. It might not select the streams in the prefearred language first.  Would it be possible to adapt the list to selected region?

**Comment by anxdpanic** [comment]
We pass region and language parameters in those requests as per the api. Do you have a specific example so I can directly check hopefully tomorrow?

**Comment by greystashh** [comment]
If you look at https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig/  I'm getting another 
streams in kodi listed

**Comment by anxdpanic** [comment]
Okay, so there is a relevanceLanguage param, which I have added for next bump. As for relevant region, we're passing the region, but there is also a location and location radius option which are coordinate based and without gps not sure atm how this could be done accurately from Kodi.

**Comment by anxdpanic** [comment]
I've opened #315 for this, will be looked at for 6.1
