### ISSUE TITLE
Profile compatibility 

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#312]
I'm on beta 7.

When the kodi master profile has the YouTube plugin disabled, MPEG DASH won't work on a secondary profile, that has YouTube enabled. 

I think this might be related to #307, I'll continue fiddling around.

**Comment by anxdpanic** [comment]
I should have this resolved in the next bump.

**Comment by anxdpanic** [comment]
Fixed by #317 b43b784bf82512d1f23d503296842cb041a5a41b

**Comment by pannal** [comment]
Switched to the current master, as there isn't a beta8 release. Seems to work, I'll report back and reopen if it doesn't. Thank you!
