### ISSUE TITLE
Cast/Streaming target

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#314]
Hey, 

I'm using a 2013 Samsung TV that has a native YouTube app. With that I can cast from the YouTube app on my mobile device directly to my TV. 

Is this feature planned and/or possible with this plugin? 

Thank you!

**Comment by anxdpanic** [comment]
This isn't planned for this add-on. There are a few ways to achieve this, you can use Kore/Yatse on your mobile device and share videos from the YouTube app to Kodi YouTube add-on. 
Or a relatively new script/add-on, https://github.com/enen92/repo-scripts/tree/1cf42884578cc668de2fca3b3a5c64dc830d2af9/script.tubecast

**Comment by pannal** [comment]
Nice, will try, thank you!

**Comment by pannal** [comment]
TubeCast works great. Closing.
