### ISSUE TITLE
Geo-location for relevant regional search results

### ISSUE THREAD

**Issue by anxdpanic** [jdf76/plugin.video.youtube#315]
https://developers.google.com/youtube/v3/docs/search/list
params: 
location:  '(37.42307,-122.08427)'
locationRadius: m, km, ft, and mi <1000km
http://freegeoip.net

**Comment by greystashh** [comment]
Couldn't this be related to chosen location and language which you select with the setup in the addon instead of tagging IP geo location?

**Comment by anxdpanic** [comment]
The parameters requires lat, long and a radius. It looks doable with freegeoip.net for next version.

**Comment by greystashh** [comment]
I see. Would it then be also possible to mark upcoming livestreams which are already sceduled in YouTube as upcoming with another color and the announced Start time in brackets behind the title in the list?

**Comment by anxdpanic** [comment]
I'm not sure off hand how scheduled is handle in the api. Can you open a new issue for this and I will look into adding it for 6.1 as well, will require new string/setting for highlighting to be color blind friendly. For 6 I'll look into adding the bracketed start time.

**Comment by anxdpanic** [comment]
Closed by #349
