### ISSUE TITLE
MPEG DASH resolution capped at 1080p

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#316]
Continuing from https://github.com/jdf76/plugin.video.youtube/issues/307#issuecomment-375650449.

tl;dr: I'm "only" receiving streams up to 1080p, not 1440p. It worked before. May this be related to #312? If I remember correctly, when it worked, I was using the master profile.

@anxdpanic Can you give me an example of a media file with a higher resolution than 1080p, that should work, so I can try that one specifically?

**Comment by anxdpanic** [comment]
video id: Bey4XXJAqS8
if you'd like to resolve your other issue before the next bump, just change
https://github.com/jdf76/plugin.video.youtube/blob/master/addon.xml#L12 from start="startup" to start="login"

**Comment by pannal** [comment]
OK, I can confirm that that video plays in 1440p. Thank you.

Can you elaborate on the impact of the minimum bandwidth setting a little bit more? I'm not exactly sure what it does. The bandwidth minimum is set to determine whether to use MPEG DASH or not, depending on what, the bitrate of the video, or the actual bandwidth of my connection?

This might be a question more fitting for the inputstream.adaptive project, but I thought I'll give it a shot.

**Comment by pannal** [comment]
Great, thank you for the explanation. So setting the min bandwidth to 30mbit ensures I always receive the stream with the highest resolution?

What's the setting for, then? Wouldn't `0` achieve the same effect?

**Comment by anxdpanic** [comment]
I've had mixed results with 0 so I've always configured it myself.

**Comment by anxdpanic** [comment]
Is this okay to close?

**Comment by pannal** [comment]
Yep, sure.

**Comment by anxdpanic** [comment]
If you have any other questions, or issues let me know. Thanks for helping improve things 👍
