### ISSUE TITLE
live streams do not show all channels

### ISSUE THREAD

**Issue by CrYpT0n1T3** [jdf76/plugin.video.youtube#319]
Hello.
I have a set Polish region. In live broadcasts, I do not show Polish online channels only those from the world.
Can you change it somehow? Transmissions from the world also do not show everyone, with me two pages of 50 stream.

**Comment by anxdpanic** [comment]
This is related to #315 'Live' events are found by search, will be looking to add it for 6.1

**Comment by anxdpanic** [comment]
With latest alpha, run setup wizard to perform geolocation. This will enable 'My Location' to provide location relevant live and search results. Beyond this it's an api limitation.

Closed by #349
