### ISSUE TITLE
Mark upcoming livestreams in brackets

### ISSUE THREAD

**Issue by greystashh** [jdf76/plugin.video.youtube#321]
It would be nice if you could mark upcoming livestreams with startdate behind the title in brackets. There is an annotation in lib.youtube_request.py, line 310 (param event_type). Maybe that might help you to integrate

`
    :param event_type: 'live', 'completed', 'upcoming'
 `

**Comment by greystashh** [comment]
Maybe the better presentation is:

(Live @ %H:%M) | title
If Live is not the same day:
(Live on %d.%m. @ %H:%M) |  title

**Comment by greystashh** [comment]
@anxdpanic:  Do you plan integrate this still in 6.0.0 or will you release the version final first?

**Comment by anxdpanic** [comment]
Will be for 6.1 and likely one of the earliest additions. v6 is about ready just making some final updates for Purchases first.

**Comment by greystashh** [comment]
Are you already working on 6.1?

**Comment by anxdpanic** [comment]
@greystashh Not yet, should have some time to start soon

**Comment by greystashh** [comment]
Are you back from the death? ;) Nice to hear from you. 

Besides will you release 6.0 final these days?

**Comment by anxdpanic** [comment]
I should be back for the most part, thank you. :) Just giving some time for the reusepython pr to be included in master so I can make any changes necessary before I bump 6 to release. Hoping to get started on some of the 6.1 features in the next couple days while waiting.

**Comment by anxdpanic** [comment]
So I did what I could. YouTube doesn't seem to provide the air time/date in the results, which means to achieve this would be 50+ http requests per page. So I've added a folder for Completed and Upcoming, the only way to tell when an Upcoming event is expected is to select the item.

https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev

**Comment by anxdpanic** [comment]
Was blind the other day I guess, I was able to get this working.
Closed by #349
