### ISSUE TITLE
Don't offer video rating unless watched

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#325]
Currently, when automatic video rating is enabled, it always pops up after a video has been stopped. 

This should only occur after the video has been watched at least 85% (?).

**Comment by pannal** [comment]
Awesome :)

**Comment by anxdpanic** [comment]
I've added a play count minimum percent in d73970e5f092fd4c03688e20c2a021d785fce552
[add] Play count minimum percent (default: 85%) Settings -> General -> Play count minimum percent
This is the threshold for counting as watched and triggering post play events(other than refresh).

Available in ~alpha7 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev
