### ISSUE TITLE
Too slow research

### ISSUE THREAD

**Issue by Gythion** [jdf76/plugin.video.youtube#326]
Hi, when I made a search with 5.5.1 and 6.0 beta, it makes too  much time for a search, and much often, it can't. Already cleared cache. With version 5.4.1, no problem. Here is my log: https://is.gd/OyoRxU

**Comment by anxdpanic** [comment]
Can you try ~beta10 from https://github.com/jdf76/plugin.video.youtube/releases/tag/6.0.0-dev the hang on some requests should be resolved.

**Comment by anxdpanic** [comment]
Will need to open a new issue with a clean device(no add-ons that are banned on the kodi forum) and a log reproducing it with debugging enabled.
