### ISSUE TITLE
Refresh list after playback ended

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#328]
It would be nice to automatically check for updates of the current list after watching a video from it. 

Currently, to see new videos that got published while I was watching one from my subscriptions, I have to exit and reenter the current view.

**Comment by pannal** [comment]
OK, that makes it a bit easier. I'd still love this as a separate feature, though.

**Comment by anxdpanic** [comment]
I look to add it as a post play event in the next version

**Comment by opav** [comment]
Please make it as a optional user settings.  I'm against refresh after play, as that will obviously cause a delay after every play event, personally I prefer faster UI navigation and response which btw has improved tremendously in recent releases - thank you.

**Comment by anxdpanic** [comment]
Closed by #348 It's defaulted to off.
