### ISSUE TITLE
More information about the videos in views

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#329]
I don't know whether that's something the skin would have to support, but I'd like to be able to see not only the video title, but also the username who posted the video and when, in poster/fanart views. 

A bit like in the official YouTube apps. I can somewhat circumvent that by using the infowall view mode, but in order to see the username/channel who posted the video, I'd have to navigate to it. Also in the info panel there's no information about when it was posted. 

Thank you!

**Comment by anxdpanic** [comment]
Have you tried the unofficial version? In the normal version we use the content type of videos(required by official repo) and the unofficial uses the content type of episodes. There are more views and more details for episodes.

**Comment by pannal** [comment]
I'm using a git-checkout at the moment. How do I switch content-types there?
Or am I required to use the unofficial releases you put out instead?

**Comment by pannal** [comment]
Do I have to use the override-view advanced settings? Just by switching the branch, nothing changed.

**Comment by anxdpanic** [comment]
Override will force the view you want always. You can test the views by changing them in the left pullout panel when on a list of videos.

**Comment by pannal** [comment]
Yeah, there's only InfoWall, Wall and WideList, as before.

**Comment by anxdpanic** [comment]
That is an Estuary limitation, could have sworn it had more though. If you change to confluence and change between official - unofficial you'll see quite a few additional views.

For the most part though channel name is only visible in the plot under the title in both skins. Most stuff is made available in properties and the skin decides how show them. ie. With estuary if you change sort from default to date/date added the date will show on the thumbnail instead of time.

**Comment by pannal** [comment]
Okay, I just tried Confluence, but there's not really more information visible in the Thumbnail view (the others are mostly list views), compared to Estuary.

Is there a way for plugins to provide their own views? I'd love for the youtube views to be a little more informative, like the official YT plugins.

**Comment by anxdpanic** [comment]
That portion is all on the skin side, for something like this on the add-on side a full gui/dialog would have to be created, which would be a large undertaking. Best option is to test out some different skins to find one that lays out information the way you'd like, would use unofficial for this as well.

**Comment by pannal** [comment]
Understood, thank you for the explanation.

This might be a bit out of scope, but is there a skin you know of, that displays the channel's name in a thumbnail/wall view?

**Comment by pannal** [comment]
I'm adapting this to my estuary skin fork, [estuary_plex](https://github.com/pannal/skin.estuary_plex), so the InfoWall items show the artist and the air date, which works quite well!

It currently displays the air date itself, but when something was aired recently, I'd like to have "2 hours ago", "14 min ago" and so on. It doesn't seem like anything besides the isodate is set as a parameter - could you add some dynamic parameter like `$INFO[ListItem.AiredFromNow]`?

**Comment by pannal** [comment]
I guess that's only possible via custom window attributes, not the info items, right?

**Comment by anxdpanic** [comment]
Not sure how this could be done for skinning, having this add-on do it would cause the translation to be required in add-on for a skin element. If you want to try some things 
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_items.py#L105 you can use setProperty() in this area, and in the skin use ListItem.Property() in the skin I believe. I think you could also use a custom script for use with your skin that generates additional info, though I'm not really familiar with skinning.

**Comment by pannal** [comment]
@anxdpanic that's a really great place to start. I'll look into it, thank you very much!

**Comment by pannal** [comment]
@anxdpanic I was just looking at `resources.lib.youtube_plugin.kodion.utils.datetime_parser.parse` - you receive ISO 8601 timestamps from YouTube with Z at the end, so they're UTC. I can't see the parse function to pass that information to the later generated time/date/datetime objects.

Do you do any timezone adjustments there? If not, that might be an issue with times/dates.
