### ISSUE TITLE
YouTube playlist always start at the second video

### ISSUE THREAD

**Issue by rabin111** [jdf76/plugin.video.youtube#33]
Hello

I have found a bug when trying to play a playlist from YouTube.

I have go to YouTube mobile app then search for any playlist. After that just share to Yaste which is forwarded YouTube playlist to Kodi YouTube addon. The problem is when YouTube addon play the playlist, it always play at the second video of that playlist.

Cloud you please find and investigate this issue. You can contact me anytime, if you need more information.

Thank you

**Comment by anxdpanic** [comment]
Should be resolved in current master. Tested from strm and Yatse
