### ISSUE TITLE
Some times the load of new page hangs on loading indefinitely

### ISSUE THREAD

**Issue by rafaelSorel** [jdf76/plugin.video.youtube#330]
Some times when navigate between categories and page , the plugin loads indefinitely , nothing to do,we need to restart the plugin !

**Comment by rafaelSorel** [comment]
I have Identified the source of the problem, indeed the problem come from the **sleep** part of this piece of code :

>         
        """
        Tests revealed that sqlite has problems to release the database in time. 
        This happens no so often, but just to be sure,
        we try at least 5 times to execute out statement.
        """
        for tries in range(5):
            try:
                return self._cursor.execute(query, values)
            except TypeError:
                return None
            except:
                time.sleep(2)
        else:
            return None


So we basically, run into the **time.sleep(2)**, **50** times for the **50** entry and each time **5** retries so this result to a timeout of 50 X 5 X 2 = **8 Min 33 Sec** .

I think this part of code needs to be handled differentely.
In order to confirm the rootcause I have created on my side a dedicated thread with a queue to handle all the insertion for the data base elements and It now works pretty good, no hangs and no big timeouts.

**Comment by anxdpanic** [comment]
Should hopefully have time to look deeper tomorrow, are you going to PR your changes?

**Comment by rafaelSorel** [comment]
It was a quick change done for testing purpose, as soos as I cleanup the code I will submit it as a PR.

**Comment by anxdpanic** [comment]
I've updated the caching a bit, and adjusted the wait time drastically.
If you want to give it a try: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.0.0-dev

Thank you for digging into this, and please submit the PR if you feel it's still beneficial.

**Comment by rafaelSorel** [comment]
Sorry for my late reply , I had issues with my machine, the cpu cooling block is dead. Any way, I will try the new tag , and I will PR my changes, then we will see.

**Comment by anxdpanic** [comment]
I've reworked the old caching @ 9d3d8b0977871e9e6471d64101bc104d6e4e4cf9 , function cache for data was very inefficient, so I added a data cache. 
The improvements in my tests:
- database accesses per 50 items: before: 70\~100 after: 4\~6
- load time of 50 items w/ no cached items: before: ~11.6 secs, after: ~3 secs
- load time of 50 items w/ all cached: before: ~0.8 secs, after: ~0.7 secs
- cached size of 50 items: before ~1MB, after ~550KB

If you'd like to test the changes, they are included in [~alpha10](https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev)

This issue should be resolved with these changes, please re-open if you happen to experience it with the latest versions.
