### ISSUE TITLE
Inputstream.adaptive version

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#332]
I'm using the newest beta9, in which you've changed the inputstream.adaptive requirement: https://github.com/jdf76/plugin.video.youtube/commit/f68af6226574b2cda363d392ca9d32beb20d767c

My OSMC Vero 4K box has only version 2.0.19. How do I update that addon?

**Comment by pannal** [comment]
I'm guessing I have to wait for OSMC to update it: https://discourse.osmc.tv/t/inputstream-adaptive-addon/70118/5

**Comment by pannal** [comment]
Latest inputstream.adaptive is 2.0.20 for Krypton.

**Comment by anxdpanic** [comment]
2.0.20 is the latest version of inputstream.adaptive that is available for Krypton. This is why Purchases also says requires Kodi 18

**Comment by pannal** [comment]
Ah, OK, sorry!

**Comment by anxdpanic** [comment]
https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631 for OSMC nightlies that include the latest

**Comment by pannal** [comment]
Yeah, I'm happy with Krypton right now and am not ready to jump on the alpha-stage ship as of yet :D

Thank you!
