### ISSUE TITLE
"My Subscriptions" list not showing right items on page 3

### ISSUE THREAD

**Issue by Fludizz** [jdf76/plugin.video.youtube#334]
I have noticed some odd behaviour with "My Subscriptions". We use this list to keep up to date with all our subscriptions. Lately we have not had as much time to watch and this made the "unwatched" list exceed two pages, however when we go to the third page, it doesn't appear to show the right items anymore. There effectively appears to be a gap between Page 2 and Page 3 in the results.

Running 6.0.0~beta8 on kodi 17.6

Since it doesn't provide any errors, would a debug log be useful at all in this case?

**Comment by anxdpanic** [comment]
Nice catch and thank you for reporting, it was skipping to page 4. Should be resolved in master now.

**Comment by Fludizz** [comment]
Thanks! I manually patched youtube.py and can confirm this works fine now :)
