### ISSUE TITLE
MPEG-DASH keeps reverting to unavailable

### ISSUE THREAD

**Issue by taleteller** [jdf76/plugin.video.youtube#338]
I am using YouTube 5.5.1 on Libreelec 8.2.5. Setup is pretty standard, internet is more than sufficient, only specialty is the usage of two profiles. 

When I install the YouTube app, i can enable MPEG-DASH and configure the required settings. Playing a video afterwards, it gets played at 1080p as expected. 

After rebooting the system, the HD playback stops working. Videos get played at 720p again. When visiting the settings MPEG-DASH is no longer available, meaning its greyed out. 

To enable 1080p playback again I have to uninstall and reinstall the whole YouTube app. Then I am able to configure the options again - until the next reboot. 

The Twitch App on the other hand works fine, showing inputstream.adaptive to run as expected. The problem must be within YouTube. If there is any data I can provide please ask.

**Comment by anxdpanic** [comment]
Multi-profile dash has been fixed in the current betas. 
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.0.0-dev

**Comment by taleteller** [comment]
Sadly that's for Kodi 18, and the milhouse builds from LibreElec are still pretty buggy to me.

**Comment by anxdpanic** [comment]
What is for Kodi 18?

**Comment by taleteller** [comment]
The beta you just liked requires Kodi 18. LibreElec 8.2.5 runs on Kodi 17.

**Comment by anxdpanic** [comment]
The betas are for Kodi 15+, the Kodi 18 requirement is a sub-point to "Purchases"

**Comment by taleteller** [comment]
I see, that was ambiguous on my first look and I can confirm the beta 6.0 to work after rebooting and no longer reverting to disabled. I will test it for a while. Only thing left is that Max resolution seems to be 1440p, 2160p does not seem to be offered, but thats a different story. I guess this Ticket can be closed.

**Comment by anxdpanic** [comment]
I added Kodi 15+ to the top. and fixed the bullet point markdown so hopefully it's more clear now for others. Thank you for confirming 👍 For >1440p you can follow #257
