### ISSUE TITLE
Watched status not working

### ISSUE THREAD

**Issue by steph09** [jdf76/plugin.video.youtube#339]
Upon watching videos the watched marker is not been displayed either for partially or fully watched videos.

It is an issue with the latest alpha/nightly versions of Kodi 18 (Windows 7 64-bit installer) although since it is only a problem that is apparent with the Youtube addon (Both stable & beta versions) I think maybe it is something with the addon rather than kodi???

**Comment by Datafreak** [comment]
I have the same issue, that the watched status doesn't work anymore.
I'm also using the last nightly of Kodi and beta of the Youtube Plugin.

I also have tried to go back to a earlier nightly and beta. But it didn't fixed my issue. Sad
I also can't see an error or so in the Debug-Log: https://paste.ubuntu.com/p/4ScRfx5pKJ/

**Comment by anxdpanic** [comment]
See also #313

**Comment by anxdpanic** [comment]
I've added a playback history that uses custom mark (un)watched/resume points in d73970e5f092fd4c03688e20c2a021d785fce552
[add] Playback history (default: off) Settings -> Advanced -> Use playback history
Available in ~alpha7 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev

**Comment by Datafreak** [comment]
Hi @anxdpanic,

thanks for this feature. I have checked it and it is working for me.

Best Regards,
Datafreak

**Comment by anxdpanic** [comment]
Found a workaround for this until it is fixed in Kodi.
Working in https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.0-dev
