### ISSUE TITLE
Streaming restarts at zero, after a couple of minutes

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#340]
When streaming using the Android YouTube app, to my OSMC with script.tubecast, playback stops after roughly five minutes and restarts from zero - or, if multiple videos are queued, the first one starts, not the current one. 

This even happens when the video is paused using my phone. 

Any pointers? Is it most likely tubecast, your plugin, my youtube android app, or my phone?

**Comment by pannal** [comment]
Ok, it's not my device and not the YouTube android app. It's either tubecast or your script.

**Comment by anxdpanic** [comment]
Haven't used tubecast myself, a debug log may shed some light on what's happening. There usually isn't much we can do once playback has started, but there may be a second event or something triggering what you're seeing.

**Comment by pannal** [comment]
Nope doesn't occur when not streaming. 

I didn't count my actual play requests, but nine sounds too much.

**Comment by pannal** [comment]
So should I open a ticket with TubeCast?

**Comment by pannal** [comment]
Here's the log after a reboot, then DEBUG logging enabled: https://paste.ubuntu.com/p/HFC22Q8wcR/

I've started streaming a couple of minutes later, using YouTube for Android. Never pressed play; pressed stop once after the stream restarted itself to second 0.

**Comment by anxdpanic** [comment]
I would report it to TubeCast as well, looks like [script.tubecast] script.tubecast: setPlaylist: is done right before both play events.

**Comment by enen92** [comment]
@anxdpanic @jdf76 this issue was on tubecast and apparently it looks like it is fixed now. The issue can be closed

**Comment by pannal** [comment]
Yep, fixed.
