### ISSUE TITLE
Germany, content may be inappropriate...

### ISSUE THREAD

**Issue by anxdpanic** [jdf76/plugin.video.youtube#347]
Example videos:
https://youtu.be/IoiA7hU8370
https://youtu.be/sBVqxZDjpC8

**Comment by greystashh** [comment]
What do you mean with inappropriate? I can't see there problems with the example videos

**Comment by anxdpanic** [comment]
Was reported here, if you're confirming they work it may be an age/account issue. https://forum.kodi.tv/showthread.php?tid=325740&pid=2733858#pid2733858

**Comment by anxdpanic** [comment]
Seems it was an issue with an old account pairing where age was correct. Thanks for confirming 👍
