### ISSUE TITLE
Live folder selected by country

### ISSUE THREAD

**Issue by greystashh** [jdf76/plugin.video.youtube#350]
After you have integrated 'My Location' for search results, would it be also possible to use this for selecting the Live folder and upcoming live streams selected by your own location and country?

BTW great work so far. Many thanks for your engagement

**Comment by anxdpanic** [comment]
Not sure what you mean? All 'My Location' (Search, Live, Upcoming Live, and Completed Live) is done based on your own location already. 
I can allow the latitude, longitude to be manually set, like the radius is.

**Comment by greystashh** [comment]
Unfortunately I still get the same results for live content although latitude is set correct with 100 km radius

**Comment by anxdpanic** [comment]
They are all definitely returning different here, you can try going down to 1km and will likely show none or very few results.

To make sure location is being passed, you can enable debugging, clear function cache in Settings -> Maintenance then try My Location -> Live (or which ever one you want to check) You will see a log line like 
```DEBUG: [plugin.video.youtube] [data] v3 request: |GET| path: |search| params: |{'relevanceLanguage': 'en', 'eventType': 'completed', 'maxResults': '10', 'regionCode': 'CA', 'part': 'snippet', 'location': 'xx.xxxx,xx.xxxx', 'hl': 'en', 'locationRadius': '280km', 'type': 'video', 'order': 'relevance'}| post_data: |None|```

location is always redacted(x's) from the log, so it remains private.

I haven't bumped version but I've made the location modifiable in #351

**Comment by greystashh** [comment]
My mistake. I haven't seen the subfolder 'My Location' in the add-on. I've just selected the live content in main folder.

Well but the results I will get within 'My folder' aren't really satisfying. I have set 500km but neither I don't get really the results I expected - most still in English (I live in north Germany next to GB) - nor the results are listed by relevance like it will on YouTube website. I think with this method you can only get streams which are uploaded (mobile) with activated location set points? 

Will you get the prelisted results similar to  youtube live channel in your country?

**Comment by greystashh** [comment]
I see. Its a pity that it doesn't work better.

BTW: Have you seen my post regarding webm in 1440p issue? Would this guide work for YouTube?

**Comment by anxdpanic** [comment]
I agree. 

Sorry missed that, I replied over there.
