### ISSUE TITLE
18+ videos on youtube

### ISSUE THREAD

**Issue by bodyguardroman** [jdf76/plugin.video.youtube#354]
I've logged why cant play 18+videos?
In kodi writing this:Confirm your age by signing in
This video may be inappropriate for some users.
When i logg on website,play 18+VIDEOS without problem.

**Comment by anxdpanic** [comment]
Other users that have reported this were using old 'Brand Channels', you can see some discussion https://forum.kodi.tv/showthread.php?tid=325740&pid=2737336#pid2737336 
If you can provide a video id that is causing the issue for you, I can test to see if it is working here.

**Comment by bodyguardroman** [comment]
https://www.youtube.com/watch?v=nsBhd9difeI
this is video,but every video with 18+ not play in Kodi.
this is fix without login:
http://www.nsfwyoutube.com/watch?v=nsBhd9difeI
can you add nsfw fix for 18+videos to youtube addon?

**Comment by anxdpanic** [comment]
Tested that video and it is working. You may not have the birth date set properly or you may be using a 'brand channel'(age gated content don't work, would need a newer account). I would try configuring the birth date first, for more information see https://forum.kodi.tv/showthread.php?tid=325740&pid=2734101#pid2734101 and the post after.
