### ISSUE TITLE
Error: Invalid relevance language 

### ISSUE THREAD

**Issue by Caballlero** [jdf76/plugin.video.youtube#356]
I can not play any youtube videos, from v6.1.0=alpha4

**Comment by anxdpanic** [comment]
relevanceLanguage should only be used on search and live. Can you try Settings - Advanced - Enable setup-wizard, then open the add-on and reconfigure language, and region. If it's still an issue, can you provide the Language and Region values shown on Settings - Advanced so I can try to reproduce the issue, thanks.

**Comment by Caballlero** [comment]
yes is fixed. thanks
