### ISSUE TITLE
Error 403 playing a video

### ISSUE THREAD

**Issue by advidsec** [jdf76/plugin.video.youtube#358]
Video doest not run generating a 403 forbbiden:

14:09:39.586 T:1508897712  NOTICE: [plugin.video.youtube] Running: YouTube (6.0.2) on Krypton (Kodi-17.4) with Python 2.7.9
                                                Path: /play/
                                                Params: {'video_id': 'GKKD8grttQ4'}
14:09:41.575 T:1946157728   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://r5---sn-h5q7dnel.c.youtube.com/videoplayback?mv=u&mt=1527508586&ms=nxu%2Conr&cp=U0pRTFVOTl9NSkNQMV9NSFJKOlFrcktqY3NmWlA4&id=o-AB7Sa0ZUy76Aj44oKAZf_G9HJ1fg0zRT8qOuRBF8sDiI&mn=sn-h5q7dnel%2Csn-4g5e6nzl&mm=30%2C26&ip=37.132.142.141&pl=24&expire=1527530980&source=youtube&ei=hPELW_LDLp6IWPPThagM&requiressl=yes&itag=22&lmt=1527445257169960&sparams=cp%2Cdur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csc%2Csource%2Cexpire&ipbits=0&fvip=4&sc=yes&ratebypass=yes&dur=261.015&c=WEB&mime=video%2Fmp4&key=yt6&signature=34307FC471416728FE515DD8953D0BC6F7DF89F7.180D7C6D428C8D32A628B7790546D86C85ACF9F0
14:09:41.611 T:1946157728  NOTICE: VideoPlayer: Opening: https://r5---sn-h5q7dnel.c.youtube.com/videoplayback?mv=u&mt=1527508586&ms=nxu%2Conr&cp=U0pRTFVOTl9NSkNQMV9NSFJKOlFrcktqY3NmWlA4&id=o-AB7Sa0ZUy76Aj44oKAZf_G9HJ1fg0zRT8qOuRBF8sDiI&mn=sn-h5q7dnel%2Csn-4g5e6nzl&mm=30%2C26&ip=37.132.142.141&pl=24&expire=1527530980&source=youtube&ei=hPELW_LDLp6IWPPThagM&requiressl=yes&itag=22&lmt=1527445257169960&sparams=cp%2Cdur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csc%2Csource%2Cexpire&ipbits=0&fvip=4&sc=yes&ratebypass=yes&dur=261.015&c=WEB&mime=video%2Fmp4&key=yt6&signature=34307FC471416728FE515DD8953D0BC6F7DF89F7.180D7C6D428C8D32A628B7790546D86C85ACF9F0
14:09:41.611 T:1946157728 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:09:41.844 T:1946157728   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://r5---sn-h5q7dnel.c.youtube.com/videoplayback?mv=u&mt=1527508586&ms=nxu%2Conr&cp=U0pRTFVOTl9NSkNQMV9NSFJKOlFrcktqY3NmWlA4&id=o-AB7Sa0ZUy76Aj44oKAZf_G9HJ1fg0zRT8qOuRBF8sDiI&mn=sn-h5q7dnel%2Csn-4g5e6nzl&mm=30%2C26&ip=37.132.142.141&pl=24&expire=1527530980&source=youtube&ei=hPELW_LDLp6IWPPThagM&requiressl=yes&itag=22&lmt=1527445257169960&sparams=cp%2Cdur%2Cei%2Cid%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csc%2Csource%2Cexpire&ipbits=0&fvip=4&sc=yes&ratebypass=yes&dur=261.015&c=WEB&mime=video%2Fmp4&key=yt6&signature=34307FC471416728FE515DD8953D0BC6F7DF89F7.180D7C6D428C8D32A628B7790546D86C85ACF9F0

**Comment by anxdpanic** [comment]
That video is working here, how are you getting to that video? (ie search, my channel, my subscriptions)
