### ISSUE TITLE
Sign-in not working with current nightly build of Kodi

### ISSUE THREAD

**Issue by mattreecebentley** [jdf76/plugin.video.youtube#360]
Does the dual-activation, then quits with a 500 Internal Error. Can still look at videos on youtube through plugin, but can't log into youtube account.

Kodi build:
27/5/2018 Winx64

**Comment by anxdpanic** [comment]
That is a server side issue, a couple others reported similar on the forum. https://forum.kodi.tv/showthread.php?tid=325740&pid=2738706#pid2738706 was also getting error 500.

**Comment by Blackclaws** [comment]
Related to other issue I posted #366 I now get a deleted profile also while signing in.

**Comment by mattreecebentley** [comment]
This was resolved via the method in the forum, however I feel this should probably be written into the instructions for the plugin as it's non-obvious.

**Comment by anxdpanic** [comment]
It should be a temporary server issue 👍
