### ISSUE TITLE
Video Thumbs instead of Channel Thumb 16:9

### ISSUE THREAD

**Issue by nevrion** [jdf76/plugin.video.youtube#364]
First of all sorry for my bad English.

Is it possible to use the video thumbnails instead of the channel thumbs when the widget is set to 16: 9?

**Comment by anxdpanic** [comment]
I can't reproduce this, 4:3 or 16:9 both appear to be video thumbnails, can you provide more information on how to reproduce what you are seeing?

**Comment by nevrion** [comment]
Was probably my mistake, it seems to be more a problem of the skin. I use Embuary. With Estuary, the problem does not exist.

**Comment by Twilight0** [comment]
Try cleaning the textures cache then repeat.

**Comment by nevrion** [comment]
He has adjusted the skin, now everything is wonderful :)
