### ISSUE TITLE
Logging out in current Kodi Leia nightly deletes profile

### ISSUE THREAD

**Issue by Blackclaws** [jdf76/plugin.video.youtube#366]
Pressing the sign out button in the current nightly build deletes the profile and puts Kodi into an unbootable state. Can be fixed by deleting the profile.xml alltogether. However other settings are cleared as well.

**Comment by anxdpanic** [comment]
This should be resolved by 088ead20871ceaff69ef0ea1875544071a0f33c3
Available in ~alpha7 
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev

Please re-open if still an issue for you  w/ alpha7
