### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by talondnb** [jdf76/plugin.video.youtube#371]
I started receiving a Backend Error in the last couple of days when trying to launch the addon. I've tested with both stable and alpha7, reset to defaults, with the same result.

Debug logs here (alpha7)

https://pastebin.com/EQ6Ht9cq

Hope this helps.

**Comment by anxdpanic** [comment]
It appears to be an issue with your channel on YouTube's end. I've updated the logging in [~alpha8](https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev) . If you can provide a new debug log with the updated version I may be able to see more.

You can also disable Settings - Folders - Liked Videos with the new version and you may be able to at least do a little bit more.

Also have you tried logging into your account on the web to see if anything is abnormal?

**Comment by talondnb** [comment]
Thanks for the prompt response to this issue. I have tried alpha8 and it has fixed my issue. I've also not done anything else to my setup and maintained the same configuration I had previously, simply removed the old plugin folder and added the new and rebooted.

Here is a current debug with alpha8.

https://pastebin.com/PGCXr2jw

I'm not sure if it gives more insight into the issue?

When I had the issue, I was resorting to the web to view youtube and didn't notice anything abnormal from there.

**Comment by anxdpanic** [comment]
Thanks 👍  The issue seems like it may have resolved itself for the others that reported it as well.
