### ISSUE TITLE
Playlists start at second item

### ISSUE THREAD

**Issue by mje-nz** [jdf76/plugin.video.youtube#382]
I'm adding Youtube playlist support to the [KodiPlay Safari extension](https://github.com/klattimer/KodiPlay). I'm using version 6.0.2 of this plugin.

When I use a URL like `plugin://plugin.video.youtube/play/?playlist_id=PLunIrIqYqs78M4K1UMnfytyivueZK-wnb` it always starts playing from the second video in the playlist. If I then press the previous button it will play the first video.

Giving the video ID of the first video (`plugin://plugin.video.youtube/play/?playlist_id=PLunIrIqYqs78M4K1UMnfytyivueZK-wnb&video_id=yU38oLPNpYk`) has the same behaviour.

**Comment by anxdpanic** [comment]
Can you provide a debug log, as well playlists require &play=1 to start playback.
https://kodi.wiki/view/Add-on:YouTube#Integration_with_STRM_files Will add some highlight to the play parameter to make that more noticeable.

**Comment by mje-nz** [comment]
Thanks for that tip. With &play=1 it starts playing from the first video. Without &play=1 it starts playing from the second video.

Logs for both attached. Without &play=1 this message is logged:
`19:45:59.862 T:1926384128   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?playlist_id=PLiEjuGSqZK0NWdRNJllWEfi3GOpcChDrX&order=default]`

[kodi-without-play.log](https://github.com/jdf76/plugin.video.youtube/files/2173470/kodi-without-play.log)
[kodi-with-play.log](https://github.com/jdf76/plugin.video.youtube/files/2173471/kodi-with-play.log)

**Comment by anxdpanic** [comment]
It looks like the expected behavior, without play=1 the add-on will only create the playlist and it's not intended to start playback automatically. You would need to make 2 separate json-rpc requests without play=1, one to create the playlist and one to play the first item.

**Comment by mje-nz** [comment]
That's not what happens. Without play=1 playback still starts automatically, it just skips the first item in the playlist.
