### ISSUE TITLE
 internal_failure: Backend Error

### ISSUE THREAD

**Issue by rochmad** [jdf76/plugin.video.youtube#384]
17:47:39.192 T:13436   DEBUG: CWebServer[8080]: request received for /jsonrpc?tm=1531133258160
17:47:39.245 T:13436   DEBUG: CWebServer[8080]: request received for /jsonrpc?tm=1531133258208
17:47:41.465 T:16456   DEBUG: ------ Window Init (Pointer.xml) ------
17:47:41.768 T:14528   ERROR: [plugin.video.youtube] Requesting access token: Code: |500| JSON: |{u'error_description': u'Backend Error', u'error': u'internal_failure'}|
17:47:41.809 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
17:47:41.809 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
17:47:41.812 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
17:47:41.817 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
17:47:41.817 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
17:47:41.820 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
17:47:41.824 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
17:47:41.824 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
could someone help me ...
i still cant login with kodi 18 and youtube plugin version 5.5.1
i already use my own api key...

17:47:41.826 T:14528   DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
17:47:41.829 T:14528   ERROR: [plugin.video.youtube] LoginException: [500] internal_failure: Backend Error
17:47:41.844 T:16456   DEBUG: ------ Window Init (DialogAddonSettings.xml) ------
17:47:41.847 T:16456   DEBUG: ------ Window Init (DialogNotification.xml) ------
17:47:43.308 T:16456   DEBUG: Keyboard: scancode: 0x38, sym: 0x0134, unicode: 0x0000, modifier: 0x100
17:47:43.308 T:16456   DEBUG: CInputManager::HandleKey: alt-long-leftalt (0x104f0d4) pressed, action is
17:47:43.311 T:16456   DEBUG: ------ Window Deinit (Pointer.xml) ------
17:47:44.192 T:13436   DEBUG: CWebServer[8080]: request received for /jsonrpc?tm=1531133263164
17:47:44.243 T:13436   DEBUG: CWebServer[8080]: request received for /jsonrpc?tm=1531133263218
17:47:45.312 T:15864   DEBUG: Thread JobWorker 15864 terminating (autodelete)
17:47:45.312 T:10336   DEBUG: Thread JobWorker 10336 terminating (autodelete)
17:47:45.313 T:14692   DEBUG: Thread JobWorker 14692 terminating (autodelete)
17:47:45.313 T:17188   DEBUG: Thread JobWorker 17188 terminating (autodelete)

**Comment by anxdpanic** [comment]
see #371

**Comment by rochmad** [comment]
hey andx

i was follow that instruction..but stil geting error


22:05:17.382 T:5136  NOTICE: [plugin.video.youtube] Running: YouTube (6.1.0~alpha11) on Krypton (Kodi-17.6) with Python 2.7.13
                                                Path: /sign/in/
                                                Params: {}
22:05:36.263 T:5136   ERROR: [plugin.video.youtube] Requesting access token: Code: |500| JSON: |{u'error': u'internal_failure'}|
22:05:36.499 T:5136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'dict' object has no attribute 'replace'
                                            Traceback (most recent call last):
                                              File "C:\Users\Archer\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "C:\Users\Archer\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\runner.py", line 43, in run
                                                __RUNNER__.run(provider, context)
                                              File "C:\Users\Archer\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_runner.py", line 25, in run
                                                if provider.handle_exception(context, ex):
                                              File "C:\Users\Archer\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 1460, in handle_exception
                                                context.get_ui().show_notification(message, title, time_milliseconds=message_timeout)
                                              File "C:\Users\Archer\AppData\Roaming\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\impl\xbmc\xbmc_context_ui.py", line 119, in show_notification
                                                _message = _message.replace(',', ' ')
                                            AttributeError: 'dict' object has no attribute 'replace'
                                            -->End of Python script error report<--
22:05:36.545 T:11292   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.youtube/sign/in/
22:05:36.548 T:11292   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/sign/in/) failed

**Comment by anxdpanic** [comment]
Another user reported resolving the issue.
https://forum.kodi.tv/showthread.php?tid=325740&pid=2750068#pid2750068
If you're unsure on how to create your own keys: https://forum.kodi.tv/showthread.php?tid=325740&pid=2681560#pid2681560
You may also try changing, Settings -> API -> Use preset API key set to a different number. These are different sets of pre-configured API keys, though they all have low limits for mass use, so creating your own keys would be suggested. (If you haven't already)

**Comment by rochmad** [comment]
well... i try this morning. and work,
but i dont know why...
i was use my key...
but with longer registration..
i give space time in betwen registration
