### ISSUE TITLE
Playing youtube videos somehow deleted profiles.xml

### ISSUE THREAD

**Issue by Blackclaws** [jdf76/plugin.video.youtube#388]
So this has been happening to me before and I thought it was fixed. However it recently happened again that a crash of the youtube plugin takes kodi itself down and leaves it unable to start unless manually repaired since profile.xml is deleted in the userdata folder... guisettings.xml also gets reset and needs to be restored.

This is all on the current git master of Kodi

EDIT: (Following seems to be irrelevant)
Interestingly enough it searches for the youtube plugin in the temp folder:

12:12:47.214 T:139919750059776   ERROR: GetDirectory - Error getting /home/kodi/.kodi/temp/plugin.video.youtube/

**Comment by anxdpanic** [comment]
That line is unrelated, can you provide a full debug log of it happening?

**Comment by anxdpanic** [comment]
Closing, Please re-open with a complete debug log if the issue persists
