### ISSUE TITLE
Seach in Channel for external Addons

### ISSUE THREAD

**Issue by nevrion** [jdf76/plugin.video.youtube#392]
First I want to apologize for my bad English.

I have to say, I have no programming experience.

I'm trying to search with an addon directly on a Youtube channel instead of globally.

I tried it like this:

plugin://plugin.video.youtube/kodion/search/input/?channel_id=UCCI6C8hD-hTZi2JEmS7zvQ?q=Windows

or also with:

plugin://plugin.video.youtube/kodion/search/input/?channel_id=UCCI6C8hD-hTZi2JEmS7zvQ/?q=Windows

Unfortunately, I have to enter the search term every time in Kodi directly. How can I pass the search term directly?

Thank you very much.

**Comment by anxdpanic** [comment]
iirc, the following should work
```plugin://plugin.video.youtube/kodion/search/query/?channel_id=UCCI6C8hD-hTZi2JEmS7zvQ&q=Windows```

**Comment by nevrion** [comment]
Thats works, nice thanks :)
