### ISSUE TITLE
Localize sign out confirmation dialog

### ISSUE THREAD

**Issue by roliverosc** [jdf76/plugin.video.youtube#402]
Hi @anxdpanic could you create a string in strings.po for the popup message of sign out. This popup message show the string "#30112" msgid "Sign Out" adding in message a question mark only.

**Comment by anxdpanic** [comment]
Just to make sure, you mean the sign out confirmation dialog?

**Comment by roliverosc** [comment]
Yes

**Comment by anxdpanic** [comment]
Will add an 'Are you sure?' with title of 'Sign Out' for next version, language contributors are already up to date with the beta for this round.

**Comment by roliverosc** [comment]
Ok, thank you!
