### ISSUE TITLE
Login failed due to 428 HTTP error

### ISSUE THREAD

**Issue by sertal70** [jdf76/plugin.video.youtube#41]
Hi all, 
I installed OpenElec 7.01 with Kodi 16.1 on my Raspberry PI 3, then added the youtube plugin 5.3.12.

I configured my API key, ID and secret, then I tried to execute the access procedure but without success: as soon as the first youtube access code is displayed on the screen, a "Login Failed" message is shown then the plugin settings window opens.

Because the "Login failed" message is a bit generic, I tweaked the **login_client.py** source file to have more specific messages: in that way I discovered that the error comes from the source line 178:

```pyton
if result.status_code != requests.codes.ok:
   raise LoginException('Login Failed')
```

I modified the message to print out the status code: its value was **428**, googling a bit I found that it is due to a missing `"If-Match"` directive in the Headers section of the request, so I modified the "headers" variable at line 143 to include such directive: 

```pyton
headers = {'Host': 'www.youtube.com',
   'Connection': 'keep-alive',
   'Origin': 'https://www.youtube.com',
   'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.28 S
   'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8',
   'Accept': '*/*',
   'DNT': '1',
   'Referer': 'https://www.youtube.com/tv',
   'Accept-Encoding': 'gzip, deflate',
   'Accept-Language': 'en-US,en;q=0.8,de;q=0.6',
   'If-Match': '*' }
```
Then I repeated the access procedure and everything went well.

I'm wondering why noone is signaling this...

Regards
Sergio

**Comment by anxdpanic** [comment]
Thank you, should be addressed now
