### ISSUE TITLE
No json object could be decoded

### ISSUE THREAD

**Issue by bodyguardroman** [jdf76/plugin.video.youtube#423]
[kodi.log](https://github.com/jdf76/plugin.video.youtube/files/2361526/kodi.log)
hi guys.,maybe this fix was solved,but i missed...
Btw.only error:NO JSON OBJECTS could be decoded.
Of course debug log.I have actual version of youtube addon
Dont work next addons.because same error.
Is it possible fix?because i tried different options from youtube manuals...

**Comment by anxdpanic** [comment]
If you take a look at the forum, you may find your answer. 
Will need a clean debug log for support, your log contains banned add-ons.  Re-open the issue with the new debug log.
