### ISSUE TITLE
 invalid relevance language on search raspberry pi 2

### ISSUE THREAD

**Issue by Wilmonster** [jdf76/plugin.video.youtube#433]

**Comment by anxdpanic** [comment]
Try addon Settings -> Advanced -> Enable set-up wizard and re-choose region and language. If it's still an issue, which language are you choosing?

**Comment by mchuv** [comment]
Hi, i have the same problem, i just installed kodi on raspberry pi 3 today, i'm using the last version of raspbian, and every time i try to use an option in the YouTube plug in, it shows a message with an error "invalid relevance language", my regional configuration is:

- Language : Spanish
- Country : Peru

I tryed to change my regional configuration to USA, but i still shows the same error.

**Comment by anxdpanic** [comment]
Try re-running the wizard again and choose Spanish (Spain) or Spanish (United States), YouTube provides Spanish (Latin America) but it seems to cause the invalid relevance language error.

**Comment by Intel11** [comment]
> Try re-running the wizard again and choose Spanish (Spain) or Spanish (United States), YouTube provides Spanish (Latin America) but it seems to cause the invalid relevance language error.

Hello, when you choose Spanish (Latin America) is when the error appears.

Is it possible to fix the error?

Thank you.

**Comment by anxdpanic** [comment]
No fix that I can see, I've removed Spanish (Latin America) es-419 for the next version. YouTube provides the language via their api but doesn't support it as a language parameter for api requests.
