### ISSUE TITLE
Quality maxes out at 360p 

### ISSUE THREAD

**Issue by pitsi** [jdf76/plugin.video.youtube#440]
Dear developers.

I just noticed that the addon can only give me up to 360p quality, e.g on [this](https://www.youtube.com/watch?v=dS5Ru41i22o) vid, this is what I get inside kodi

![screenshot000](https://user-images.githubusercontent.com/5880037/46095679-ca352a00-c1c5-11e8-857f-6923a266deba.png)

and this is what the log says
http://paste.debian.net/1044512/

Debian testing x64, kodi 17.6, youtube 6.1.4 from the main kodi repo, inputstream adaptive 2.0.19 (not used above)
As for the addon settings:
- ask for video quality = enabled (thus the dialog prompt above) 
- mpeg-dash =  disabled 
- not using a personal api key

and the rest set to defaults.

**Comment by pitsi** [comment]
Same thing happens on my rpi zero (kodi 17.6 on libreelec 8.2.5). The only difference from the pc is that I have set my own api keys there... 
And the same happens on my netbook installation (kodi 14.2, openelec 5.0.4 and youtube 5.4.9). It is set up the same way as the rpi zero.

**Comment by L2501** [comment]
you need to use DASH for high quality

```
youtube-dl -F "https://www.youtube.com/watch?v=dS5Ru41i22o"
[youtube] dS5Ru41i22o: Downloading webpage
[youtube] dS5Ru41i22o: Downloading video info webpage
[info] Available formats for dS5Ru41i22o:
format code  extension  resolution note
249          webm       audio only DASH audio   72k , opus @ 50k, 1.16MiB
250          webm       audio only DASH audio   92k , opus @ 70k, 1.52MiB
140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k, 2.78MiB
171          webm       audio only DASH audio  132k , vorbis@128k, 2.64MiB
251          webm       audio only DASH audio  163k , opus @160k, 2.95MiB
278          webm       256x144    144p   97k , webm container, vp9, 30fps, video only, 1.99MiB
160          mp4        256x144    144p  111k , avc1.4d400c, 30fps, video only, 1.81MiB
242          webm       426x240    240p  223k , vp9, 30fps, video only, 3.84MiB
133          mp4        426x240    240p  258k , avc1.4d4015, 30fps, video only, 3.84MiB
243          webm       640x360    360p  408k , vp9, 30fps, video only, 7.49MiB
134          mp4        640x360    360p  485k , avc1.4d401e, 30fps, video only, 7.77MiB
244          webm       854x480    480p  750k , vp9, 30fps, video only, 13.09MiB
135          mp4        854x480    480p 1013k , avc1.4d401f, 30fps, video only, 15.34MiB
247          webm       1280x720   720p 1426k , vp9, 30fps, video only, 20.01MiB
136          mp4        1280x720   720p 1595k , avc1.4d401f, 30fps, video only, 22.71MiB
248          webm       1920x1080  1080p 2497k , vp9, 30fps, video only, 33.29MiB
137          mp4        1920x1080  1080p 2659k , avc1.640028, 30fps, video only, 32.98MiB
17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k, 1.76MiB
36           3gp        320x180    small , mp4v.20.3, mp4a.40.2, 5.14MiB
18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k, 12.16MiB (best)
```

**Comment by pitsi** [comment]
I see, the "single file" quality does top at 360p. 
Could it be a youtube issue? Let me check some other videos...

**Comment by pitsi** [comment]
Reopening the issue because I found something odd...

I asked a friend to check the addon with the above video and he got 720p! 
The "catch" is that he opens kodi rarely, so he was on v6.0.1 when he first checked. He has mpeg-dash disabled and not using a personal api key. Here is a screenshot proving that it did play on 720p

![screenshot000](https://user-images.githubusercontent.com/5880037/46218025-4bb6c480-c34c-11e8-87db-ccdd6c871245.png)

And when kodi upgraded youtube to v6.1.4, he tried it again and it dropped to 360p (screenshot for the same reason as above)

![screenshot002](https://user-images.githubusercontent.com/5880037/46218107-815bad80-c34c-11e8-889d-6c157ffa6317.png)

So what happened? 

I tried downgrading it as well. I downloaded 6.0.2 from the releases section here, deleted my ~/.kodi/userdata/addon_data/plugin.video.youtube and started fresh, with only the forementioned settings changed. However, it maxed at 360p again, so I upgraded it back to v6.1.4.

**Comment by anxdpanic** [comment]
This seems to be on YouTube's end. That video shows only 360p even with 6.0.1

caYdSWljo1g also has a max of 360p without dash

**Comment by pitsi** [comment]
Obviously, the problem IS on youtube's end, and I am 99.9% sure about that. But how did it work on my friend's kodi at 720p? 
I wouldn't reopen the issue if it was not for him. Now his kodi is on is on 6.1.4 and maxes out at 360p as well.

And what about "caYdSWljo1g"? It is the video with the title "RELIVE ULTRA MIAMI 2013 (Official Aftermovie)" and it also maxes out at 360p. In fact, ALL the **music** videos I have checked since max out at 360p. Stupid videos with cats, dogs and other bs max out at 720p as usual.

**Comment by AdamBark** [comment]
I'm getting this problem on certain videos too although all videos seem to not get DASH video streams but I do see DASH audio streams. If there is a standard 720p video stream I get that but if that doesn't exist 360p is the highest.

**Comment by AdamBark** [comment]
I figured out what my problem was. If you are on ubuntu and using the kodi ppa make sure you have kodi-inputstream-adaptive and kodi-inputstream-rtmp installed, they should then show up in addons (you might need to restart kodi for them to appear) now make sure they are enabled. Enjoy 1080p!

**Comment by pitsi** [comment]
I know about inputstream adaptive and what it can do. That is why I mention, in all my posts, that ALL the forementioned tests were done without its use (option "use mpeg-dash" set to disabled).
To be honest, I wouldn't even care for inputstream adaptive if it was not for youtube... forcing (= polite version of what I really wanted to say) all songs clips to max out at 360p.

**Comment by pitsi** [comment]
1+ month after my initial issue report and today I found this on reddit.  
https://old.reddit.com/r/Addons4Kodi/comments/9tu71n/youtube_videos_play_in_sd_even_though_hd_is/

Regardless of what some may say, the use of personal api keys makes no difference.

**Comment by nouman8** [comment]
im also facing this,all songs are now capped at 360p while vlog videos play at 720p as usual.

**Comment by nouman8** [comment]
could it be due to youtube switching to the new av1 codec ?

**Comment by pitsi** [comment]
Can you prove that any stream on youtube is on av1?

**Comment by pitsi** [comment]
Can you share a link to a video playing in av1 so we can parse it in youtube-dl and check what extra "formats" it has to offer? 
Other than that, I am sure that the streams encoded in av1 will be video only streams, so the addon will use inputstream adaptive (aka mpeg-dash as you said) to make them play, so it is not a solution to this issue.

**Comment by anxdpanic** [comment]
The av1 streams are video only, and were recently added to the add-on so they can at least be identified but they aren't usable by the add-on atm. https://github.com/jdf76/plugin.video.youtube/commit/93c0068c9eed6b08424acd701355d1c1500d5505

**Comment by pitsi** [comment]
Thank you both. I am pretty sure my hw will be incapable of av1, as it is for h265.

On the other hand, it can not be considered as a solution because it also demands the usage of inputstream adaptive. Let me say it differently. Any solution that needs inputstream adaptive to work is not a solution but a workaround to this issue. I can explain the why if needed...

**Comment by anxdpanic** [comment]
I don't see a way to have YouTube return >360p audio+video combined streams for these cases and the limitation is also seen with other tools. There is also no way for a python add-on in Kodi to mux separate audio and video streams. The only way to achieve >360p for these cases is mpeg-dash, and mpeg-dash in Kodi requires InputStream Adaptive.  InputStream Adaptive is also required to watch YouTube Purchases, because again YouTube uses mpeg-dash. So unless YouTube makes those qualities in that format available again (unlikely), I don't see another solution.

**Comment by pitsi** [comment]
I know all that. However, the 2 things mentioned above 

- the "unexpected" playback of a clip at 720p at my friend's v6.0.1
- the fact that youtube has a lot of 720p streams in combined audio+video, which they are not song clips but vlog videos and other bs with cats and dogs (proof > http://paste.debian.net/1051798/)

still gives me some hope for that "other" solution

**Comment by anxdpanic** [comment]
It's looking like this is how things are now and is being applied to all new music video content+ as well. I don't see any chance of this being resolved. Any "unexpected" behavior early on was an exception and not the rule, and I would suspect to be related to slow propagation of the change.

**Comment by dagwieers** [comment]
There was a bug in **inputstream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259

**Comment by anxdpanic** [comment]
This issue is unrelated, YouTube has limited some videos to 360p (non mpeg-dash content). 
But thank you for the heads up 👍  
iirc some 1080p YouTube videos are 1920x1088, so there may still be some cases where 1080 will result in 720 for YouTube videos. I will have to check on that next chance I get after adjusting for your fix.

**Comment by ihenry** [comment]
Just to note, after enabling dash I had to reboot to get 1080p on YouTube
