### ISSUE TITLE
Disable rate-after-watching for playlists

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#458]
The rate-after-watching feature essentially disables continuous playback in playlists. Please add a switch or disable it for playlists.

Thank you!

**Comment by anxdpanic** [comment]
I added this in #516, it defaults to not rating videos in playlists

**Comment by anxdpanic** [comment]
alpha release updated, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev 
alpha4+ will include this, thank you for the request 👍
