### ISSUE TITLE
Kodi 17.6/18 Nightly "Video Unavailable"

### ISSUE THREAD

**Issue by XxAcielxX** [jdf76/plugin.video.youtube#464]
Hello,

I'm trying to play some videos from YouTube on my RPi3 using two LibreELEC versions and the video simply won't play. It starts to load the video then suddenly says "Video Unavailable".

Playing Methods:
1. Directly from YouTube Search
2.  From Favourites (Playlist)
3. Share from Android Phone through Yatse.

I have enabled MPEG-DASH, InputStream_Adaptive & RTMP as well.

Example Videos:
https://youtu.be/A31x2FL-C1Y
https://youtu.be/JDqL8j2u_T4

**Comment by XxAcielxX** [comment]
Yes, I can confirm this problem with 6.2.1-dev.beta1 is fixed. Tested the above links and several others as well.

Can you see check if the Cache Size (MB) is working or not. I have increased it to 25, but it's loading same as value set at default (10)

Thanks a lot for fixing the issue in the OP.

**Comment by anxdpanic** [comment]
Good to hear 👍 Thanks for confirming.

I just double checked on the cache, it is working here. What you may be seeing, is when set to 25MB you'll see a data cache of 12.5 max. The cache size is split between function cache and data cache and each will have a max size equal to half the cache size setting.
If you're seeing something different, open a new issue with more details. 👍
