### ISSUE TITLE
Don't refresh view after stopping unfinished video

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#468]
As the title says: I'd like to see an option to set a percentage watched of a video until the automatic refresh function kicks in. 

Thank you

**Comment by anxdpanic** [comment]
'Settings - General - Refresh' after watching only happens after 'Settings - General - Play count minimum percent' any other refresh you may seeing is likely caused by Kodi itself,

**Comment by pannal** [comment]
OK, then this might be a side effect of #458
