### ISSUE TITLE
RuntimeError when playing videos in different addon

### ISSUE THREAD

**Issue by Varstahl** [jdf76/plugin.video.youtube#473]
I was working on an addon while having 6.2.2 installed and I started noticing an issue with your addon:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.RuntimeError'>
  Error Contents: XBMC is not playing any media file
  Traceback (most recent call last):
    File "%AppData%\Kodi\addons\plugin.video.youtube\resources\lib\youtube_plugin\kodion\utils\player.py", line 75, in onPlayBackStarted
      self.current_video_total_time = self.getTotalTime()
  RuntimeError: XBMC is not playing any media file
  -->End of Python script error report<--
```

When a video is started and stopped immediately after (regardless of the fact I wasn't even using your addon), your hook causes crashes to be logged. There are no sanity checks at the beginning of the `onPlayBackStarted` function, and there are still errors possible on race conditions, so you might want to wrap and catch that runtime error to avoid similar propagations.

**Comment by anxdpanic** [comment]
I wasn't able to reproduce it but it should be protected against in the latest dev version. https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.3-dev if you'd like to confirm.

**Comment by Varstahl** [comment]
It's going to take me some time but I'll check when I'm able to and report back.
