### ISSUE TITLE
Use plugin to list a collection of YouTube channels

### ISSUE THREAD

**Issue by goggle** [jdf76/plugin.video.youtube#474]
I want to use this plugin in one of my own addons to display a list of youtube channels. I'm currently building `ListItem`s and add the url `'plugin://plugin.video.youtube/channel/%s/' % channel_id` to redirect to `plugin.video.youtube`.

I'm wondering if it is possible to build this directory structure directly with `plugin.video.youtube`? The benefit would be, that I would have these nice thumbnails for the channels. Is there something like
```
'plugin://plugin.video.youtube/channels/%s,%s,%s' % (cid1, cid2, cid3)
```
available? If not, would it be possible to add this to `plugin.video.youtube`?

**Comment by anxdpanic** [comment]
You can add this add-on as a required module;
```    
<requires>
    <import addon="xbmc.python" version="2.20.0"/>
    <import addon="plugin.video.youtube" version="6.2.0"/>
</requires>
```

then ```import youtube_requests``` and use ```youtube_requests.get_channels([channel_id1, channel_id2])``` to get all the information (title, description, thumbnails, etc) for the channels you specify

see https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_requests.py#L169

**Comment by goggle** [comment]
I just tried it out and it works fine, thanks.

There is one issue thought: `youtube_requests.get_channels` does not respect the ordering of the input. The output information that I get, is in a completely different order from the input. Maybe we could add another additional optional argument `keep_order` to that function.

Is there a list of function that are safe to use from other Kodi plugins, i.e. functions which are stable and not expected to change in new releases of `plugin.video.youtube`?

**Comment by anxdpanic** [comment]
The list returns in the same order as the api, here is a quick mock up of how to do this in your add-on.

```
channel_ids = ['UCzQUP1qoWDoEbmsQxvdjxgQ', 'UCLA_DiR1FfKNvjuUpBHmylQ', 'UCaBf1a-dpIsw8OxqH4ki2Kg', 'UC3XTzVzaHQEd30rQbuvCtTQ']
sorted_channels = []

channel_response = youtube_requests.get_channels(channel_ids)

if channel_response and 'error' not in channel_response[0]:
    for channel_id in channel_ids:
        try:
            sorted_channels.append(next(channel for channel in channel_response if channel_id == channel.get('id')))
        except StopIteration:
            pass

    """
    returned_ids = [channel.get('id') for channel in channel_response]
    sorted_ids = [channel.get('id') for channel in sorted_channels]

    print 'original list order: ' + str(channel_ids)
    print 'returned list order: ' + str(returned_ids)
    print 'sorted list order:   ' + str(sorted_ids)
    
    #  original list order: ['UCzQUP1qoWDoEbmsQxvdjxgQ', 'UCLA_DiR1FfKNvjuUpBHmylQ', 'UCaBf1a-dpIsw8OxqH4ki2Kg', 'UC3XTzVzaHQEd30rQbuvCtTQ']
    #  returned list order: [u'UCaBf1a-dpIsw8OxqH4ki2Kg', u'UCzQUP1qoWDoEbmsQxvdjxgQ', u'UC3XTzVzaHQEd30rQbuvCtTQ', u'UCLA_DiR1FfKNvjuUpBHmylQ']
    #  sorted list order:   [u'UCzQUP1qoWDoEbmsQxvdjxgQ', u'UCLA_DiR1FfKNvjuUpBHmylQ', u'UCaBf1a-dpIsw8OxqH4ki2Kg', u'UC3XTzVzaHQEd30rQbuvCtTQ']
    """
```

**Comment by goggle** [comment]
@anxdpanic Thanks, this works well.

Another question: Is there an easy way to sort the channels by its size (total number of subscriptions) or by it's activity (most recent video upload)?

And what is the best way to list videos from different channels? Is it also possible to sort them by the most recent uploads and the most viewed videos?

**Comment by goggle** [comment]
So I wanted to sort the channels by **number of subscription**. But I've realized that `get_channels` does not include the _statistics_ section described in https://developers.google.com/youtube/v3/docs/channels#resource. Is there any reason for that?

Or is there another way to sort the channels by number of subscriptions?

**Comment by goggle** [comment]
Ok, so I managed to list videos from different channels by using `youtube_requests.get_playlist_items`. Unfortunately, there is no _duration_ information available from that request. How do I get the durations of these videos?
Or is there a solution where `plugin.video.youtube` can list these videos for me by calling a function where I just need to submit the _video ids_?

**Comment by anxdpanic** [comment]
Hope you have it all working to your liking. I'm going to close this but feel free to comment here still if you need assistance or open issue if required.

**Comment by goggle** [comment]
@anxdpanic Thanks for yout help. I did not try it out yet, but I will definitely give it another try soon.
