### ISSUE TITLE
Video is not available in your country on raspberry Pi/xbian

### ISSUE THREAD

**Issue by b3er** [jdf76/plugin.video.youtube#486]
The plugin displays this error while playing region restricted videos on raspberry pi
Region is setup correctly, api keys also
The same video with the same plugin version is working correctly in the same network when it is installed on win10, but fails on raspberry
YouTube (6.2.3~beta2) on Krypton (Kodi-17.6) with Python 2.7.13, XBian 20180716-0 - Bleeding Edge, Linux 4.14.66+ #1 SMP PREEMPT Thu Aug 23 12:58:31 CEST 2018 armv7l GNU/Linux
Log:
`7:12:46.276 493.143036 T:1520689920  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.3~beta2) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'YmY1tPya6zY'}
17:12:46.304 493.170349 T:1520689920   DEBUG: [plugin.video.youtube] JSONStore Load |/home/xbian/.kodi/userdata/addon_data/plugin.video.youtube/access_manager.json|
17:12:46.306 493.172882 T:1520689920   DEBUG: [plugin.video.youtube] Selecting YouTube config "All"
17:12:46.308 493.174347 T:1520689920   DEBUG: [plugin.video.youtube] Access token count: |2| Refresh token count: |2|
17:12:46.313 493.179443 T:1520689920   DEBUG: [plugin.video.youtube] User is logged in
17:12:46.321 493.187256 T:1520689920   DEBUG: [plugin.video.youtube] Found cached data for videos |YmY1tPya6zY|
17:12:46.322 493.188354 T:1520689920   DEBUG: [plugin.video.youtube] Is embeddable: True
17:12:46.929 493.795959 T:1520689920   DEBUG: [plugin.video.youtube] Cipher: js player: |https://www.youtube.com/yts/jsbin/player-vfl718orE/ru_RU/base.js|
17:12:48.395 495.261536 T:1520689920   DEBUG: [plugin.video.youtube] Is embeddable: False
17:12:50.704 497.570709 T:1520689920   DEBUG: [plugin.video.youtube] Shutdown of Kodion after |4.5063| seconds
17:12:50.705 497.571167 T:1520689920    INFO: CPythonInvoker(25, /home/xbian/.kodi/addons/plugin.video.youtube/resources/lib/default.py): script successfully run
17:12:50.708 497.574890 T:1921484928   DEBUG: ------ Window Init (DialogNotification.xml) ------
17:12:50.709 497.575256 T:1921484928   DEBUG: Window DialogNotification.xml was already loaded
17:12:50.709 497.575409 T:1921484928   DEBUG: Alloc resources: 0.00ms
17:12:50.882 497.748901 T:1520689920    INFO: Python script stopped
17:12:50.883 497.749390 T:1520689920   DEBUG: Thread LanguageInvoker 1520689920 terminating
17:12:50.900 497.766296 T:1498936064   DEBUG: Thread scriptobs 1498936064 terminating
17:12:50.907 497.773285 T:1921484928   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=YmY1tPya6zY]
17:12:50.907 497.773499 T:1921484928   DEBUG: Playlist Player: no more playable items... aborting playback
17:12:50.908 497.774200 T:1498936064   DEBUG: Thread BackgroundLoader start, auto delete: false`

**Comment by anxdpanic** [comment]
Can you provide a complete log reproducing with debug logging enabled for both systems

**Comment by anxdpanic** [comment]
Closing, please re-open with a complete debug log if the issue persists.
