### ISSUE TITLE
Add support to show 16:9 (widescreen) thumbnails for videos (Possibly adding a setting for 16:9 or 4:3)

### ISSUE THREAD

**Issue by jonisb** [jdf76/plugin.video.youtube#49]
I would like the video thumbnails to be widescreen as most of the videos are widescreen (at least for me), right now the plugin uses the "high" thumbnail image and that is always 4:3.

Looks like there are two 16:9 thumbnail options "medium" and "maxres" based on [Youtubes API](https://developers.google.com/youtube/v3/docs/videos#snippet.thumbnails.%28key%29)

"maxres" is potentially quite big and not always available so might not be the ideal image, "medium" has a lower resolution than "high" but seems OK on my 40" TV.

Ideally 4:3 videos would have a 4:3 thumbnail and 16:9 videos a 16:9 thumbnail but knowing what format a video uses don't seem to be available from Youtubes API, v2 of the API did seem to have support to detect some widescreen videos.

I made a post in the Kodi forum with some more [info](http://forum.kodi.tv/showthread.php?tid=267160&pid=2564156#pid2564156).

jonib

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/releases/tag/5.4.0 alpha3 adds choice in thumbnail size

**Comment by jonisb** [comment]
Thanks for adding the option, works great (tested on Kodi 16,1)

But I think adding the aspect ratio to the option text would be helpful, why would a user choose medium quality (unless their internet sucks) even though they might prefer to get widescreen thumbnails instead and sacrifice quality.

**Comment by anxdpanic** [comment]
Done
