### ISSUE TITLE
Auto-Remove from 'Watch Later' not working

### ISSUE THREAD

**Issue by tadly** [jdf76/plugin.video.youtube#493]
I'm **not** using a custom Watch Later playlist and the *Retrieve Watch Later playlist id* feature also fails yet **it does work**.
I do see the videos I've added, I can add to it (through the add-on) and I can manually remove from it.

The Auto-Remove feature however does not work.

I'm not sure what other setting might influence this so let me know what you need.

**Comment by anxdpanic** [comment]
What happens when retrieving the watch later playlist id?

The watch later id is stored in the access_manager.json 
https://www.youtube.com/playlist?list=PLAYLISTID can compare to https://www.youtube.com/playlist?list=WL to ensure it's the correct playlist

This will also only happen if the 'Play count minimum percent' setting is met. 

Should be able look deeper into this weekend

**Comment by tadly** [comment]
Shouldn't manually adding/removing stuff not work as well in this case?
Because that certainly does 🤔

**Comment by anxdpanic** [comment]
Add was always working, remove working is a complete surprise to me. I will double check it all hopefully over the weekend

**Comment by tadly** [comment]
Just realized that it's actually: `"watch_later": " WL"`.
There's a **needed** space in front of `WL`.

I also tried getting the wl id myself from youtube.com/tv as you where referencing that earlier.
Not sure if it's supposed to be that short string within the url but that didn't work for me (I always restarted kodi to ensure I'm not hitting a cache).

Anyways. Thanks for looking into it and if there's any way for me to help out, lemme know :)

**Comment by anxdpanic** [comment]
Okay, so I doubled checked everything and if anything I am more confused. The option to remove from ```' WL'``` isn't available manually so I'm not sure how you're achieving that. I did try to force both cases and it doesn't work in either case.
I did make a minor PR for ensuring```' WL'``` is used, nothing that should affect this. 

If you are interested in trying yourself, https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/provider.py#L716 is the auto remove @ post play
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/utils.py#L341 is the```Remove``` context menu to delete items from playlists
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/client/youtube.py#L967 This is the number of pages ```Retrieve Watch Later playlist id``` checks for the id.

**Comment by tadly** [comment]
Ahahahahaha! I'm **so really** sorry for wasting your time.
I kinda figured something out which explains everything.

So, I have this addon I wrote (namely shortcuts) which allows me to save any directory to an easily accessible data-store (all keyboard-shortcut driven).
I obviously saved the Watch Later playlist as well and guess what...
`plugin://plugin.video.youtube/channel/mine/playlist/<proper playlist id>/`

That said, it doesn't seem like google is exposing the id anymore (even on youtube.com/tv).
I least a `ctrl+f` within the devtools for my ID doesn't come up with anything :/

**Comment by tadly** [comment]
And after updating the ID in the `access_manager` + restarting kodi, autoremove also works.

Again, I'm really sorry for wasting your time on this.
The only reason I _remembered_ was because you said the remove button shouldn't show at all so I double checked and lo and behold... yeah

**Comment by anxdpanic** [comment]
hah! no worries there 👍 
I ran the retrieve id during my testing. and it re-found my playlist on first try. The add-on makes the request as English and finds the 'watch later' title and the ```browseId``` is the playlist id. Just tested on youtube.com/tv, you need to scroll until Watch Later is on the screen then it is in the json response for the https://www.youtube.com/youtubei/v1/browse request for that page.

**Comment by anxdpanic** [comment]
Good to hear you got it all figured out though, along with the working id. :D

**Comment by tadly** [comment]
Scrolled through the whole page and `Watch Later` doesn't even show up at all.
This would explain why retrieving the id doesn't work.

Good to know how you guys handle this though..
Gonna play around for a little long but it seems like this ID is something I'm gonna treasure real good from now on.
Good thing I make daily backups :)

**Comment by anxdpanic** [comment]
That definitely explains it, likely a case where you'd have to add 20+ videos to get the Watch Later playlist on to your Trending list.

Definitely something I wish could be handled with a better solution, but so far I haven't found the id exposed anywhere else.

**Comment by tadly** [comment]
The hint for 20+ ids is good though.

I will actually test that and once I got a ruff estimate of "number of videos required", I'll let you know.
Would be good info to put into the Dialog that says "faild! add more videos" IMO

**Comment by tadly** [comment]
Sounds good to me.
Once I have more infos I'll add them to the new issue :) (kinda short on time currently)

**Comment by tadly** [comment]
So uhm...
I'm kind of at the point where it doesn't work anymore even though I do have a proper playlist-id.
I know there hasn't been an update to the add-on so I'm curious...

Does it matter how the video was started?
Should e.g. sharing from the phone or using a chrome extension still work?
In other words, will every video be checked against the watch-later playlist?

But even so, I did start some from within kodi which also didn't work.

**Comment by anxdpanic** [comment]
I just let a batch of videos play out, and all were removed correctly. Not sure what would be happening in your case.

**Comment by anxdpanic** [comment]
One change has been made that might be relevant, https://github.com/jdf76/plugin.video.youtube/commit/c19b1bf832b7fcce7da6cb65925e277a3c454bfe

I will update the repo versions with that change.

**Comment by tadly** [comment]
How dare you not have the testing repo on the latest and greatest :D (that's why I use it!!!!)
Did your test include this change?

p.s. thanks a lot :)

**Comment by anxdpanic** [comment]
hah :D it did include that change and a few other minors. Repositories are all updated with alpha2 and the few fixes 👍

**Comment by tadly** [comment]
Ugh, barley have time to breath lately.
Notebook seemed to be working but my HTPC was still struggling with this.
Will reinstall the add-on to make sure I got the right sources...

**Comment by tadly** [comment]
So it's still very much a hit or miss.
One video (I think I pressed skip at the end. I was way past my 80% threshold) did **not** get removed while the next (and last) one in the **queue** did.

Reason I highlighted queue is because maybe that got something to do with it?

Having only had a quick look at the code, is there a reason for the whole playback monitoring to be so convoluted? (no offense)
Subclassing [xbmc.Player](http://romanvm.github.io/Kodistubs/_autosummary/xbmc.html?highlight=monitor#xbmc.Player) would IMO make much more sense and should (if done right) be much more reliable then running your own loop.

I don't even understand why [the first loop](https://github.com/jdf76/plugin.video.youtube/blob/59f2d67ca5b2f44d4b67ed3fcd73b3cb68e870ee/resources/lib/youtube_plugin/kodion/utils/player.py#L48) exists.
How I understand it, it waits for playback to start **up to** 1.38^ hours. Seems kinda weird/random.

In regards to `xbmc.Player`. Things changed with Leia so there's stuff to be weary about when keeping backwards comparability.

Addon version: Unofficial 6.3.2~alpha4

**Comment by anxdpanic** [comment]
The change from the Player class was to resolve https://github.com/jdf76/plugin.video.youtube/issues/498

That first loop waits 200ms @ 25x, no where near hours, and is waiting for player to become active (because of things like Always ask for quality happening before video start)

The current iteration is definitely more consistent then the original Player() method, may be worth a revisit for the next version if it continues to be an issue.

When you have a chance, can you try to catch a debug log snippet of the failing video? Should be able to see the report information being sent for history to see at which point it fails.

**Comment by tadly** [comment]
Where am I going wrong?
```
0.2 * 1000 * (5 / 0.2) = 5000 sec.
5000 / 60 / 60 = 1,38 hours
```
But if there's a good reason than I won't complain (at least as long as I don't have the time to PR something better (: )

Will certainly try to grab a log (hopefully this evening)

**Comment by anxdpanic** [comment]
I forced the loop to go it's full length just to triple check;
```
08:12:29.312 T:88560   DEBUG: 0.0
08:12:34.331 T:88560   DEBUG: 5.0
```

**Comment by tadly** [comment]
[that's where I went wrong](http://romanvm.github.io/Kodistubs/_autosummary/xbmc.html#xbmc.sleep)
sleep is in milliseconds, not seconds :)
I feel like I shouldn't be working/thinking today

**Comment by anxdpanic** [comment]
hah, I know those days all too well. 
Never hurts to double check things though(especially while loops) :)

**Comment by tadly** [comment]
I did not forget about grabbing you a log btw but because my ISP decided to break routing to google or something I wasn't able to use youtube at all and than other stuff got in the way.

Anyways. Though I'd quickly try and reproduce it on my notebook aaaaaaand I can't.
Guess I'll play it save, remove the whole userdata folder for youtube and try again.

But every video I play on my HTPC is not being removed (it's not me going mad, it actually doesn't work).
Will report back after having reset the entire add-on.

**Comment by cas--** [comment]
I am not sure what has changed with this plugin but since I installed a fresh Kodi 18 last month the watch later definitely is not working correctly. 

I can add items to Watch Later using context menus in other folders and the Watch Later folder is populated but there is no context menu option in Watch Later to remove an item nor are items removed after watching. 

I have tried with two different PCs with the same result and it was working perfectly with Kodi 17 and latest Youtube addon version in December.

**Comment by anxdpanic** [comment]
@tadly Sounds good

@cas-- To be able to remove items from your Watch Later you must first successfully run Settings - Folders - Retrieve Watch Later playlist id

**Comment by cas--** [comment]
Afraid that has not worked at all for me since updating, it always fails

**Comment by anxdpanic** [comment]
There is no other way to achieve this currently, will have to retry going through the steps until the playlist id can be found. I wish there was another way as well. 
Once it is found its saved to the json in the addon_data folder so it can be backed up.

**Comment by cas--** [comment]
> Once it is found its saved to the json in the addon_data folder so it can be backed up.

Okay thanks, I was thinking you now had found a foolproof way of getting it :)

I shall see if I have a backup kodi profile to find the id or use the alternative methods from previous WL issue.

**Comment by tadly** [comment]
So... Reinstalled the addon (agian) and nuked everything apart from the settings.xml because I didn't feel like reconfiguring everything (takes way to long with all my changes :D)

After that it work.... until it didn't 🙄 

Couldn't grab a proper debug-log yet but the progress-reporting (I mean the debug lines) was missing for videos that did not end up getting removed.
In other words, `playback_monitor` wasn't running at all.
Today I really should be able to grab a log 🤞

**Comment by anxdpanic** [comment]
If you're not seeing the monitor running, can you try upping https://github.com/jdf76/plugin.video.youtube/blob/59f2d67ca5b2f44d4b67ed3fcd73b3cb68e870ee/resources/lib/youtube_plugin/kodion/utils/player.py#L52 to something like 30 just to see if it's not waiting quite long enough.

**Comment by tadly** [comment]
Oh... Oh! Now everything makes sense!!!
Yeah I do see videos often taking longer to start (kodi buffers for quite some time).
Will test for sure. Having 10 sec. instead of 5 would make sense IMO.

Brings me back to subclassing `xbmc.Player` though :P

**Comment by tadly** [comment]
Nope was not the issue.. Or not the only one at least...
*BUT* [I got you a log](https://pastebin.com/933vNa97) (finally)

What I did is:
1. Play a youtube video
2. While the first one is still playing, start another youtube video

The first one was properly tracking, the second video will not track.

**Comment by anxdpanic** [comment]
Thanks, can see what is happening, will see what I can do.

Your log makes me wish I knew C++ to throw setting spam behind component logging.
So much of this:
```
DEBUG: CAddonSettings[plugin.video.youtube]: loading setting definitions
DEBUG: CAddonSettings[plugin.video.youtube]: trying to load setting definitions from old format...
DEBUG: CAddonSettings[plugin.video.youtube]: loading setting values
DEBUG: CSettingsManager: requested setting (kodion.access_token) was not found.
DEBUG: CAddonSettings[plugin.video.youtube]: failed to find definition for setting kodion.access_token. Creating a setting on-the-fly...
```

**Comment by tadly** [comment]
Would [this](https://pastebin.com/H4qkz3CJ) make it easier for you? :)

**Comment by anxdpanic** [comment]
Very much so, thank you :)

**Comment by tadly** [comment]
I can now confirm for sure that it's an issue with having one video **already** playing while starting a new one.

I listen to youtube music live-streams all the time and just select a new video to watch resulting in it not getting tracked.

Just wanted to to make sure you understood that correctly  :)

**Comment by anxdpanic** [comment]
Thanks, that should make it easy enough to reproduce. Will likely be a couple days before I get a chance to look at it. Got a new PC yesterday, so need to get everything back in order first :)

**Comment by anxdpanic** [comment]
The latest alpha has a bandaid that still isn't 100% but is much better than it was. Quick tests were 1 fail per 5 videos vs all failing (starting a video with a video playing).

Still intend to revisit this before next stable.

**Comment by tadly** [comment]
I'm just glad you could reproduce it :)

I assume the `playback_monitor` is also used for reporting the progress to youtube right?
For that reason you need an active component and can't rely on the `xbmc.Player` reporting.

I'll hopefully mock up something today or tomorrow on how I'd go about doing it.
For a proper implementation I lack time sadly.
I feel bad for only reporting issues and not actually helping on resolving stuff so a mock is the least I can do :)

**Comment by anxdpanic** [comment]
Been a little slow on this, had some Twitch updates to take care of, and taking some time to enjoy the new PC :)
You are correct the `playback_monitor` is responsible for reporting as well. I have made another attempt within the current structure and was unsuccessful. Next chance I get I'm going to try going back to Player callbacks with some locks implemented to try to force the new video to hold until previous has completed reporting.

**Comment by anxdpanic** [comment]
@tadly 
Can you please give alpha5 a good test when you have a moment. Monitoring is now done in a thread spawned from player callback. Seems to have resolved the issue in my tests.

**Comment by tadly** [comment]
aaaaah dammit!
I knew I forgot something!!! _feels really really ashamed_
Will be done starting this evening! (youtube is basically all I watch 😅)

I actually did start a Monitor based mock, ran into some issues, had enough for the day aaaaaand...
... well, here we are 🙄 

Thanks for working on this :)

**Comment by anxdpanic** [comment]
No worries at all, I got side tracked myself :smile: and had a couple failed attempts before reaching this solution. Thanks!

**Comment by tadly** [comment]
Hm... so:
* [x] Playing a youtube video while nothing else was playing works.
* [x] Playing a youtube video **while** another **youtube** video was playing works.
* [x] Playing a youtube video **while** another **video** was playing works. (only tested local video)
* [ ] Playing a youtube video **while music** was playing doesn't work. (tested both a stream and local)

I think that should covers all scenarios?

**Comment by anxdpanic** [comment]
I think that should cover it all. 
I just pushed ~beta1 to the repositories, which should cover all cases now

**Comment by tadly** [comment]
Looking good so far :+1:

I'm sure I'll break it eventually but for now :tada: :)

**Comment by anxdpanic** [comment]
Going to bump version soon, have you noticed any unexpected behavior?

**Comment by tadly** [comment]
Still looking good over here :)

**Comment by anxdpanic** [comment]
Thanks for confirming, bumped to 6.4.1 now.
