### ISSUE TITLE
Key mappable endpoints

### ISSUE THREAD

**Issue by anxdpanic** [jdf76/plugin.video.youtube#497]
RunPlugin endpoints, that users can map to key presses
https://kodi.wiki/view/Keymap
https://kodi.wiki/view/Keymap#Add-on_built-in.27s

Suggested actions:
- [x] add to playlist
- [x] remove from playlist
- [x] add to watch later
- [x] rate
- [x] play audio only
- [x] play with subtitles
- [x] go to channel
- [x] subscribe
- [x] unsubscribe

Mappable actions: 
https://kodi.wiki/view/Add-on:YouTube#Keymaps
```
RunPlugin(plugin://plugin.video.youtube/play/?audio_only=1)  # Plays current ListItem as audio only
RunPlugin(plugin://plugin.video.youtube/play/?prompt_for_subtitles=1)  # Plays current ListItem with selected subtitles
RunPlugin(plugin://plugin.video.youtube/video/rate/?rating=like)  # Like the current ListItem
RunPlugin(plugin://plugin.video.youtube/video/rate/?rating=dislike)  # Dislike the current ListItem
RunPlugin(plugin://plugin.video.youtube/video/rate/?rating=none)  # Remove rating from the current ListItem
RunPlugin(plugin://plugin.video.youtube/video/rate/)  # Rating selection dialog for the current ListItem
RunPlugin(plugin://plugin.video.youtube/playlist/add/video/?playlist_id=watch_later)  # Add current ListItem to Watch Later playlist
RunPlugin(plugin://plugin.video.youtube/playlist/add/video/?playlist_id=PLDmQ0lsL4hGK48quXwOoz4q3MpsavqiIR)  # Add current ListItem to user specified playlist
RunPlugin(plugin://plugin.video.youtube/playlist/select/playlist/)  # Add current ListItem to the user selected playlist
RunPlugin(plugin://plugin.video.youtube/playlist/remove/video/)  # Remove current ListItem from current playlist
RunPlugin(plugin://plugin.video.youtube/channel/property/)  # Go to channel of the current ListItem
RunPlugin(plugin://plugin.video.youtube/subscriptions/add/)  # Subscribe to current ListItem
RunPlugin(plugin://plugin.video.youtube/subscriptions/remove/)  # Unsubscribe from current ListItem
```

Comment with actions you might want to see that aren't already mentioned

**Comment by tadly** [comment]
If this is being implemented in such a way that adding stuff is not difficult than the following could be added as well because why the heck not:
* Go to channel
* Subscribe to channel

**Comment by tadly** [comment]
* Play audio only

(just noticed this is a new context-menu addition and would make a lot of sense being mapped IMO)

**Comment by anxdpanic** [comment]
#506 Adds keymap support for audio only and ratings

```
RunPlugin(plugin://plugin.video.youtube/play/?audio_only=1)  # Plays current ListItem as audio only
RunPlugin(plugin://plugin.video.youtube/video/rate/?rating=like)  # Like the current ListItem
RunPlugin(plugin://plugin.video.youtube/video/rate/?rating=dislike)  # Dislike the current ListItem
RunPlugin(plugin://plugin.video.youtube/video/rate/?rating=none)  # Remove rating from the current ListItem
```

**Comment by tadly** [comment]
Awesome!
Would just `RunPlugin(plugin://plugin.video.youtube/video/rate/` also be possible showing a dialog where I can pick one of the other three options (like, dislike, remove)?
Then I wouldn't have to map 3 different keys :)

**Comment by anxdpanic** [comment]
Should be fixed up with 0a165d2
```
RunPlugin(plugin://plugin.video.youtube/video/rate/)  # Rating selection dialog for the current ListItem
```

**Comment by tadly** [comment]
Just wanna say I really like *working* (not like I'm doing much) with you.
It's so uncomplicated.

**Comment by anxdpanic** [comment]
Thank you for making it easy :)

0041215 adds support for add to watch later, user specified playlist and user selected playlists
```
RunPlugin(plugin://plugin.video.youtube/playlist/add/video/?playlist_id=watch_later)  # Add current ListItem to Watch Later playlist
RunPlugin(plugin://plugin.video.youtube/playlist/add/video/?playlist_id=PLDmQ0lsL4hGK48quXwOoz4q3MpsavqiIR)  # Add current ListItem to user specified playlist
RunPlugin(plugin://plugin.video.youtube/playlist/select/playlist/)  # Add current ListItem to the user selected playlist
```

**Comment by anxdpanic** [comment]
#509 adds support for go to channel, subscribe/unsubscribe and remove from current playlist

```
RunPlugin(plugin://plugin.video.youtube/playlist/remove/video/)  # Remove current ListItem from current playlist
RunPlugin(plugin://plugin.video.youtube/channel/property/)  # Go to channel of the current ListItem
RunPlugin(plugin://plugin.video.youtube/subscriptions/add/)  # Subscribe to current ListItem
RunPlugin(plugin://plugin.video.youtube/subscriptions/remove/)  # Unsubscribe from current ListItem
```

**Comment by tadly** [comment]
Nice work with documenting it as well!
Once you make alpha4 I can do some testing.

As of yet I'm not sure what's already included in alpha3 so it's kind of a hit or miss (:

**Comment by tadly** [comment]
Dude no hurry. It's christmas time after all and I'm kinda short on time anyways :)
Thanks for all the work you've put in!

**Comment by anxdpanic** [comment]
I've bumped the zip to alpha4, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev
Hope you have a great holiday :)

**Comment by tadly** [comment]
Looking good and oh boy do I love this!

Makes using the add-on within kodi soooo much more convenient (given you have a remote which allows mapping lots of stuff to)

The only improvement I'd have is to post notifications for the following actions:
 * Add to Watch Later
   Title: _Added to Watch Later_
 * Add to the user provided playlist
   Title: _Added to playlist_
 * Remove from the current playlist
   Title: _Removed from playlist_
 * Like
   Title: _Liked video_
 * Dislike
   Title: _Disliked video_
 * Remove rating
   Title: _Rating removed_
 * Subscribe
   Title: _Subscribed to channel_
 * Unsubscribe
   Title: _Unsubscribed from channel_

All these notifications make sense even if the action was invoked from the context menu (or elsewhere if even possible) as it gives the user a confirmation that _it actually worked_.
As such this would be more of a general improvement to the addon (not specific to this issue).

Also, the duration of those notifications should **not** be the default 5 seconds. 2 are probably enough (3 at most I'd say).
It's only a title and no body with little text to read.

Again, thanks for all your work and hope you're having a great holiday too!

**Comment by anxdpanic** [comment]
After trying it out a bit, adding some sort of feedback was definitely necessary. 
It's added with cb301f01263ad1fbf58680588a6d5b3e4dc62ff7 and it's in alpha5 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev

**Comment by tadly** [comment]
Hope you had a good start into the new year so far.
I'm here to nit-pick if you don't mind ':D

First off, `Refresh` would be nice if we could map (I think that's a custom implementation?)

Second, the nit-picky part.
It would be awesome if the **next** listitem would be selected after executing a action.
Reason for this is due to how kodi itself handles queuing items.
If you press `q` on the keyboard it will be put into the current playlist and the next listitem will be selected automatically.
So I often end up spamming `q` a few times to quickly build a playlist.
Being able to (just as quickly) add stuff to e.g. watch later would be nice.
I think it would be important that the next listitem is selected immediately and **not after** processing the *request* (e.g. adding to watch later takes a good second or two) so the user can *spam* it.
If this would cause issues due to the plugin still processing the first request while the second is being made then I have to get back to the drawing board.
What actions should cause the next item to be selected is up for discussion.

These (obviously) should *not*:
* Play audio only
* Play with subtitles
* Go to channel

These (IMO) should :
* Add to Watch Later
* Add to the selected playlist
* Add to the user provided playlist
* Remove from the current playlist
  _This one's tricky because it causes a refresh of the current view. Don't remember what happens after_

These kinda make sense but also could leave the user confused?!
* Like
* Dislike
* Remove rating
* Prompt for rating
* Subscribe
* Unsubscribe

**Comment by anxdpanic** [comment]
It's been a good start to the year, hope yours is good as well.

Container.Refresh should work for refresh, there is nothing special about the add-on's refresh.

Will have to look into changing the listitem focus, I would assume it's possible though.

Remove from current playlist shouldn't be too bad.  An unchanged list position should work, where the others would be position + 1

Hopefully have time for this tomorrow, with live streams breaking today(have time shift with mpeg-dash live streams after the fix though) I'm hoping to get bumped to beta for the weekend.

**Comment by tadly** [comment]
Thanks a bunch man ❤❤❤

**Comment by jonisb** [comment]
If I have a channel name is there a way to go to that channel via the plugin? 
If not I would like to request such a command.

I'm working on a plugin that gives me a list of channels names but now I don't see how to show the videos for those channels.

Thanks for the continued work on the plugin. 😃

**Comment by anxdpanic** [comment]
This issue is unrelated, you have a couple options though.
You can directly use https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_requests.py
or this module which is based on the above, https://github.com/xbmc/repo-scripts/pull/1021 (see this for example usage and the add-ons which use it)

Or you can create static entries which point to: `plugin://plugin.video.youtube/channel/<channel_id/`

**Comment by jonisb** [comment]
Thank you, exactly what I needed. 👍
