### ISSUE TITLE
Auto-Remove from Watch Later removes wrong video

### ISSUE THREAD

**Issue by tadly** [jdf76/plugin.video.youtube#498]
If you play one video from watch-later and queue another video from watchler, the **second** video will be removed once the first finishes.

Seems like [this](https://github.com/jdf76/plugin.video.youtube/blob/04bfe6efb4b86e22c5dc418253dcfb5d2544773b/resources/lib/youtube_plugin/youtube/provider.py#L696) returns the wrong video-id.

**Comment by anxdpanic** [comment]
Have an idea how to get this fixed, just pr'd 6.2.3 to the official repository so will be working on these watch later fix ups next

**Comment by tadly** [comment]
Awesome thanks!

This should also explain why sometimes auto removal wouldn't work as the mentioned line would end up with no video-id in case it's the only item in the playlist (I assume, didn't actually test that)

**Comment by anxdpanic** [comment]
This should be resolved with https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev

I moved the playback monitor out of the service and inline with playback. The video id won't be overwrote like it was with window properties/service now.

**Comment by tadly** [comment]
Will test that sometime later today (hopefully) :)

**Comment by tadly** [comment]
Only got to it just now but seems to be working fine :)

**Comment by tadly** [comment]
I think we can close this. Has been working pretty reliable so far :)
