### ISSUE TITLE
search and return not working ?

### ISSUE THREAD

**Issue by zosky** [jdf76/plugin.video.youtube#50]
hi, im [trying to enhance context.trailer](https://github.com/BigNoid/context.trailer/pull/2) to use your search if there is no trailer in the db, but its not behaving _properly_ 

this pulls up results but [it wont cooperate](https://gist.github.com/zosky/3a7195dabb355218623a60dd1a1a4ee4) when you try to return

```xbmc.executebuiltin("ActivateWindow(videos,plugin://plugin.video.youtube/kodion/search/query/?q=%s Trailer&search_type=video,return)" % name)```

any suggestions ?

**Comment by anxdpanic** [comment]
Likely related to:
xbmc/pull/12058
xbmc/pull/12050

**Comment by anxdpanic** [comment]
Closed due to inactivity, please re-open if still an issue.
