### ISSUE TITLE
Videos will not play!

### ISSUE THREAD

**Issue by theGuruWithin** [jdf76/plugin.video.youtube#52]
Last night plugin worked and today it won't play videos on both Kodi 17.1 and 16.1.

Here is error log... Please fix... Really love plugin!
https://paste.ubuntu.com/24389148/

**Comment by theGuruWithin** [comment]
I installed new 5.3.13~alpha3 then
I deleted all history and databases plus installed
Still no videos will play.  I get Youtube Error "check log for info"

BTW I have 4 boxes and plugin still works on just one of the boxes still running 16.1.  All were flashed originally from same image.

**Comment by anxdpanic** [comment]
Looks to be either a dependency issue(can try to re-install script.module.requests) or os/environment issue.
