### ISSUE TITLE
How to contribute to Korean translation

### ISSUE THREAD

**Issue by parkmino** [jdf76/plugin.video.youtube#525]
I visited this github and came to know that Korean translation is not complete.
I would like to contribute to Korean translation.
Downloading and translating 'language/resource.language.ko_kr' could be accpetable for you?
I will attach the translated file here if accpetible.

P.S. Youtube livestream seems not work any more for me.
Is this project related to youtube-dl that seems to have this issue at the moment?

**Comment by anxdpanic** [comment]
Welcome and thank you.
Downloading and translating would be fine--this was just done with nl_NL 10 minutes ago--, or you could also use https://help.github.com/articles/editing-files-in-another-user-s-repository/ .

This project doesn't use youtube-dl. For the live stream issue see #299 and the comments following https://github.com/jdf76/plugin.video.youtube/issues/299#issuecomment-452721549

**Comment by parkmino** [comment]
OK and I will attach the translated file here.

I have been using youtube livestream without any problem under ubuntu 18.04 and it might have been messed up while trying other addons.
I will look into it ;)

**Comment by anxdpanic** [comment]
The live stream issue is a new issue, see #527

**Comment by anxdpanic** [comment]
@parkmino to fix live streams see https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev

**Comment by parkmino** [comment]
Please find the attached file for 'resources/language/resource.language.ko_kr/strings.po'

Livestream came back to me again with 'plugin.video.youtube-6.3.0.alpha7.zip'

Cheers!

[strings.po.txt](https://github.com/jdf76/plugin.video.youtube/files/2747663/strings.po.txt)

**Comment by anxdpanic** [comment]
Thank you very much for the contribution! 
It is added with https://github.com/jdf76/plugin.video.youtube/commit/7837fb95b3c6e9bb42f30539b863710cdbd31268
beta1 adds your translation and a fixup for live streams, which is available from https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev

I'm going to close this issue now, open a new issue for any future additions and thank you again 👍
