### ISSUE TITLE
YouTube Livestreams play as AAC audio for 5 seconds, then playback ends

### ISSUE THREAD

**Issue by webodan** [jdf76/plugin.video.youtube#527]
Hi,

So I've been using upgraded Krypton to Leia on LibreELEC RPi2.arm yesterday and the version of this plugin that comes with the repo of it, and it was working fine until i tried it again today, and now for some reason livestreams will only play as audio and playback stops after 5 seconds. I tried installing version 6.3.0 alpha-3 (i think it was) just in case something went wrong on the upgrade, and the problem persists. I've also tried downgrading libreelec from 8.95.002 to 8.95.001 in case something was wrong with that, since I had both versions available on the update repo. Same result.

**Comment by anxdpanic** [comment]
Need more information, please provide a log reproducing the issue with debug logging enabled 
https://kodi.wiki/view/Log_file

**Comment by anxdpanic** [comment]
n/m I'm able to reproduce this, something has changed on YouTube's end again.

**Comment by anxdpanic** [comment]
Can you try https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev alpha7
Live streams should be working better than before, with time shifting now working with mpeg-dash enabled for live streams

**Comment by webodan** [comment]
I upgraded it and it seems to work now! I'll report back if anything pops up. Thank you again!

**Comment by anxdpanic** [comment]
This was reported on the forums as well, was my fault (overlooked what was supposed to be a temporarily commented out piece of code.)

beta1 adds a fixup for live streams 
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev

w/ Kodi 18 non-dash live streams seem to work without issue
w/ mpeg-dash and Kodi 17 and 18 most streams should now play with beta1. Some of the live streams have large sync issues that I don't believe I can resolve with the add-on. Time shifting back a small amount _seemed_ to work, not sure how reliable this is though.

**Comment by anxdpanic** [comment]
Thanks @webodan 

@tadly I tested the live stream in the log and it appears to be working here now. The ~5 second bit of audio is the only ```audio only``` stream returned/available so I don't see a way to implement audio only for live streams currently.

**Comment by tadly** [comment]
Bummer. Was hoping it would finally be possible. Thanks anyways :)

**Comment by TheLux83** [comment]
I want to throw my hat in the ring, too.
I have the same problem. I'm using Librelec 8.2.5 with YouTube Plugin and InputStream Adaptive. My Streams are starting with sound only and are closing after 5 seconds.

This is the part in the logfile that is created when starting a Livestream.
```
13:49:40.466 T:1426060192  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.3) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': '20lATPvwNmE'}
13:49:42.071 T:1945272320  NOTICE: VideoPlayer: Opening: https://r1---sn-4g5e6nzl.googlevideo.com/videoplayback?signature=8AB8746C6D8A956B1309188FD3AEBB2F9CC1E06F.CCE8CD944AEDC6C3D2502D23D5C38B5040E82613&mt=1547300904&mv=m&pl=18&ei=dfA5XOT5AsyzgAfr07roAw&ms=lv&mm=32&mn=sn-4g5e6nzl&key=yt6&compress=yes&c=WEB_EMBEDDED_PLAYER&gir=yes&hang=1&beids=9466587&gcr=de&noclen=1&initcwndbps=1278750&expire=1547322581&live=1&ipbits=0&mime=audio%2Fmp4&cmbypass=yes&source=yt_live_broadcast&id=20lATPvwNmE.1&sparams=cmbypass%2Ccompress%2Cei%2Cgcr%2Cgir%2Chang%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clive%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnoclen%2Cpl%2Crequiressl%2Csource%2Cexpire&itag=140&requiressl=yes&ip=31.19.204.46&keepalive=yes|Cookie=GPS%3D1%3B%20PREF%3Df1%3D50000000%3B%20VISITOR_INFO1_LIVE%3DpDGV3bWwY9w%3B%20YSC%3D2e4gUG3OAEs%3B%20s_gl%3D1c7eef1e2f3f866318cc434af62424b9cwIAAABERQ%3D%3D%3B
13:49:42.071 T:1945272320 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:49:42.141 T:1474294688  NOTICE: Creating InputStream
13:49:42.548 T:1474294688  NOTICE: Creating Demuxer
13:49:42.554 T:1474294688  NOTICE: Opening stream: 0 source: 256
13:49:42.554 T:1474294688  NOTICE: Finding audio codec for: 86018
13:49:42.556 T:1474294688  NOTICE: Creating audio thread
13:49:42.557 T:1587540896  NOTICE: running thread: CVideoPlayerAudio::Process()
13:49:42.567 T:1587540896  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
13:49:42.741 T:1474294688 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
13:49:44.376 T:1474294688  NOTICE: CVideoPlayer::OnExit()
13:49:44.376 T:1474294688  NOTICE: VideoPlayer: eof, waiting for queues to empty
13:49:44.377 T:1474294688  NOTICE: Closing stream player 1
13:49:44.377 T:1474294688  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
13:49:44.389 T:1474294688  NOTICE: Waiting for audio thread to exit
13:49:44.390 T:1587540896   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
13:49:44.390 T:1587540896  NOTICE: thread end: CVideoPlayerAudio::OnExit()
13:49:44.390 T:1474294688  NOTICE: Closing audio device
13:49:44.589 T:1474294688  NOTICE: Deleting audio codec
13:49:44.632 T:1945272320  NOTICE: CVideoPlayer::CloseFile()
13:49:44.632 T:1945272320  NOTICE: VideoPlayer: waiting for threads to exit
13:49:44.632 T:1945272320  NOTICE: VideoPlayer: finished waiting
13:49:44.633 T:1945272320  NOTICE: CVideoPlayer::CloseFile()
13:49:44.633 T:1945272320  NOTICE: VideoPlayer: waiting for threads to exit
13:49:44.633 T:1945272320  NOTICE: VideoPlayer: finished waiting
```

**Comment by webodan** [comment]
@TheLux83 upgrade to libreelec based on kodi leia, not krypton (use a beta update channel), that fixed it for me

**Comment by anxdpanic** [comment]
@TheLux83 
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.3.0-dev 
The 6.3.0~beta2 version here should work with Kodi 17+ mpeg-dash, and Kodi 18 with/without mpeg-dash.

**Comment by TheLux83** [comment]
Hey @webodan and @anxdpanic thanks for your really fast reply :)
I've updatet to the 6.3.0~beta2 and it doesn't seem to work with mpeg-das.
I get the following error:
```
14:07:50.973 T:1937801888  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=20lATPvwNmE
14:07:50.974 T:1808769904  NOTICE: Creating InputStream
14:07:50.978 T:1808769904   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.0.20
14:07:50.979 T:1808769904   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
14:07:50.979 T:1808769904   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=20lATPvwNmE]
14:07:50.979 T:1808769904  NOTICE: CVideoPlayer::OnExit()
14:07:51.186 T:1937801888  NOTICE: CVideoPlayer::CloseFile()
14:07:51.186 T:1937801888  NOTICE: VideoPlayer: waiting for threads to exit
14:07:51.186 T:1937801888  NOTICE: VideoPlayer: finished waiting
```
I've installed inputstream adaptive in version 2.3.12.0
If I disable mpeg-dash, my live streams are working again. 

Another question: Is watching live streams better with mpeg-dash? Or don't we need it with kodi 18 anymore?

**Comment by TheLux83** [comment]
Hm, I've activated debugging, started YouTube with mpeg-dash again and... it worked. Don't know why, but it works now. Many many thanks for your efforts!
