### ISSUE TITLE
Support for webm(vp9/opus) streams

### ISSUE THREAD

**Issue by monarc99** [jdf76/plugin.video.youtube#53]
Is it possible to support the webm streams (vp9&opus)?

e.g. all available streams for yYanlaOOpsQ
Youtube Addon can only play the old formats and the dash formates in the mpd (only mp4 streams).

>youtube-dl -F https://www.youtube.com/watch?v=yYanlaOOpsQ
>[youtube] yYanlaOOpsQ: Downloading webpage
>[youtube] yYanlaOOpsQ: Downloading video info webpage
>[youtube] yYanlaOOpsQ: Extracting video information
>[youtube] yYanlaOOpsQ: Downloading MPD manifest
>[info] Available formats for yYanlaOOpsQ:
>format code  extension  resolution note
>249          webm       audio only DASH audio   57k , opus @ 50k, 10.15MiB
>250          webm       audio only DASH audio   74k , opus @ 70k, 13.18MiB
>171          webm       audio only DASH audio  124k , vorbis@128k, 23.08MiB
>140          m4a        audio only DASH audio  129k , m4a_dash container, mp4a.40.2@128k (44100Hz), 27.29MiB
>251          webm       audio only DASH audio  142k , opus @160k, 25.71MiB
>160          mp4        256x144    DASH video  118k , avc1.4d400c, 30fps, video only, 18.03MiB
>278          webm       256x144    144p  119k , webm container, vp9, 30fps, video only, 19.17MiB
>133          mp4        426x240    DASH video  255k , avc1.4d4015, 30fps, video only, 52.80MiB
>242          webm       426x240    240p  273k , vp9, 30fps, video only, 42.00MiB
>243          webm       640x360    360p  494k , vp9, 30fps, video only, 79.37MiB
>134          mp4        640x360    DASH video  655k , avc1.4d401e, 30fps, video only, 108.26MiB
>244          webm       854x480    480p  911k , vp9, 30fps, video only, 146.15MiB
>135          mp4        854x480    DASH video 1219k , avc1.4d401f, 30fps, video only, 208.31MiB
>247          webm       1280x720   720p 2083k , vp9, 30fps, video only, 298.86MiB
>136          mp4        1280x720   720p 2495k , avc1.4d401f, 30fps, video only, 422.04MiB
>302          webm       1280x720   720p60 3160k , vp9, 60fps, video only, 492.94MiB
>298          mp4        1280x720   DASH video 3636k , avc1.4d4020, 60fps, video only, 646.10MiB
>248          webm       1920x1080  1080p 4335k , vp9, 30fps, video only, 544.22MiB
>137          mp4        1920x1080  1080p 4658k , avc1.640028, 30fps, video only, 780.56MiB
>303          webm       1920x1080  1080p60 5438k , vp9, 60fps, video only, 856.81MiB
>299          mp4        1920x1080  DASH video 6024k , avc1.64002a, 60fps, video only, 1.08GiB
>264          mp4        2560x1440  DASH video 10779k , avc1.640032, 30fps, video only, 1.86GiB
>271          webm       2560x1440  1440p 10833k , vp9, 30fps, video only, 1.77GiB
>308          webm       2560x1440  1440p60 15585k , vp9, 60fps, video only, 2.60GiB
>17           3gp        176x144    small , mp4v.20.3, mp4a.40.2@ 24k
>36           3gp        320x180    small , mp4v.20.3, mp4a.40.2
>43           webm       640x360    medium , vp8.0, vorbis@128k
>18           mp4        640x360    medium , avc1.42001E, mp4a.40.2@ 96k
>22           mp4        1280x720   hd720 , avc1.64001F, mp4a.40.2@192k (best)
`
the streams can be found in  -> adaptive_fmts : https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/video_info.py#L598

greetings
monarc

**Comment by anxdpanic** [comment]
Cannot be done atm. They are 'video only' and Kodi doesn't provide support for muxing, an inputstream add-on may provide this functionality in the future.

**Comment by greystashh** [comment]
Has there been any news for inputstream compability?

**Comment by anxdpanic** [comment]
It looks like there are some AML VP9 support PR's to kodi master, but I believe the way inputstream.adaptive works VP9 support will have to be added there. Which I haven't seen any movement on.

**Comment by greystashh** [comment]
As I see you have created a commit yesterday concerning webm. Does vp9 work already?

**Comment by anxdpanic** [comment]
They don't work, but including them in the manifest with latest versions of inputstream.adaptive doesn't cause an issue either. So I've included them in the manifest for the newer versions, so when they are working we hopefully shouldn't need any additional changes.

**Comment by Leon99** [comment]
Knock-knock. Any news on this? I'm considering a switch to watching YouTube via Kodi, and the first thing I noticed is that the video quality is somewhat inferior here, I figured out the reason is the codec. Is there any hope to get webm support any time soon?

**Comment by greystashh** [comment]
Maybe this may help to create a dash manifest?

http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash

**Comment by greystashh** [comment]
@anxdpanic   peak3d has integrated vp9 playback for the Netflix addon. Maybe this is now possible for YouTube as well including HDR

**Comment by anxdpanic** [comment]
I tried this out, and it's not working for YouTube (the webm streams don't show even in manual selection). I will get everything together and reach out to peak3d when I get a chance next.

**Comment by greystashh** [comment]
Is it working already with this version?

**Comment by anxdpanic** [comment]
not working, but it allows adding those streams so it can be tested easier

**Comment by alsteiner** [comment]
Times change. I have created a tutorial in which I show how it is possible for everyone to publish high-quality sound (opus @ 160kbps) on YouTube. See here: '2019 How to Upload Best Audio Quality to YouTube. Opus for All. ' → https://youtu.be/yjBIzNId5Yk

**Comment by anxdpanic** [comment]
6.4.0 enables webm-vp9, requires inputstream.adaptive >= 2.3.14
https://github.com/jdf76/plugin.video.youtube/wiki/Installation
Submitted and waiting review to the Official repository as well

Closing this, #257 will contain follow up when opus/vorbis and av1 support are available.
