### ISSUE TITLE
Unofficial repository for alphas, betas and stables.

### ISSUE THREAD

**Issue by tadly** [jdf76/plugin.video.youtube#537]
Have you ever thought of having a unofficial repository for this addon which would have both stable and dev builds for both the official and unofficial version?

I'm a lazy person and manually updating the add-on to the latest dev version is a little tedious :)

Further, the unofficial version does (obviously) have it's merits and having it in **a** repository would make sense.

**Comment by anxdpanic** [comment]
I've staged 3 repositories, I won't have a chance to test them directly tonight. They are available here; https://github.com/jdf76/repository

**Comment by anxdpanic** [comment]
hah, It's been on the TODO for quite a while, this just gave me the nudge to finally to do it. :D

Yeah, all in one repository wouldn't work too well with the current system. I'd love to be able to add a 'tag' to each version and be able to choose the 'tags' you want from the repository for that add-on. 

Jumping between versions _should_ work in Krypton as well.

The majority of the work was just getting things set up, I have something like 8 portable Kodi versions, and 5 repositories all with symlinks to the add-ons git folders, It does add some maintenance but for the most part it's as simple as checking out the correct branch of the add-on and then running the appropriate repository generator.

**Comment by tadly** [comment]
Welp, call me _The Nudger_ then :D (does sound kinda cool actually)

Will obviously test this (sometime this evening I hope)

**Comment by anxdpanic** [comment]
Instead of adding zips to the in *-dev tag I added a link to a new wiki page with all the installation links. https://github.com/jdf76/plugin.video.youtube/wiki

**Comment by tadly** [comment]
Just realized something with the release of 6.3.1...

If you are using the dev repository you won't get automatically updated to the latest release and are therefore "stuck" on an outdated version.

As such I'd like to discuss whether or not it would make sense to also push the latest releases to the dev repository.

I myself use the dev repo for my main setup but am missing out on the improvements made between the most recent dev release and the final release which would force me to explicitly switch to a different repository within kodi (a lot of steps).

---

After writing the above and double-checking if this is really the case, I realized that the latest version in the dev repo is `6.3.2-alpha1` while the most recent release is only `6.3.1` (which came **after** dev).
Even if auto-updating across multiple repositories would work (which is what I wanted to test but doubt it will) it wouldn't work if the version numbers don't line up (release should be higher than dev in this case).
Is there a explicit reason for this or was that just an oversight maybe?

And finally:
In the [wiki](https://github.com/jdf76/plugin.video.youtube/wiki/Installation), the **Add-on zip files** URL for **Stable Versions** -> **Unofficial** is wrong (Currently pointing to testing)

**Comment by anxdpanic** [comment]
I fixed the link to Unofficial. 

I might need some more clarification.

If you're on a dev repository you can install the regular unofficial repository or update from official repository without issue, so you shouldn't be stuck. 
Wouldn't be much to push the stable release to the dev repositories as well though

6.3.1 comes before the dev release 6.3.2~alpha1, 6.3.1 never had a dev version as it was fixups required after the official repository review.

**Comment by tadly** [comment]
> If you're on a dev repository you can install the regular unofficial repository or update from official repository without issue, so you shouldn't be stuck.
Wouldn't be much to push the stable release to the dev repositories as well though

Yeah, saying *stuck* wasn't quite right. As I said, you **can** manually switch to a different version (other repository) but this would involve _a lot of work_ as kodi doesn't itself automatically switch repositories if one has a newer version whiiiiiich brings me to...

> 6.3.1 comes before the dev release 6.3.2~alpha1, 6.3.1 never had a dev version as it was fixups required after the official repository review.

Does 6.3.1 include all the new and fancy stuff introduced in the dev versions? (like keyboard shortcuts, history tracking on youtube etc.)?

I assume it **does not** given the version numbers and the way you phrased it.

I guess I just got confused about the the whole `-dev` release/tag disappearing from the release section which led me to think:
_Uh, dev phase is over, all the changes are now in the most recent release which was 3 days ago._
And here we are 😄

Whether or not the version numbers are actually correct (which I assume they are) the general question is:
Should the dev repository **always** have the most recent add-on version even if it's not technically a alpha, beta, etc. just to add convenience for users who use the dev repository as their "main" (me 😁).

**Comment by anxdpanic** [comment]
I always remove the dev tag releases, they always pointed to the alpha1 commit and GitHub's source zips weren't representative of the latest dev version. The tag/release was mainly used as a landing page from the forums, now it links to the installation wiki entry.

In the future, I will push the stable versions to the in development repositories, will only take an extra 1~2 mins. :smile:

The version that contained all the new stuff was 6.3.0, but when it went stable and I PR'd to the official repository some changes were required. Those changes were made and bumped the add-on to 6.3.1. (Yes, 6.3.1 includes all the new stuff eg. keymapping)

Another issue was brought up (some videos broken for some peoples accounts) but it's a change that could break video playback, so a new dev version was started; 6.3.2~alpha1

**Comment by tadly** [comment]
Aaaah... Now I follow and also just realized I could have saved use some time by looking at release date of `6.3.2~alpha1` which is 2 days ago => newer than the latest stable.

Sorry for that 🙄 

Guess that concludes this issue (again) :)
