### ISSUE TITLE
All Music Videos not working

### ISSUE THREAD

**Issue by XxAcielxX** [jdf76/plugin.video.youtube#548]
Hello,

I'm trying to play music videos, but none of them play at all. Any video which has its Category as *Music* will not play, but they play fine on Android/PC.

Plugin v6.3.0 Official
Milhouse 9.0 Latest Build on RPi3.

Example Links
https://youtu.be/pqYWDvV0I28
https://youtu.be/RHZx8ydaNF8

Regards~

**Comment by anxdpanic** [comment]
They are working here, run Settings - Maintenance - Clear function cache, if that doesn't resolve it will need a debug log

**Comment by XxAcielxX** [comment]
Ahh, should have mentioned this somewhere. I was going crazy trying to get them to play.

Thanks there for your quick reply, like that about you. 🙂

**Comment by TimDomino** [comment]
I've had a similar problem today with different video (not music videos). An update to the new release did not yet resolve the issue, but a subsequent "Clear function cache" finally did the trick. Thanks for the hint and your awesome plugin. Maybe it makes sense to include this fix in some FAQ ;-)

**Comment by teodoryantcheff** [comment]
Came here to report music and other videos not playing with 6.3.1 but the 

**"Clear Function Cache" does resolve the problem!**

:+1: 

Thanks and as @TimDomino suggests it does make sense to have that documented somewhere...maybe.

**Comment by goggle** [comment]
Clearing the function cache did not work for me. I have also tried to disable MPEG-DASH playback without success. There are several videos that do not work for me (e.g. https://www.youtube.com/watch?v=GW_gsNVM498). Here is the debug log:

```
04:55:31.361 T:976208752  NOTICE: [plugin.video.youtube] Running: YouTube (6.3.1) on Leia (Kodi-18.0) with Python 2.7.15
                                            	Path: /maintain/function_cache/clear/
                                            	Params: {}
04:55:36.257 T:976208752  NOTICE: [plugin.video.youtube] Running: YouTube (6.3.1) on Leia (Kodi-18.0) with Python 2.7.15
                                            	Path: /maintain/data_cache/clear/
                                            	Params: {}
04:55:44.670 T:976208752  NOTICE: [plugin.video.youtube] Running: YouTube (6.3.1) on Leia (Kodi-18.0) with Python 2.7.15
                                            	Path: /maintain/function_cache/delete/
                                            	Params: {}
04:56:17.818 T:1937784848   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
04:56:18.982 T:976208752  NOTICE: [plugin.video.youtube] Running: YouTube (6.3.1) on Leia (Kodi-18.0) with Python 2.7.15
                                            	Path: /channel/mine/playlist/LLOzAOB2ViO4yTKdor0vstWA/
                                            	Params: {}
04:56:26.353 T:976208752  NOTICE: [plugin.video.youtube] Running: YouTube (6.3.1) on Leia (Kodi-18.0) with Python 2.7.15
                                            	Path: /play/
                                            	Params: {'video_id': 'GW_gsNVM498'}
04:56:29.951 T:1937784848  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=GW_gsNVM498
04:56:29.952 T:1937784848   ERROR: CCurlFile::Stat - Failed: Unsupported protocol(1) for plugin://plugin.video.youtube/play/?video_id=GW_gsNVM498
04:56:29.954 T:992994160  NOTICE: Creating InputStream
04:56:30.236 T:992994160   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
04:56:30.238 T:992994160   ERROR: CCurlFile::Open failed with code 403 for https://r1---sn-fpobv-1gie.googlevideo.com/videoplayback?mime=video%2Fmp4&txp=5531432&ratebypass=yes&expire=1548150987&ei=a5RGXJiAKMim1gLalYOYCw&c=WEB&lmt=1538708825306112&fvip=1&lsparams=ms%2Cpl%2Cmn%2Cmm%2Cmv%2Cinitcwndbps&mt=1548129279&clen=13712455&ms=au%2Crdu&pbrmi=600&source=youtube&mv=m&initcwndbps=741250&id=o-AEFztUVaT4po66yPQqrsF-ECcAhDUapRsVGUnkAE4J-f&pl=24&lsig=ALy0alEwRgIhAIns4KHVlV80quHIOonJX6mfyRt3RuI97SLr5cU2QcXxAiEA90W8vhTkIFQEZJJmOnvjvSHtZcIeWMtXtgUdKcxrTyA%3D&dur=249.939&ipbits=0&gir=yes&itag=18&sparams=expire%2Cei%2Cip%2Cratebypass%2Cgir%2Clmt%2Cipbits%2Citag%2Cclen%2Crequiressl%2Cid%2Cmime%2Csource%2Cdur&mn=sn-fpobv-1gie%2Csn-1gieen7e&mm=31%2C29&ip=178.238.175.175&requiressl=yes&signature=AOvmAUowRgIhAMJDDgIhPAAdtrZsmyJ2VpBUS8t8Kti-g8EPdpgQ2GcPAiEA8M-DHL1DIrPvDhoh5_M0ipa54GmXTxqOtIhj7kLlUl8=:
04:56:30.378 T:992994160   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
04:56:30.381 T:992994160   ERROR: CCurlFile::Open failed with code 403 for https://r1---sn-fpobv-1gie.googlevideo.com/videoplayback?mime=video%2Fmp4&txp=5531432&ratebypass=yes&expire=1548150987&ei=a5RGXJiAKMim1gLalYOYCw&c=WEB&lmt=1538708825306112&fvip=1&lsparams=ms%2Cpl%2Cmn%2Cmm%2Cmv%2Cinitcwndbps&mt=1548129279&clen=13712455&ms=au%2Crdu&pbrmi=600&source=youtube&mv=m&initcwndbps=741250&id=o-AEFztUVaT4po66yPQqrsF-ECcAhDUapRsVGUnkAE4J-f&pl=24&lsig=ALy0alEwRgIhAIns4KHVlV80quHIOonJX6mfyRt3RuI97SLr5cU2QcXxAiEA90W8vhTkIFQEZJJmOnvjvSHtZcIeWMtXtgUdKcxrTyA%3D&dur=249.939&ipbits=0&gir=yes&itag=18&sparams=expire%2Cei%2Cip%2Cratebypass%2Cgir%2Clmt%2Cipbits%2Citag%2Cclen%2Crequiressl%2Cid%2Cmime%2Csource%2Cdur&mn=sn-fpobv-1gie%2Csn-1gieen7e&mm=31%2C29&ip=178.238.175.175&requiressl=yes&signature=AOvmAUowRgIhAMJDDgIhPAAdtrZsmyJ2VpBUS8t8Kti-g8EPdpgQ2GcPAiEA8M-DHL1DIrPvDhoh5_M0ipa54GmXTxqOtIhj7kLlUl8=:
04:56:30.381 T:992994160   ERROR: Open - failed to open source <https://r1---sn-fpobv-1gie.googlevideo.com/videoplayback?mime=video%2Fmp4&txp=5531432&ratebypass=yes&expire=1548150987&ei=a5RGXJiAKMim1gLalYOYCw&c=WEB&lmt=1538708825306112&fvip=1&lsparams=ms%2Cpl%2Cmn%2Cmm%2Cmv%2Cinitcwndbps&mt=1548129279&clen=13712455&ms=au%2Crdu&pbrmi=600&source=youtube&mv=m&initcwndbps=741250&id=o-AEFztUVaT4po66yPQqrsF-ECcAhDUapRsVGUnkAE4J-f&pl=24&lsig=ALy0alEwRgIhAIns4KHVlV80quHIOonJX6mfyRt3RuI97SLr5cU2QcXxAiEA90W8vhTkIFQEZJJmOnvjvSHtZcIeWMtXtgUdKcxrTyA%3D&dur=249.939&ipbits=0&gir=yes&itag=18&sparams=expire%2Cei%2Cip%2Cratebypass%2Cgir%2Clmt%2Cipbits%2Citag%2Cclen%2Crequiressl%2Cid%2Cmime%2Csource%2Cdur&mn=sn-fpobv-1gie%2Csn-1gieen7e&mm=31%2C29&ip=178.238.175.175&requiressl=yes&signature=AOvmAUowRgIhAMJDDgIhPAAdtrZsmyJ2VpBUS8t8Kti-g8EPdpgQ2GcPAiEA8M-DHL1DIrPvDhoh5_M0ipa54GmXTxqOtIhj7kLlUl8=|Cookie=PREF%3Df1%3D50000000%26al%3Dde%3B%20VISITOR_INFO1_LIVE%3DqHZstswLwDA%3B%20YSC%3D-j9ewLF5sCQ%3B%20s_gl%3Dd46ba3aed438c9891ac357ee87d8cd07cwIAAABDSA%3D%3D%3B>
04:56:30.381 T:992994160   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.youtube/play/?video_id=GW_gsNVM498]
04:56:30.381 T:992994160  NOTICE: CVideoPlayer::OnExit()
04:56:30.390 T:976208752   ERROR: EXCEPTION: XBMC is not playing any media file
04:56:30.505 T:1937784848  NOTICE: CVideoPlayer::CloseFile()
04:56:30.505 T:1937784848  NOTICE: VideoPlayer: waiting for threads to exit
04:56:30.505 T:1937784848  NOTICE: VideoPlayer: finished waiting
04:56:30.517 T:1937784848 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (0.55s)
```

**Comment by mittal07abhilash** [comment]
Facing the same issue for 3-4 days now. Clearing function cache didn't help.
Here is the log when I try to play music videos:
[Log.txt](https://github.com/jdf76/plugin.video.youtube/files/2782502/Log.txt)

**Comment by XxAcielxX** [comment]
@mittal07abhilash

You're using v6.2.3, where current version is v6.3.1

You need to update your YouTube Add-on Plugin to latest version then ***Settings - Maintenance - Clear function cache***

It will fix.

**Comment by mittal07abhilash** [comment]
I had somehow messed up my apt source list and was experiencing some other issues too. After fixing it everything works fine. Thanks for the quick reply though.

**Comment by goggle** [comment]
I have just discovered, that also `youtube-dl` fails to download to video mentioned above, but only when using my YouTube account to download the video. Without providing account credentials it works fine. Here is the link to the issue report: https://github.com/rg3/youtube-dl/issues/18950

**Comment by goggle** [comment]
Ok, it seems as though this is an already known issue which is discussed in this issue report: https://github.com/rg3/youtube-dl/issues/18841; but the `youtube-dl` maintainers cannot reproduce it.

Here is a possible fix (at least for `youtube-dl`): https://github.com/rg3/youtube-dl/pull/18927

**Comment by anxdpanic** [comment]
The cache is only valid for 1 day and then the issue will resolve itself as well, so those that don't clear the function cache will start working after the 1 day cache time.

For 6.3.2~alpha1 I added a fix so 'Clear function cache' won't be required for these types of issues going forward.

@goggle 
I'm not able to reproduce this issue either, all those videos work for me. I did test using the sp value when available and it does not break anything for me, so I went a head an added it to the alpha so you can confirm if it resolves your issue. You can find the zips @ https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

**Comment by goggle** [comment]
@anxdpanic Thanks for taking care of that issue. I've just installed the 6.3.2~alpha1 version on my local machine and tested the video mentioned above. The playback works now, but I only get a 480sd resolution. Other videos are played as usual in a 720hd resolution.

Here are the relevant sections of my Kodi log: 
[kodi_youtube_alpha.log](https://github.com/jdf76/plugin.video.youtube/files/2784934/kodi_youtube_alpha.log)

**Comment by anxdpanic** [comment]
This is a limitation on YouTube's end, the max quality for many videos is now 360p. To get higher qualities enabling and using InputStream Adaptive/MPEG-DASH is required.

**Comment by goggle** [comment]
@anxdpanic I have just tested it on another machine, where I have Kodi 18 and the "Inputstream Adaptive" addon installed, and there it works perfectly in high quality. Thanks!

**Comment by goggle** [comment]
@anxdpanic Did you apply the changes proposed in the youtube-dl PR (https://github.com/rg3/youtube-dl/pull/18927) to fix the issue? Could you mention the commit that fixes the issue, maybe this could also be applied to youtube-dl.

**Comment by anxdpanic** [comment]
This issue is resolved, opened a new issue for the issue reported by goggle.
