### ISSUE TITLE
Hide watched

### ISSUE THREAD

**Issue by tadly** [jdf76/plugin.video.youtube#565]
In Kodi, you typically can "Hide Watched" when e.g. browsing your Movies or TV-Shows.
This option is missing with the youtube addon.

As of now I'm not sure if this is a plugin limitation or if it's just a matter of properly setting media types etc.

**Comment by anxdpanic** [comment]
This is only available on the unofficial version, seems to be a limitation of content type/media type of video[s], that is required for the official repository.

**Comment by tadly** [comment]
Very interesting... Guess I'll be switching back to the unofficial version than :D
Case closed :)
