### ISSUE TITLE
More items in search history than max 50?

### ISSUE THREAD

**Issue by Cake11** [jdf76/plugin.video.youtube#57]
Hi,
Would it be possible to extend the Youtube search history to at least 100 or even unlimited. Currently 50 is (at least for me) very limiting.
Thanks!
Cake

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/pull/58/commits/103f84b5a7f16df6d1a4c890df02c3736b4bedb8 increases it to 200

**Comment by Cake11** [comment]
Dear jdf76,
Thank you for your effort. Really appreciated!!!
Best, Cake11
