### ISSUE TITLE
Login Activation malformed code

### ISSUE THREAD

**Issue by iadegesso** [jdf76/plugin.video.youtube#575]
Hi,
when I try to do the initial Login, I cannot complete it because the addon asked me to type two activation codes, but while the first one works, the second code is malformed since the form field in the activation page trucates it before the last character and it adds a long dash after the forth character. See the images below for more details.

I'm on Kodi 18 Leila, using LibreELEC on a Raspberry Pi 3B.

Regards

Iade Gesso, PhD in Computer Science

![immagine](https://user-images.githubusercontent.com/5804075/52540747-70588980-2d8d-11e9-8f09-ca1866d5f7b5.png)

![immagine](https://user-images.githubusercontent.com/5804075/52540752-7ea6a580-2d8d-11e9-8b11-e07e810ce992.png)

**Comment by anxdpanic** [comment]
The change to 9 characters is new, the issue isn't add-on related. Activation has worked every time for me, another report using a different browser worked, others entered the first 8 characters and submitted until they can enter the 9 digits. Not experiencing this myself the others may have been simply cache related.

This is the working activation screen @ /activate
![Activation screen](https://i.imgur.com/7TWabOX.png)


YouTube's own service requires the 9 digits code
![YouTube for TV](https://i.imgur.com/n7dzuGQ.png)

**Comment by SecT0uch** [comment]
Same problem here. Using Firefox on android

**Comment by iadegesso** [comment]
> The change to 9 characters is new, the issue isn't add-on related. Activation has worked every time for me, another report using a different browser worked, others entered the first 8 characters and submitted until they can enter the 9 digits. Not experiencing this myself the others may have been simply cache related.
> 
> This is the working activation screen @ /activate
> ![Activation screen](https://camo.githubusercontent.com/383270354293a5629eef14832b6d2939eb1b9441/68747470733a2f2f692e696d6775722e636f6d2f37545761624f582e706e67)
> 
> YouTube's own service requires the 9 digits code
> ![YouTube for TV](https://camo.githubusercontent.com/67c5b2cdd65fd8becc4f7664a78a5aa8383eb8d4/68747470733a2f2f692e696d6775722e636f6d2f6e37647a7547512e706e67)

I was on Firefox (running on Gentoo amd64) using the Anonymous Navigation, so nothing related to the activation link was stored in the cache before.

The 9 digits code is asked to me at the second activation step only; the first activation step asked me the 8 digits code.

Best regards

Iade

**Comment by Celoxocis** [comment]
I'm having the same issue. It asks me the first time for a 9 digit code and the second time for a 8 digiti code.

i enter and allow both but both times its for "Youtube on TV" i have not received the "Kodi" one yet.

**Comment by anxdpanic** [comment]
@iadegesso and @SecT0uch can you try https://www.google.com/device as your activation page

@Celoxocis Would need to see a debug log showing the error your are receiving to have any idea what is happening there.

**Comment by iadegesso** [comment]
In my case I tryed again and it asked me the 8 digits code two times...

Thanks

Iade

**Comment by cas--** [comment]
> The 9 Digit code only works here: https://accounts.google.com/signin/oauth/usercode

I encountered the same issue as there does seem to be some caching not redirecting to this new URL (the old URL contains `oauth2` not `oauth`). 

Using the new URL worked for both 8 and 9 digits codes.
