### ISSUE TITLE
HDR streams not working

### ISSUE THREAD

**Issue by greystashh** [jdf76/plugin.video.youtube#577]
At first great thanks to peak3d and anxdpanic for enabling 4k content finally

I have tried the 6.4.0 and experienced an issue with HDR content. Unfortunately the add-on doesn't start these videos. Log is uploaded

Besides there is another thing to improve it: Adding vp9 enable option to add-on settings so that the videos already start in 4k. ATM you have to select it in video settings during playback first

**Comment by anxdpanic** [comment]
I'll push an alpha update likely tomorrow that will default to webm when available. auto bandwidth selection will work as expected this way, and low powered devices can choose mp4 if webm doesn't perform as well.

HDR streams seem to play here on Windows and I don't see any log?

**Comment by greystashh** [comment]
Sorry, I forgot:
https://pastebin.com/FwL58rub

**Comment by anxdpanic** [comment]
For 6.4.1~alpha 
Enable -  `Settings - MPEG-DASH - Default to WEBM adaptation set`

Will have to look into the log further but the video does play here on Windows, may need reporting to inputstream adaptive with the full log.

**Comment by greystashh** [comment]
Maybe you could report peak3d

**Comment by greystashh** [comment]
Have you uploaded the 6.4.1 alpha already? I can't find it.

Would it be possible to add an option in settings to deactivate HDR in meantime so that videos can be played?

**Comment by anxdpanic** [comment]
You'll find it through; https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

I will look at more options next chance I have, still getting set up again on a new pc

**Comment by anxdpanic** [comment]
alpha2 has an `Include VP9.2 (HDR)' setting in the MPEG-DASH category

**Comment by greystashh** [comment]
Thanks. There is another issue I have recognised with webm streams in general. The frame rate switch doesn't work immediately when the video starts but take one ms after start to get  correct hz value:
- videos in 23,97/24 start with 23.00hz
- videos in 25fps stat with 24hz
- videos in 30 fps start with 29hz
- videos in 60fps start with 59hz

There is always a lack of 1 hz whether the video starts and then switch correctly after one second.

**Comment by anxdpanic** [comment]
This is actually an issue with all mpeg-dash with the add-on. The issue is that the exact refresh rates are not provided.
See the comment here: https://github.com/jdf76/plugin.video.youtube/commit/ec4f8478f6b574484ada517ce5e74cb9957e4d25

**Comment by greystashh** [comment]
Actually this doesn't happen with mp4 material. There the video starts with correct fps rate

**Comment by greystashh** [comment]
Concerning YouTube HDR I found the reason. My device is Nvidia Shield TV which doesn't support VP9.2 and therefore no YouTube HDR. So actually you can close the issue. 
But nevertheless it would be nice if you could resolve the problem with webm streams that they get the right fps at start

**Comment by anxdpanic** [comment]
Im likely going to switch the HDR setting to default to false

**Comment by anxdpanic** [comment]
#582 is opened for refresh rate issues

**Comment by anxdpanic** [comment]
Opened #591 to make this hdr information easier to find for other shield users.
