### ISSUE TITLE
No video playing after LibreELEC update to 9.0.0

### ISSUE THREAD

**Issue by iadegesso** [jdf76/plugin.video.youtube#579]
Hi all,
after upgrading my LibreELEC setup to the 9.0.0 version, I'm not able to watch most of the videos. If I double click on the items in the search result list, only a few times the video starts playing. No error message is shown. After the double click the loading circle is shown, interrupted, then shown again and finally it stops and I get the search result list again.

I get this behaviour both with 6.3.1 and 6.4.0 versions of the add on.

Best regards

Iade

**Comment by anxdpanic** [comment]
There have been no similar reports, would need a debug log to hopefully see what is happening

**Comment by iadegesso** [comment]
After a week... today it seems that this problem desapeared.
I will test it for a long while.

Iade

**Comment by anxdpanic** [comment]
Please reopen with log if the issue returns.
