### ISSUE TITLE
Unable to watch purchased movies

### ISSUE THREAD

**Issue by sebnutt** [jdf76/plugin.video.youtube#580]
Dear all,

After installing youtube add-on from Kodi repo on KODI 18.1 for Android TV on Xiaomi Mi Box S, I can navigate the folders and even get my purchased movies listed.

The issue is that when I try to watch any of them, nothing happens.

No issue while watching unDRMed movies (trailers, etc...). No issue within the youtube native app to watch purchased movies either.

Youtube and InputStream.adaptative add-ons configured as expected.

Thanks for support.

**Comment by sebnutt** [comment]
Just tried installing KODI 18.1 on my Samsung Gran Prime => exact same behavior
- KODI installed from Play store
- Youtube add-on installed from kodi repo

**Comment by anxdpanic** [comment]
Was working on the addon when your initial comment came in, and was able to fix up Purchases.
Can you try 6.4.1~alpha2 from: https://github.com/jdf76/repository/tree/master/testing/official/zips/plugin.video.youtube

**Comment by sebnutt** [comment]
I'll try as soon as i'm back home and met toi know. Co i need To perform a factory reset or reinstall if the addon would be enough ?

**Comment by anxdpanic** [comment]
All that's required is to install the alpha from zip. If it doesn't work straight away just try restarting Kodi at that point.

**Comment by sebnutt** [comment]
I can't unfortunately install 6.4.1~alpha2 from the zip.
I got a pop-up saying "installation failed"

**Comment by anxdpanic** [comment]
I just got that too, second try it installed. Everything is fine with the zip, something was likely in use on my end.
I would need a debug log to capturing the installation failed to hopefully see what might be causing it in your case.

**Comment by anxdpanic** [comment]
Have you since been able to update and resolve the issue?

**Comment by sebnutt** [comment]
Sorry for this late reply. Fortunately, installing Alpha 4.zip youtube add-on sloved the issue for some purchased movies on Youtube. Grateful hugs !
Still have to identify why not all movies work are streaming...

**Comment by anxdpanic** [comment]
For the movies that aren't working, do they play the first ~10 seconds?

**Comment by sebnutt** [comment]
Some play, others don't even start.

**Comment by sebnutt** [comment]
Nothing typical noticed

**Comment by anxdpanic** [comment]
If you can get a debug log trying to play the ones that fail, I'd be happy to take a look. I only a few purchases purely for test purposes. 

For the ones that start to play, if you change the Stream Selection to Manual in the InputStream Adaptive settings you'll be able to select a lower resolution stream that will work. 

YouTube doesn't provide the resolutions you have access too, only a general hint(which isn't perfect) and they provide the urls to all resolutions even ones you don't have access to, which causes that issue.

**Comment by sebnutt** [comment]
I'll try manually and let you know.

**Comment by nonobio** [comment]
Hello,
I just discover that i could maybe watch my YouTube's purchased or rented movies on Kodi, great !! Thanks for your work :)
So i tried.
First i didn't see the "My purchases" folder. I enable MPEG DASH to display it. Is that normal ? What's the aim of MPEG DASH exactly ?
Then i tried to watch my purchased movie : it didn't work : i updated manually the addon to 6.4.1 beta 1 and playback started :) , but it hang after 10 seconds. I saw info in changelog about that so : i changed input stream adaptive setting "stream selection" from Auto to Manual : it works with some flux but not all of them (HD flux doesn't work :(  )...and : i have no sound at all whatever the flux.
I also see that mpeg dash vod require proxy to be set at http tab setting, but i don't know what to enter here.
Is there any instructions i miss ? Where are explanations about mpeg dash, prox, input stream setting, etc. ?

**Comment by anxdpanic** [comment]
mpeg-dash is 'Dynamic Adaptive Streaming over HTTP'
InputStream Adaptive (the binary add-on required to use mpeg-dash) also supports DRM (ie. Widevine) which is required for purchased content. 
The proxy should work with default settings, and sounds like it is working in your case. 
When you purchase a video from YouTube you only have rights to certain qualities, so not all qualities will work. As mentioned in the comment above, the add-on only has a hint of what qualities you can play which results in the 10 second issue for some videos. As you're already doing you'd have to use manual selection and choose the highest functioning resolution in those cases.

Wish there was a better solution, hopefully this will improve in the future.

**Comment by nonobio** [comment]
Hi,
Thanks for all your explanations :)

To be sure : i need "InputStream Adaptive" to watch purchased content **"AND"** MPEG-DASH feature enable in YouTube addon setting (for me, if not enable i don't have "My purchase" folder) ?

About my sound issue (" i have no sound at all whatever the flux"), do you have any idea ? maybe it is better to open a new issue...

**Comment by anxdpanic** [comment]
Closed by 37caf0db7f8ac5ab40fc6e083bfa331d566e2839
