### ISSUE TITLE
Start video with specified seektime

### ISSUE THREAD

**Issue by tobias-d-oe** [jdf76/plugin.video.youtube#593]
Hi,

is there a way to set a parameter to the plugin start, to start a video with a specific seek time?
If it isn't, can you please add a parameter to accomplish this?
For example something like this:
-  plugin://plugin.video.youtube/?action=play_video&videoid=$VIDEOID&seek=00:15:00
   (this example should starts the video with id $VIDEOID at position "15 min") 

or

- plugin://plugin.video.youtube/?action=play_video&videoid=$VIDEOID&seek=900
   (this example should starts the video with id $VIDEOID at position "900 sec") 

Thanks
  Tobias

**Comment by anxdpanic** [comment]
1096ab937962494926294a59f6bfe06c27fb1b50 adds `plugin://plugin.video.youtube/?action=play_video&videoid=$VIDEOID&seek=900` 
Will be included in the beta2 bump coming tomorrow/monday.

**Comment by tobias-d-oe** [comment]
Hi there,

I cannot get it managed start a video at a specific time with the new seek parameter, it always starts at the beginning.
Can you please point me to my mistake?

I've tried with:
`
url = "plugin://plugin.video.youtube/play/?video_id=%s&seek=%s" % (vid,seek)
listitem = ListItem(path=url)
listitem.setInfo(type="Video", infoLabels={"mediatype": "movie", "title": "LiveTV"})
Player().play(url, listitem)
`

also tried:

`
url = "plugin://plugin.video.youtube/play/?video_id=%s&seek=%s" % (vid,seek)
xbmc.executebuiltin('PlayMedia("{url}")'.format(url=url))
`

In the kodi log I get the following:
`
2019-03-25 10:00:13.324 T:985658096  NOTICE: [plugin.video.youtube] Running: YouTube (6.4.0) on Leia (Kodi-18.2) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'ltStPUUT_1k', 'seek': '1005'}
2019-03-25 10:00:14.650 T:1918149216  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.youtube/play/?video_id=ltStPUUT_1k&seek=1005
`

But the video starts at the beginning (seek=0).

Thanks in advance
Tobias

**Comment by anxdpanic** [comment]
It's not available in 6.4.0, you will need 6.4.1~beta2 from https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

**Comment by anxdpanic** [comment]
Just a heads up as well, 
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_resolver.py
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_requests.py

Those can be used for YouTube requests, then allowing you to handle the processing and add-on/playback side of things.

**Comment by anxdpanic** [comment]
Closed by 1096ab937962494926294a59f6bfe06c27fb1b50
