### ISSUE TITLE
Error...."Exception in ContentProvider....Could not parse iso 8601 timestamp"

### ISSUE THREAD

**Issue by xalaros** [jdf76/plugin.video.youtube#599]
Fresh install Kodi 18.1 on Android box and every time I try to go to 2nd page of every list of videos for example "Liked videos" or "My Favorites" on YouTube v6.4.0 appears error...."Exception in ContentProvider....Could not parse iso 8601 timestamp".
I have log-in and configure it MPEG-DASH with API Keys.
Any idea how to resolve it?
https://paste.kodi.tv/avipubovon

**Comment by anxdpanic** [comment]
Closed by d7236e6a9e28bc0063b9bedd77724c329f499673
