### ISSUE TITLE
Selected quality is not used for the first time

### ISSUE THREAD

**Issue by martinrotter** [jdf76/plugin.video.youtube#606]
1. Open addon.
2. Select some video.
3. Select 1080p video quality.
4. **Video starts playing but some much lower 480p quality is shown instead.**
5. Go to video options and change to 1080p and now video switches to correct quality.

**Comment by anxdpanic** [comment]
Using MPEG-DASH/InputStream Adaptive with Stream Selection set to Manual?
If so, that is the expected behavior. 
Otherwise, please provide a debug log reproducing the issue. https://kodi.wiki/view/Log_file

**Comment by anxdpanic** [comment]
Please re-open the issue with a debug log
