### ISSUE TITLE
Update Korean translation

### ISSUE THREAD

**Issue by parkmino** [jdf76/plugin.video.youtube#617]
It has been a while and several new translations are added as attached.

[strings.po.txt](https://github.com/jdf76/plugin.video.youtube/files/3297538/strings.po.txt)

**Comment by anxdpanic** [comment]
Thank you. That was some good timing, I had just opened everything to bump to beta1 only 10 seconds before the issue came through.
The translations are added with f63a606, I amended the commit so you were the author.
