### ISSUE TITLE
Breaks on version 6.4.1 with this video link

### ISSUE THREAD

**Issue by hiren1771** [jdf76/plugin.video.youtube#629]
https://www.youtube.com/watch?v=KMqI0B8fMeU

signature function not found error.

Error in:
plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py
line 60.

**Comment by anxdpanic** [comment]
6.5.0~beta3 already includes the fix
Can find it @ https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions
