### ISSUE TITLE
SD ONLY

### ISSUE THREAD

**Issue by TRC4** [jdf76/plugin.video.youtube#637]
Hello,
Plugin work only for SD Streams?
here i have php list generator https://demo.kodi.al/YouTube/Kodi/
all list is SD resolution, any change for HD?

![Picture_14-11-50_2019-07-11](https://user-images.githubusercontent.com/17369574/61049985-30eaa380-a3e6-11e9-8181-55f4fe41f6b8.png)
![Picture_14-12-29_2019-07-11](https://user-images.githubusercontent.com/17369574/61049986-30eaa380-a3e6-11e9-8a81-d99a300164d9.png)

**Comment by anxdpanic** [comment]
In the YouTube add-on settings, enable and configure MPEG-DASH for qualities higher than 720p. Kodi v17+ required.
