### ISSUE TITLE
problem with item data on 3rd party addons

### ISSUE THREAD

**Issue by Ackman303** [jdf76/plugin.video.youtube#642]
Hi,

I'm not sure if this is an issue or not but, I'm currently working on an addon, and it calls the youtube addon to play some videos.

The "problem" is once the video ends or once the user stops the video. Youtube addon is changing the image, the title, the duration I added to my item with the info that Youtube addon gets from Youtube... Am I right?

As I said, I'm not sure if this is really an issue, I have been checking the source code from Youtube addon to know if there are some extra param I'm missing to skip this issue, but I didn't see it.

In case that this extra param doesn't exist, can the Youtube addon team make it for the future versions?

Thanks!
And nice addon by the way :)

**Comment by Twilight0** [comment]
There are some methods to prevent this behaviour:

1. Utilize youtube.resolve method
2. Don't mark the listitem as IsPlayable and use xbmc.Player() method.
3. (Untested) use builtin PlayMedia method.

**Comment by Ackman303** [comment]
Working!
Thank you :)

**Comment by Ackman303** [comment]
Hi again,

Your solution worked for me, I just imported youtube_resolver in my addon and the resolve method worked fine.

Now I'm just reordering my addon, moving some functions into a resources folder as scripts, and the import is not working in this case.

I'm calling the scripts with: XBMC.RunScript('script_name', 'args')

How should I import in my /resources/script_name.py the youtube_resolver?

something like "from youtube import youtube_resolver"... ?

Thanks
