### ISSUE TITLE
Unable to seek any video

### ISSUE THREAD

**Issue by XxAcielxX** [jdf76/plugin.video.youtube#647]
Hello,

Using v6.5.1~alpha2 and I can't seem to seek any video either forward or backward. The Seekbar stuck at the very start, videos keep playing.

Videos have no end point time showing (total video length), only current time shows. As soon as you start a video and stop it kodi marks it as Watched.

Kindly check it please. Regards~

**Comment by anxdpanic** [comment]
Should be resolved with ~beta1 
https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

**Comment by XxAcielxX** [comment]
I confirmed that it has been fixed. Thanks @anxdpanic

**Comment by anxdpanic** [comment]
Thanks for confirming. I'm going to temporarily re-open the issue, to hopefully avoid any duplicates.

**Comment by anxdpanic** [comment]
Had to make a couple quick fixups, beta2 is now posted.

**Comment by anxdpanic** [comment]
6.5.1 is now on the Official repository, closing the issue 👍
