### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by thebpmgroup** [jdf76/plugin.video.youtube#650]
_discarded_stream['audio']['codec'] = str(stream['codecs'])

line 1027

Just started happening when trying to watch a youtube video in my subscriptions, from a youtuber I normally watch frequently.

**Comment by anxdpanic** [comment]
Can you try with 6.5.1~beta2, it's available https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

If it's still an issue, enable debug logging and reproduce the issue and provide the complete log.

**Comment by anxdpanic** [comment]
Please reopen with a debug log if you're still experiencing the issue with v6.5.1
