### ISSUE TITLE
No streams found

### ISSUE THREAD

**Issue by innerspacepilot** [jdf76/plugin.video.youtube#661]
Hello!
Latest plugin version 6.5.2~beta1 shows "No streams found" error on following video
https://www.youtube.com/watch?v=hi9rhMn6qTU

**Comment by tomatosoupcan** [comment]
Error should currently be occurring with all videos, YT made some changes that have broken many different players all at once.

**Comment by Ackman303** [comment]
Yes, I'm currently using 6.5.1 version, and the same thing is happening, looks like the addon is not able to resolve the video.

**Comment by madcowchow** [comment]
yep, same problem here. using osmc on raspberry pi.

**Comment by anxdpanic** [comment]
Looking into it now, will post here when there is a new version ready

**Comment by innerspacepilot** [comment]
Latest youtube-dl (2019.09.01) is also broken.

**Comment by lorderr** [comment]
Seems that youtube-dl already has triaged the bug.
Some further reading:
https://github.com/fent/node-ytdl-core/issues/486
https://github.com/ytdl-org/youtube-dl/commit/bf1317d

**Comment by anxdpanic** [comment]
I've updated the testing repositories with 6.5.2~beta2
zips: https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions

**Comment by jonisb** [comment]
Great job, it works and thanks for the (lightning) fast fix. Apparently Youtube [changed](https://developers.google.com/youtube/v3/revision_history) the subscriber count display only, but I guess someone slipped and changed much more.

**Comment by arcaine2** [comment]
Doesn't seem to be fully fixed for me. Some videos play, other do not. No error message. Log: https://pastebin.com/FSJPJpgW

**Comment by anxdpanic** [comment]
@arcaine2 You are experiencing the issue described by #659, only the 720p mp4's are affected. Using mpeg-dash, or choosing 360p for those videos will work.

**Comment by innerspacepilot** [comment]
Seems like the issue is fixed.
Thank you

**Comment by itmitica** [comment]
The issue is current again.

**Comment by itmitica** [comment]
It's now working again...

**Comment by programmer131** [comment]
ok so it was working fine and now getting this error

**Comment by louisnichols** [comment]
Started seeing this again today. Worked fine till yesterday. Add-on version 6.8.11 running under Raspberry Pi OS, without desktop environment. Should I provide logs?

**Comment by rjousse18** [comment]
I have the same problem on pi4 LibreElec 9.2.7 (Kodi 18)

**Comment by sylvainpelissier** [comment]
Same for me since this morning: Librelec: 9.26, Kodi: 18.9 and Youtube Add-on: 6.8.11.

**Comment by nripenc** [comment]
I am getting the same error. It would be very kind of dev to fix this prob. I use tv only to watch yt thru kodi raspberry pi 2

Kodi 17.6

**Comment by ArchieMeng** [comment]
I am getting the same error as well.
Kodi version: 19.1
Youtube Addon version: 6.8.11+matrix.1
Error log: https://paste.kodi.tv/mihefafami.kodi

**Comment by zenwarr** [comment]
Same here, starting from yesterday.
Kodi 18.7, youtube addon 6.8.11
Log: https://paste.kodi.tv/hevawixuco.kodi

**Comment by zenwarr** [comment]
For anyone affected: the relevant issue in actual repository (this one is abandoned): https://github.com/anxdpanic/plugin.video.youtube/issues/129 , the bug is already fixed in 6.8.14, just update the plugin to the latest version.

**Comment by ArchieMeng** [comment]
> For anyone affected: the relevant issue in actual repository (this one is abandoned): [anxdpanic/plugin.video.youtube#129](https://github.com/anxdpanic/plugin.video.youtube/issues/129) , the bug is already fixed in 6.8.14, just update the plugin to the latest version.

Thank you. It's already fixed now.
