### ISSUE TITLE
Wrong video title

### ISSUE THREAD

**Issue by innerspacepilot** [jdf76/plugin.video.youtube#664]
Hello!
Title displayed wrong
Same plugin version on kodi 17.6 and 18.4
Here is the log file and a screenshot:
*log removed
![Screenshot_2019-09-12_20-33-08](https://user-images.githubusercontent.com/42217618/64806874-c1876080-d59c-11e9-9d7b-c7c1a82d1686.png)

**Comment by innerspacepilot** [comment]
Could that be that title is taken from stream's metadata?

**Comment by anxdpanic** [comment]
it's getting taken from the same place as when I try to reproduce and I get a different encoding for some reason. can you paste bin a debug log including kodi starting up, will give me more information to try to reproduce the environment.

**Comment by innerspacepilot** [comment]
full log
https://pastebin.com/whx41c0v

**Comment by anxdpanic** [comment]
Can you try 6.5.2~beta3 @ https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions This should fix the issue, thank you for the information needed.

**Comment by innerspacepilot** [comment]
Yes. It is fixed now
Thanks.
