### ISSUE TITLE
Video don't play and can't choose different format

### ISSUE THREAD

**Issue by jonisb** [jdf76/plugin.video.youtube#674]
The plugin can't play this video: https://www.youtube.com/watch?v=PP0mNCYcmuI
I don't get the formats list if that option is activated.
When trying to play it on Youtubes website it gives an error,

youtube-dl -F gives me:
```
[youtube] PP0mNCYcmuI: Downloading webpage
[youtube] PP0mNCYcmuI: Downloading video info webpage
[info] Available formats for PP0mNCYcmuI:
format code  extension  resolution note
249          webm       audio only tiny   58k , opus @ 50k (48000Hz), 7.85MiB
250          webm       audio only tiny   73k , opus @ 70k (48000Hz), 9.87MiB
251          webm       audio only tiny  141k , opus @160k (48000Hz), 18.82MiB
43           webm       640x360    360p , vp8.0, vorbis@128k, 102.75MiB
18           mp4        640x360    360p  513k , avc1.42001E, mp4a.40.2@ 96k (44100Hz), 76.64MiB
22           mp4        1280x720   720p  656k , avc1.64001F, mp4a.40.2@192k (44100Hz) (best)
```
"22" gives a 503 error:
`[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10)...`
Both "18" and "43" works to download.

Log: https://paste.kodi.tv/bedufusuco.kodi

**Comment by jonisb** [comment]
Another video: https://www.youtube.com/watch?v=O2JWYKO-bk0
This one works via Youtube website.
But it don't work via plugin and I can't choose format.

Log: https://paste.kodi.tv/afakodanek.kodi

**Comment by anxdpanic** [comment]
are you able to test the current master branch? 
#675 should resolve the issue, though for https://www.youtube.com/watch?v=PP0mNCYcmuI the 720p stream crashes Kodi and doesn't seem to work on the web either.

**Comment by jonisb** [comment]
Nice, master branch seems to work, thanks.
720p on that video seems to have been broken for several months based on the Youtube comments.

**Comment by anxdpanic** [comment]
I've added #677 for the context menu addition. Working on a larger update, will hopefully have this included.

**Comment by jonisb** [comment]
Cool, thanks.

**Comment by anxdpanic** [comment]
added in #724

**Comment by jonisb** [comment]
Thanks, seems to work great.

I've had to rebuild/upgrade my PC, and I'm taking my sweet fucking time 😞 so I didn't see this before.
