### ISSUE TITLE
Channel listing is refreshed on every action

### ISSUE THREAD

**Issue by chpasha** [jdf76/plugin.video.youtube#688]
This issue happens to me since update to kodi 18.5 so it is possible that something has changed in it recently. When opening video list from youtube channel, actions like watching video or marking it as watched causes the whole channel list to reload, every time. I have a weak internet connection on one of my media devices so using this plugin become a huge pain since after every watched 30sek. video I wait another 30 for the list to needlessly reload. Here are the log entries that follow every load attempt

```
2019-11-30 17:34:49.385 T:1915680304 ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-11-30 17:34:49.404 T:1491055328 NOTICE: [plugin.video.youtube] Running: YouTube (6.5.2) on Leia (Kodi-18.5) with Python 2.7.13
Path: /channel/UCFzJjgVicCtFxJ5B0P_ei8A/
Params: {}
```

**Comment by anxdpanic** [comment]
The lists are cached, so the internet shouldn't be a big concern on refreshes.
The snippet you provided doesn't contain any usable information, need a complete debug log showing the issue. https://kodi.wiki/view/Log_file

**Comment by chpasha** [comment]
>The snippet you provided doesn't contain any usable information, need a complete debug log

will be done, thanks

**Comment by chpasha** [comment]
Here you go with debug log https://pastebin.com/KVnSPVYL

Looks to me like the plugin do tries to cache data but at the next moment it is empty again  - you can see this after I marked item as watched, look for the line in the log
`2019-12-01 11:40:10.320 T:1404039904   DEBUG: Mysql execute: insert into files `
after that plugin repeats all steps that it did before - loading list of channels, trying to cache them. and so on and so on (I didn't paste the rest of the log but it looks identical, after marking any item watched the load process repeats)

**Comment by chpasha** [comment]
I've decided to remove plugin completely deleting all data and after clean installation the problems seems to be gone now, so I can close the ticket I think
