### ISSUE TITLE
Disable playlist, search and live

### ISSUE THREAD

**Issue by csvke** [jdf76/plugin.video.youtube#697]
I want to disable [back], [playlist], [search], [live] button, preferably individually per favourite (I have add a number of Youtube channel in my favourite), but I don't mind disabling that universally.

![Screenshot 2019-12-06 at 12 10 20 AM](https://user-images.githubusercontent.com/4078574/70252958-3d203480-17bd-11ea-83cd-c840276b9dd1.png)

I found that there was a mentioned in the changelog.txt that
_[add] add support for &hide_folders=true parameter in search query urls
        - when added to the url it will hide the Playlists, Channels, and Live folders_
[Here](https://github.com/jdf76/plugin.video.youtube/blob/master/changelog.txt#L50)
But I don't know where to modify the search query url in the code base.

Thanks.

**Comment by anxdpanic** [comment]
this is now possible with current master branch, was added in #720
