### ISSUE TITLE
Sign In not possible

### ISSUE THREAD

**Issue by joecksma** [jdf76/plugin.video.youtube#698]
When attempting to sign in, i get the following error message on the second sign in (Youtube Plugin for Kodi #1):

> Signing in with Google is temporarily disabled for this app
> The use of Google Log-in has not yet been confirmed for this app

I tried this with versions 6.5.2, 6.5.1 and 6.4.0 on Kodi 18.5

**Comment by Kirottu** [comment]
I second this, the Youtube on TV "device" works no problem, but the Youtube plugin for Kodi #1 gives the error mentioned above.

**Comment by anxdpanic** [comment]
Using your own API keys should resolve this issue, https://forum.kodi.tv/showthread.php?tid=348464&pid=2681560#pid2681560

**Comment by anxdpanic** [comment]
I've opened #700 for other users that experience this
