### ISSUE TITLE
URL mentioned on GitHub points to non-existing forum

### ISSUE THREAD

**Issue by PanderMusubi** [jdf76/plugin.video.youtube#706]
URL mentioned on GitHub points to non-existing forum

https://forum.kodi.tv/showthread.php?tid=325740

**Comment by anxdpanic** [comment]
@jdf76 Can you update the repository description with the new url, https://forum.kodi.tv/showthread.php?tid=348464 I'm not able to edit that myself.

**Comment by jdf76** [comment]
i updated the main page, is it missing anywheres else?

Jeff

**Comment by PanderMusubi** [comment]
Not that I know of, also Googled the link. Thanks for fixing this.
