### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Maranobarbaro** [jdf76/plugin.video.youtube#708]
Sorry guys anyone can help me?
This appear only on certain videos...
![IMG_20191219_195128](https://user-images.githubusercontent.com/47886304/71201241-e8d78300-2299-11ea-8b86-51dc08f421bd.jpg)
![IMG_20191219_195146](https://user-images.githubusercontent.com/47886304/71201242-e8d78300-2299-11ea-98ef-3fd2bf736898.jpg)
![IMG_20191219_195139](https://user-images.githubusercontent.com/47886304/71201243-e8d78300-2299-11ea-8ff6-221d3cf1d7bf.jpg)

**Comment by anxdpanic** [comment]
Update to the lastest version of the add-on. If that doesn't resolve the issue, please re-open the issue with a complete debug log. https://kodi.wiki/view/Log_file
