### ISSUE TITLE
Enter Playlist ID in Search Should show Playlist in Playlist Search Results

### ISSUE THREAD

**Issue by Grauen** [jdf76/plugin.video.youtube#709]
I would like to add a Playlist to my favorites in Kodi but I cannot find the Playlist in the YouTube plugin search results, even though I enter the correct keywords.

It would be great if you could just search for the Playlist ID like PLwu7U48UrpyX-SYhoY8KG7ZUeQ0LcyFRe and then the Playlist will be shown in the Playlist result folder.

**Comment by Grauen** [comment]
Open Youtube App -> New Search -> Enter Playlist ID -> Open Playlist in Result-Response 

will produce this output:

`rep -iE "plugin.video.youtube" kodi.log | grep -i -E "v3 request" | cat
13:01:01.981 T:1609036704   DEBUG: [plugin.video.youtube] [data] v3 request: |GET| path: |search| params: |{'relevanceLanguage': 'en_US', 'regionCode': 'US', 'maxResults': '50', 'q': 'PLwu7U48UrpyX-SYhoY8KG7ZUeQ0LcyFRe', 'safeSearch': 'none', 'part': 'snippet', 'hl': 'en_US', 'type': 'video', 'order': 'relevance'}| post_data: |None|
13:01:08.007 T:1609036704   DEBUG: [plugin.video.youtube] [data] v3 request: |GET| path: |search| params: |{'relevanceLanguage': 'en_US', 'regionCode': 'US', 'maxResults': '50', 'q': 'PLwu7U48UrpyX-SYhoY8KG7ZUeQ0LcyFRe', 'safeSearch': 'none', 'part': 'snippet', 'hl': 'en_US', 'type': 'playlist', 'order': 'relevance'}| post_data: |None|`

Indeed, repeating this search in the youtube api explorer will return an empty result:
https://developers.google.com/youtube/v3/docs/search/list?apix_params=%7B%22part%22%3A%22snippet%22%2C%22q%22%3A%22PLwu7U48UrpyX-SYhoY8KG7ZUeQ0LcyFRe%22%2C%22type%22%3A%22playlist%22%7D

But if you search for a playlist by using the `v3/playlists` endpoint, youtube will return the correct playlist

`curl \
  'https://www.googleapis.com/youtube/v3/playlists?part=snippet&id=PLwu7U48UrpyX-SYhoY8KG7ZUeQ0LcyFRe&key=[YOUR_API_KEY]' \
  --header 'Authorization: Bearer [YOUR_ACCESS_TOKEN]' \
  --header 'Accept: application/json' \
  --compressed`


So if you click playlists there should be 2 api calls -> one that just searches for playlists by searchquery using the `search`-endpoint and one trying to resolve a playlist by the ID using the `playlists` parameter.

**Comment by anxdpanic** [comment]
This will be fixed in the next dev(6.5.3~alpha2+) and release versions, added by #725

**Comment by anxdpanic** [comment]
The testing repositories have 6.5.3~beta1 with this added, zip is also found https://github.com/jdf76/plugin.video.youtube/releases/tag/6.5.3-dev
