### ISSUE TITLE
Debug logs showing not-my-keys being used for device auth

### ISSUE THREAD

**Issue by cricalix** [jdf76/plugin.video.youtube#711]
This might be related to #700 , or it might not.

I followed the steps in https://forum.kodi.tv/showthread.php?tid=348464 to generate my own API key, OAuth Client ID (which has a .apps.googleusercontent.com suffix), and OAuth secret. Turned on the web server functionality so I could paste them in. Verified the JSON and XML files both have the same set of three strings, restarted the NUC that's running Kodi.

When I attempt to sign in via the plugin, I get the first screen saying "go to google.com/device", but there's no activation code displayed. I enabled debug logging in Kodi, and I'm seeing the following debug logs:

DEBUG: [plugin.video.youtube] Requesting access token: Config: |YouTube-TV| Client id [:5]: |86155| Client secret [:5]: |SboVh|
DEBUG: [plugin.video.youtube] Requesting access token: |{"error_description": "Precondition Failed", "error": "authorization_pending"}|
DEBUG: [plugin.video.youtube] YouTube-TV Login: Access Token |False| Refresh Token |False| Expires |0|

Those client strings are not from the strings I entered into the API page, nor what's recorded on disk. Skimming the code, it looks like the client log line comes from https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/client/login_client.py#L179

Looking in the helpers code, it seems like the code is going down the hard-coded route, not the "keys are provided" route.

Version is 6.5.2.

What have I missed in setting this up?

**Comment by cricalix** [comment]
Should also mention that I think the code is hitting an exception raise in login_client, but the UI doesn't get the message, and it just sits there waiting for something to happen.

**Comment by anxdpanic** [comment]
The YouTube-TV keys are hardcoded and are used in the first activation. Your keys won't be used until the second activation.
It is sending a request to youtube to verify authorization every so often and waiting a set amount of time overall per activation.

Would need the complete log with debug logging activated to tell more.

**Comment by cricalix** [comment]
Thanks for the prompt response. grep youtube kodi.log sufficient, or will there be non-tagged lines that are useful? Github gist or some other way?

**Comment by anxdpanic** [comment]
Complete log for context, https://kodi.wiki/view/Log_file
Also just double checked and there is a code showing for the first activation here.

**Comment by cricalix** [comment]
https://paste.kodi.tv/asuretowez.kodi

Snipped to debug logging enabled, and an attempt to invoke the Sign In process, and snipped when I hit cancel after waiting about 2 minutes.

**Comment by cricalix** [comment]
Found the problem - skin Ace2 doesn't support showing the code. Sorry for the false report; changed back to default skin to troubleshoot something else, and this plugin worked. I'll file a bug to the Ace2 skin author.
