### ISSUE TITLE
remove from watch later in item menu?

### ISSUE THREAD

**Issue by hiren1771** [jdf76/plugin.video.youtube#728]
for some reason remove from watch later setting does not work for me. Any chance one can get the menu on an item (where there is things like, resume from time, audio only etc etc,) to show a "remove from watch later" option to remove one item from watch later please?

**Comment by anxdpanic** [comment]
This a known issue, remove from watch later doesn't work by default due to YouTube's api.
To fix this you should be able to go to `Settings - Folders - Retrieve Watch Later playlist id` and follow the on screen instructions.

**Comment by hiren1771** [comment]
Retrieve Watch Later playlist id - just tells me succeeded, in a pop up box.
I check auto remove setting is still on.
I watch a video in water later, and then another, both still stay in watch later. They did not get removed.

**Comment by anxdpanic** [comment]
It's working here, but caching was still causing it to show. Will try to look into that before 6.6.0. 
Is the `Remove` context menu available when browsing your Watch Later list? (that would mean it should be working)
If still an issue, please reopen this with a debug log

**Comment by hiren1771** [comment]
There is no "remove" menu for items in my watch later list.
It doesn't remove for me, because afterward going into YT app, it still shows in watch later list.
I looked at the logs there is nothing obvious I can see.

**Comment by anxdpanic** [comment]
When you get succeeded from retrieving the playlist this should be added to access_manager.json, and if that is available removal should be possible. You can check that file at [userdata](https://kodi.wiki/view/Userdata)/addon_data/plugin.video.youtube/access_manager.json

If you see `"watch_later": " WL"` that means it wasn't updated there, when working it will be `"watch_later": "<playlist id>"` which should start with `PL`.

**Comment by hiren1771** [comment]
Ah, works now. It was WL, I ran it again and rebooted, then it's PL. Now I
see remove in the menu. Thank you so much for your help. Much appreciated.

**Comment by DjDiabolik** [comment]
Issue also resolved for me.
