### ISSUE TITLE
Youtube plugin as of right now (27/1/20) is UNUSABLE

### ISSUE THREAD

**Issue by Flubbex** [jdf76/plugin.video.youtube#730]
Youtube updated something and it broke your plugin considerably. Almost no videos play and the ones that do have no recognized sound stream. Is this project dead enough that I can fork it and make a proper youtube plugin?

**Comment by anxdpanic** [comment]
There has been 7 additions in the last 4 days, including a fix for the issue you're talking about. So in short, this project is still in active development.

Here is the pinned issue regarding video playback errors. https://github.com/jdf76/plugin.video.youtube/issues/719
There is a zip for the current beta version that includes the fix.

**Comment by anxdpanic** [comment]
If that doesn't resolve your issue, please open a new issue specific to your symptoms and include a complete debug log.

**Comment by anxdpanic** [comment]
You are still welcome to create an alternative, but make sure to change the add-on id(not plugin.video.youtube), name etc.
