### ISSUE TITLE
Search and 1080p not always work

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#737]
_Translator:_
1. Search sometimes doesn't work.
2. Some movies run at the lowest resolution (360p), even though it is 720p when selecting quality manually. 1080p quality is not available, but on the PC is 1080p.

_RPi3, Kodi 18.5, YT 6.6.0, LibreELEC 9.2.0_

**Comment by anxdpanic** [comment]
Will look into the search issue more.
For video quality >360-720 mpeg-dash is required, 
Enable Settings - MPEG-DASH - Use MPEG-DASH
Enable Settings - MPEG-DASH - Use for videos
Configure Settings - MPEG-DASH - Video quality, etc.

If that's not the issue, open this or a new issue with the required debug logs.
