### ISSUE TITLE
YouTube API alternatives

### ISSUE THREAD

**Issue by kekukui** [jdf76/plugin.video.youtube#739]
Since YouTube has a habit of restricting API usage, and this presents many problems for the end user,* I want to present some alternatives for your consideration:

There is an open source YouTube client written in Java which does not depend on the YouTube API - it appears to YouTube as a browser.  This eliminates the need for end users to manually create a developer account / API key and configure the application to use it.

https://github.com/TeamNewPipe/NewPipeExtractor

It may be feasible to run this Java-based YouTube client on embedded Linux ARM platforms: many ARM CPU's have hardware support for executing Java bytecode (denoted by a "J" appended to the CPU name, except for post-v5 cores where it is required.)

https://en.wikipedia.org/wiki/Jazelle

On platforms lacking hardware support for Java bytecode, you could avoid installing the Java Runtime Environment with something like this:

**Java to C++ converter**
https://www.tangiblesoftwaresolutions.com/product_details/java_to_cplusplus_converter_details.html

**Java to Python converter**
https://github.com/natural/java2python
https://pypi.org/project/java2python

* Related issue: https://github.com/jdf76/plugin.video.youtube/issues/736

**Comment by anxdpanic** [comment]
This would be better as a NewPipe add-on request on the forum.

**Comment by kekukui** [comment]
Hmm... yes, maybe we need a dedicated YouTube resolver

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_resolver.py
That has been working this whole time for add-ons that use it. 

And in the dev and next versions `plugin://plugin.video.youtube/play/video_id=' urls won't require API, fixing anything that uses those urls without requiring api keys.
See: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.0-dev

**Comment by kekukui** [comment]
Thanks, this is helpful - I did not know there is a repo for alpha & beta versions.  You might want to mention this in the add-ons info panel, or in the list of links here: https://github.com/jdf76/plugin.video.youtube

**Comment by christophehenry** [comment]
So, has this been solved on some dev branch? Is this testable? I see this issue is closed.

**Comment by anxdpanic** [comment]
Is what testable?
A request for an alternate add-on is not an issue with this add-on. A request for alternative belongs on the forum, in it's own thread. ie. request a newpipe add-on.

If you mean playback without API keys, it's in the official release. Browsing to videos doesn't work without API however.

**Comment by christophehenry** [comment]
> If you mean playback without API keys

Yes. That's what I meant. I though this issue was about replacing API usage by NewPipeExtractor.
