### ISSUE TITLE
R.I.P. plugin.video.youtube

### ISSUE THREAD

**Issue by easylistbrasil** [jdf76/plugin.video.youtube#741]
it is now necessary to pay to have a developer account to release the access token.

R.I.P.

**Comment by anxdpanic** [comment]
I just created another set of keys for free without issue. The latest alpha playback works regardless of api. just no navigating the app without keys.

**Comment by anxdpanic** [comment]
Please open a specific issue, with information like screenshots and steps to get where you're seeing payment is required.
