### ISSUE TITLE
youtube trailer playback not started from any plugin

### ISSUE THREAD

**Issue by elpi07** [jdf76/plugin.video.youtube#760]
I have installed your last development version of the youtube plugin (6.7 beta1) but I cannot play any trailer video from any other plugin. When I click on it nothing happens. No error message no playback. I have seen in the messages from others the same problem, but I did not find any solutions till now. 
I will attach my log, please give me an advice what to do! 
Thanks.
[log.txt](https://github.com/jdf76/plugin.video.youtube/files/4329081/log.txt)

**Comment by anxdpanic** [comment]
There are banned add-ons installed, on top of that I don't even see the YouTube add-on called in that snippet.

Please re-open with a complete debug log with no banned add-ons.

**Comment by elpi07** [comment]
I have cleaned the plugins.  Only the Movishark and Youtube addons are installed. During the log session, I have 3 times tried to open the trailer without any success. No error, no playback. 
Is any problem in my youtube addon settings? Earlier it was working without any problem.

[kodi.log](https://github.com/jdf76/plugin.video.youtube/files/4333920/kodi.log)
