### ISSUE TITLE
Extra data in player_config

### ISSUE THREAD

**Issue by voyman** [jdf76/plugin.video.youtube#762]
First of all, thank you for this great addon!
For some reason I was unable to play any videos with it starting two days ago, when seemingly nothing had changed on my end. First thing I tried was install 6.7.0-beta1 to see if my issue was fixed there but no luck. Next I tried complete reset and reinstall (including new keys just to be sure) but that also didn´t help. So today I bit the bullet and started going through logs and code.
Here is the error that I kept getting:
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Extra data: line 1 column 72840 - line 1 column 86724 (char 72839 - 86723)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 750, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 50, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 712, in _method_get_video_info
                                                player_config = self.get_player_config(html)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 573, in get_player_config
                                                player_config.update(json.loads(_player_config))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
                                            ValueError: Extra data: line 1 column 72840 - line 1 column 86724 (char 72839 - 86723)
                                            -->End of Python script error report<--
`
Not wanting to spend too much time on it and frankly not really understanding it without spending even more time I decided to try the brute-force approach: commenting the offending block (line 572-575 in helper/video_info.py) out and hope for the best.
Lo and behold this restored playback functionality for me, with no visible issues that I can find.

Maybe you can have a look at what changed (on Google‘s end) and come up with a proper fix?
One interesting tidbit that I noticed during testing: I only had this issue when signed in, playback was ok from search results when not authenticated.

**Comment by anxdpanic** [comment]
I am unable to reproduce this. So I need some help in the form of a file dump if you're up for it.

Using [plugin.video.youtube-6.7.0.0.01~beta1.zip](https://github.com/jdf76/plugin.video.youtube/files/4363505/plugin.video.youtube-6.7.0.0.01.beta1.zip) the video should play but this version will create a dump of the file I need to fix the issue properly. 
The file I need is [userdata](https://kodi.wiki/view/Userdata)/addon_data/plugin.video.youtube/\<video id\>.html

Note don't use this version more than a couple times, as it will generate new files every time you play something. Current master should Bandaid the issue though.

**Comment by voyman** [comment]
I've generated 3 of those dumps but upon having a peek in there I saw they contain a bunch of oauth tokens so I wouldn't want to just post them willy-nilly. At the same time I realize that trying to sanitize the dump might render it useless, especially if for whatever reason the error comes form the parts I strip out.

So I thought to try my hand at debugging it myself and quickly found the source of the problem with my dumps: they contain an additional two objects between the two delimiters used to read the config object:
```javascript
ytplayer.config = {
    "attrs": {
        "id": "movie_player"
    },
    "assets": {
        "js": "\/s\/player\/9b926fb0\/player_ias.vflset\/en_US\/base.js",
        "css": "\/s\/player\/9b926fb0\/www-player-webp.css"
    },
    "args": {
        "hl": "en_US",
        "fexp": "<snip>",
        "cbr": "Chrome",
        "enablejsapi": "1",
        "innertube_api_version": "v1",
        "cbrver": "53.0.2785.143",
        "csi_page_type": "watch",
        "host_language": "en",
        "enablecsi": "1",
        "transparent_background": "1",
        "fflags": "<snip>",
        "loaderUrl": "<snip>",
        "cr": "US",
        "cver": "2.20200319.09.00",
        "ps": "desktop-polymer",
        "gapi_hint_params": "<snip>",
        "innertube_context_client_version": "2.20200319.09.00",
        "external_fullscreen": true,
        "user_display_image": "<snip>",
        "watermark": "<snip>",
        "vss_host": "s.youtube.com",
        "cos": "Windows",
        "user_display_name": "<snip>",
        "innertube_api_key": "<snip>",
        "c": "WEB",
        "show_miniplayer_button": "1",
        "player_response": "<snip>",
        "cosver": "10.0",
        "use_miniplayer_ui": "1",
        "use_fast_sizing_on_watch_default": false
    }
};
ytplayer.web_player_context_config = {
    "transparentBackground": true,
    "useFastSizingOnWatchDefault": false,
    "showMiniplayerButton": true,
    "externalFullscreen": true,
    "showMiniplayerUiWhenMinimized": true,
    "rootElementId": "movie_player",
    "jsUrl": "/s/player/9b926fb0/player_ias.vflset/en_US/base.js",
    "cssUrl": "/s/player/9b926fb0/www-player-webp.css",
    "contextId": "WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_WATCH",
    "eventLabel": "detailpage",
    "contentRegion": "US",
    "hl": "en_US",
    "hostLanguage": "en",
    "playerStyle": "desktop-polymer",
    "innertubeApiKey": "<snip>",
    "innertubeApiVersion": "v1",
    "innertubeContextClientVersion": "2.20200319.09.00",
    "device": {
        "browser": "Chrome",
        "browserVersion": "53.0.2785.143",
        "os": "Windows",
        "osVersion": "10.0",
        "interfaceName": "WEB",
        "interfaceVersion": "2.20200319.09.00"
    },
    "serializedExperimentIds": "<snip>",
    "serializedExperimentFlags": "<snip>"
};
(function playerBootstrap() {
    var createPlayer = yt && yt.player && yt.player.Application && (yt.player.Application.createAlternate || yt.player.Application.create);
    if (createPlayer) {
        createPlayer("player-api", ytplayer.config, ytplayer.web_player_context_config);
        ytplayer.config.loaded = true;
    }
}
    ());
ytplayer.load = function () {
    throw new Error('Unexpected call to ytplayer.load.');
};
```
(I snip'd the long or sensitive stuff for clarity).

Hopefully this helps, and thanks again for your efforts.

**Comment by anxdpanic** [comment]
Thanks! That hopefully solved the problem. Can you try out 
[plugin.video.youtube-6.7.0.0.02~beta1.zip](https://github.com/jdf76/plugin.video.youtube/files/4364470/plugin.video.youtube-6.7.0.0.02.beta1.zip)

If it worked, you should see `DEBUG: [plugin.video.youtube] Found valid player config |True|` slightly before playback.

**Comment by voyman** [comment]
Yep, that did the trick, got the log entry and playback works as usual - good job mate!

**Comment by anxdpanic** [comment]
Great! Thank you again for your help with this 👍
