### ISSUE TITLE
API Page is disabled

### ISSUE THREAD

**Issue by krlosgilson** [jdf76/plugin.video.youtube#771]
After performing the process of creating the keys, I'm not able to configure the Addon because the API page is disabled and I didn't find any option to activate it.

![image](https://user-images.githubusercontent.com/24833043/77836889-0dfd4c80-7139-11ea-8224-8d20bf7ca642.png)

**Comment by anxdpanic** [comment]
You should be able to scroll down that list, there are categories below API as well.
