### ISSUE TITLE
Add support for using only Invidious API.

### ISSUE THREAD

**Issue by roket1428** [jdf76/plugin.video.youtube#775]
Some people might prefer not using their own API keys or even worse don't know how to do it. For that reason, a new project or direct embedded support for Invidious API should be added.

**Comment by roket1428** [comment]
For basic usability, not implementing log in functionality for now is very good choice. ^.^

**Comment by Perflyst** [comment]
Someone else created a new plugin: https://github.com/TheAssassin/kodi-invidious-plugin

**Comment by roket1428** [comment]
> Someone else created a new plugin: https://github.com/TheAssassin/kodi-invidious-plugin

Nice. <3
