### ISSUE TITLE
Plugin crashes when selecting an autocomplete item in the search

### ISSUE THREAD

**Issue by jamieburchell** [jdf76/plugin.video.youtube#777]
When searching and entering text, various suggestions / autocompletes are shown above the text. When selecting any of these items the plugin crashes. In OSMC this manifests as Kodi crashing completely.

Last entry in kodi.old.log

```
2020-04-08 10:19:10.027 T:1319600864  NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0) on Leia (Kodi-18.6) with Python 2.7.13
                                                Path: /kodion/search/input/
                                                Params: {}
```

**Comment by anxdpanic** [comment]
Need the complete log with debugging enabled

**Comment by jamieburchell** [comment]
[kodi.old.log](https://github.com/jdf76/plugin.video.youtube/files/4452985/kodi.old.log)
Here you go.

**Comment by anxdpanic** [comment]
@jamieburchell Sorry for the delay, I don't see anything YouTube related out of the ordinary. You may need to raise this for the auto complete add-on.

**Comment by jamieburchell** [comment]
Ah, thanks. I just found this open issue. https://github.com/phil65/plugin.program.autocompletion/issues/12
