### ISSUE TITLE
Missing setting menu

### ISSUE THREAD

**Issue by RailsRubyX** [jdf76/plugin.video.youtube#778]
I want to set up YouTube add-on with api keys.
But in menu setting i have nothing. Only "No available categories". And i can't enable API in the settings!

**Comment by anxdpanic** [comment]
I would start by reinstalling the add-on, if it's still an issue I'll need a complete debug log.

**Comment by RailsRubyX** [comment]
I'm reinstalled the add-on. But the same issue in the menu!
Where I can find the complete debug log?

**Comment by RailsRubyX** [comment]
> 
> 
> I would start by reinstalling the add-on, if it's still an issue I'll need a complete debug log.
I'm reinstalled the add-on. But the same issue in the menu!
Where I can find the complete debug log?

**Comment by Albager** [comment]
I don't know if this helps, but yesterday I had the same problem here:
![screenshot006](https://user-images.githubusercontent.com/11389126/78991739-ed21f780-7b39-11ea-966d-d058e8d5abb4.png)

After enabling Debug Logging and rebooting Kodi/libreelec - not reinstalling the Addon - everything is working again:
![screenshot007](https://user-images.githubusercontent.com/11389126/78991977-8c46ef00-7b3a-11ea-8349-3ec8d5bf7da6.png)

**Comment by anxdpanic** [comment]
@RailsRubyX Please re-open this issue with the complete debug log.
