### ISSUE TITLE
Kodi YouTube Addon throws Error

### ISSUE THREAD

**Issue by SubZero5** [jdf76/plugin.video.youtube#783]
I open the YouTube addon and sometimes when I try to enter My Subscriptions and sometimes (as now) I want to browse the Page (2) of my subscription, the YouTube Addon gives up and Error and the list fails to open.

https://paste.kodi.tv/datifoqeyi.kodi

**Comment by eternaleye** [comment]
So it seems that YouTube changed their `publishedAt` metadata to no longer include fractional seconds; it can be worked around by editing [resources/lib/youtube_plugin/youtube/helper/utils.py`](https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/utils.py#L292) to change line 292 to

```python
video_item.set_aired_utc(utils.datetime_parser.strptime(snippet['publishedAt'], '%Y-%m-%dT%H:%M:%SZ'))
```

However, [line 291](https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/utils.py#L291) is already

```python
datetime = utils.datetime_parser.parse(snippet['publishedAt'])
```

so it may be better to change line 292 to

```python
video_item.set_aired_utc(datetime)
```

**Comment by anxdpanic** [comment]
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev
This should be addressed in alpha1

**Comment by hedleyroos** [comment]
I don't think it is fixed in master yet. See https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/utils.py#L292. That line is the only line in the module that uses strptime, whereas just calling parse as at https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/helper/utils.py#L524 should be the preferred method.

**Comment by anxdpanic** [comment]
@hedleyroos 
https://github.com/jdf76/plugin.video.youtube/commit/5bb5adc1db731485c187d92c8742b9f55a72ce35

**Comment by mshopf** [comment]
I suggest using a more flexible approach that tries both variants.
Find a patch attached.

[youtube_fix_dateparse.diff.txt](https://github.com/jdf76/plugin.video.youtube/files/4498874/youtube_fix_dateparse.diff.txt)

**Comment by debdrup** [comment]
What's the timeline for the non-alpha version of the release with this fix in it being uploaded to the official repositories, if I may ask?

**Comment by anxdpanic** [comment]
I just bumped to beta, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev
Will hopefully be Sunday/Monday. If you install the zip for beta1, you'll still automatically get the release version as well.
