### ISSUE TITLE
Linking to a youtube livestream

### ISSUE THREAD

**Issue by CHJ85** [jdf76/plugin.video.youtube#790]
Hi there. So I'm setting up an m3u playlist of my favorite youtube livestreams.
I know how I can link to a specific video id (plugin://plugin.video.youtube/play/?video_id=VID).
But that ID expires once the stream is over. So how do I link to the channel's livestream feed, like https://www.youtube.com/channel/UCz81IIi1Fu_TRUvrc_iiVDA/live?

**Comment by anxdpanic** [comment]
The best option atm is: `plugin://plugin.video.youtube/play/?channel_id=UCz81IIi1Fu_TRUvrc_iiVDA&live=1`

`live=X` where X is the live stream index if there are multiple live streams. The index may change when there are multiple live streams.

**Comment by CHJ85** [comment]
Thank you so much 😀
