### ISSUE TITLE
Wiki (Personal API Keys) update: allow unsafe apps

### ISSUE THREAD

**Issue by SebSeb11** [jdf76/plugin.video.youtube#794]
[Personal API Keys Wiki](https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys) helped me a lot but still could not login to youtube on Libreelec 9.2.1.<br>
I always got a "wrong client ID" error after first login step. The solution was to allow unsafe apps (here: [https://myaccount.google.com/lesssecureapps?pli=1](https://myaccount.google.com/lesssecureapps?pli=1)) as described [here](https://github.com/jdf76/plugin.video.youtube/issues/700#issuecomment-586710964).

Shouldn't this info be added to the ["Sign in" section](https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys#sign-in) of the wiki?

**Comment by anxdpanic** [comment]
Added a note to the wiki, https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys#sign-in
Please re-open if you feel that is insufficient based on your experience.
