### ISSUE TITLE
Phyton error, youtube crash

### ISSUE THREAD

**Issue by faltaren** [jdf76/plugin.video.youtube#802]
[kodi.log](https://github.com/jdf76/plugin.video.youtube/files/4532357/kodi.log)
Hey! I have the latest kodiu 18.7 nightly. Can browse my subcriptions without a crash. Plz chech the log.

**Comment by anxdpanic** [comment]
Duplicate of #783 
Fixed in beta1 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev
