### ISSUE TITLE
API keys web interface stuck on port 50152

### ISSUE THREAD

**Issue by kekukui** [jdf76/plugin.video.youtube#807]
**"You should then be able to update your keys by visiting** `http://<IP of Kodi device>:<port>/api`
**The port used is Settings - HTTP Server - Port which by default is 50152"**

https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys#configure-the-add-on
______________________

--The API keys page is still found on port **50152** even when it is changed in settings

![screenshot004](https://user-images.githubusercontent.com/20834957/80409463-ec59c700-8896-11ea-8703-26b22669313c.png)

![image](https://user-images.githubusercontent.com/20834957/80409736-638f5b00-8897-11ea-922e-a943b4fbc0af.png)

**Comment by anxdpanic** [comment]
That's not the correct setting and controls different things. As you quoted the correct setting is `Settings - HTTP Server - Port` This is referencing the YouTube add-ons settings and not Kodi's settings.

**Comment by kekukui** [comment]
I would suggest using a different color to highlight the words "HTTP Server" in both places.  The lack of clarity is confusing people, for example:

_**"I could access the web interface using ipadress for kodi but using ipadress/api returned a file not found error"**_

https://forum.kodi.tv/showthread.php?tid=353278&pid=2944174#pid2944174

**Comment by sauliiin** [comment]
2025 and this is a problem for me
