### ISSUE TITLE
Addon only gives 'accessNotConfigured' Error

### ISSUE THREAD

**Issue by OverlordQ** [jdf76/plugin.video.youtube#808]
No matter how many times I input/update the personal API Key/Client Info the addon *always* prompts me with the accessNotConfigured error. 

http://paste.osmc.tv/lugeyigoda

**Comment by anxdpanic** [comment]
If you haven't resolved this, others have reported removing the old project completely and following https://github.com/jdf76/plugin.video.youtube/wiki/Personal-API-Keys resolved it (the guide has had revisions)
