### ISSUE TITLE
Non-ASCII characters in HTTP responses are not correctly decoded

### ISSUE THREAD

**Issue by thombet** [jdf76/plugin.video.youtube#821]
Thank you for the great work on this very helpful add-on :)
I ran into a minor issue and I could not solve it so I submit this issue because it seems it was not reported before.

When I try to play a private video which I don't have access to I get a notification error which contains the following string:
`Cette vidÃ©o est privÃ©e.`

It should be `Cette vidéo est privée.` (which is the French translation of `This video is private.`) so the French string is not correctly encoded as you can see. Actually I think it is not a classic unicode/byte encoding issue but rather the HTML version of this string that was not correctly unescaped.

If it helps, the error is reported by the function [`_method_get_video_info()`](https://github.com/jdf76/plugin.video.youtube/blob/851bd2145ad7b70b3c192d1301641e1a74b3b926/resources/lib/youtube_plugin/youtube/helper/video_info.py#L856) in the file `video_info.py`. I think the issue is something similar to what was reported [here](https://stackoverflow.com/a/27403159) but I could not solve the problem with the proposed solution so I hope you will find a better solution ;-)

**Comment by anxdpanic** [comment]
Thanks for reporting, if able please try alpha2 from https://github.com/jdf76/plugin.video.youtube/releases/tag/6.x.x-dev

**Comment by thombet** [comment]
Yes it works with the alpha2, thank you very much !

It [looks like](https://github.com/jdf76/plugin.video.youtube/commit/36d02abb4e4e4fd5eed798c168d426abccd98f0c) it was much simpler than what I thought ^^

One question though @anxdpanic: why not encoding the whole `playability_status` or the whole response with `raw_unicode_escape`instead of encoding only `reason`?

**Comment by anxdpanic** [comment]
`reason` is currently the only part of `playability_status` that is used

6.8.1 is waiting review on the official repository, release available: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.8.1

**Comment by thombet** [comment]
OK

Thank you again for the fix :)
