### ISSUE TITLE
Can't play YT content when logged in

### ISSUE THREAD

**Issue by AlexHarrowell** [jdf76/plugin.video.youtube#827]
So I worked through the advice to build a project in the Google console and did the OAuth2 stuff. I can now see my YT recommendations, history, etc but trying to do anything with them - like play them - gives "No stream found" errors and advice to see the event log. 

The event log tells me KODI was successfully started.

YT stuff plays fine without logging in. There might to be a KODI or LibreELEC issue about URIs as several other add-ons are fuxxored (mixcloud, soundcloud, The Guardian)

**Comment by anxdpanic** [comment]
see https://github.com/jdf76/plugin.video.youtube/releases/tag/6.8.2 
it's currently waiting for review for official repository

**Comment by AlexHarrowell** [comment]
I updated. The "no stream found" error is gone, and instead, the now-playing notification appears at the upper right corner of the screen and immediately vanishes, as if the song was of zero length.


On 14 May 2020 00:05:42 BST, anxdpanic <notifications@github.com> wrote:
>see https://github.com/jdf76/plugin.video.youtube/releases/tag/6.8.2 
>it's currently waiting for review for official repository
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jdf76/plugin.video.youtube/issues/827#issuecomment-628290828

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AlexHarrowell** [comment]
This seems to be broken quite widely across Kodi although it works fine in a browser. Why not have an option to open in an external browser and then Kodi might be useful for something/

**Comment by anxdpanic** [comment]
I don't have any issues with videos I've been watching, and no other users are reporting this. I would need a debug log to see what is going on in your case.

**Comment by AlexHarrowell** [comment]
It's not leaving anything in the log at all even with debug on. At least, not in the log as shown in the log viewer.


On 17 May 2020 13:26:15 BST, anxdpanic <notifications@github.com> wrote:
>I don't have any issues with videos I've been watching, and no other
>users are reporting this. I would need a debug log to see what is going
>on in your case.
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jdf76/plugin.video.youtube/issues/827#issuecomment-629788934

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AlexHarrowell** [comment]
if I choose "always ask quality", I get a menu offering different video
streams, so it's at least getting into this function:

https://github.com/jdf76/plugin.video.youtube/blob/284c7d105514b82dc450f0d145f752596329be45/resources/lib/youtube_plugin/kodion/utils/methods.py#L84

this at line 149 looks like "selectable streams: " and a number should be
logged if debug is on, so long as sorted_stream_data_list is a sequence
that len() understands:

https://github.com/jdf76/plugin.video.youtube/blob/284c7d105514b82dc450f0d145f752596329be45/resources/lib/youtube_plugin/kodion/utils/methods.py#L149

but it's not logging anything?

and as the UI event fires, this must be happening?

https://github.com/jdf76/plugin.video.youtube/blob/284c7d105514b82dc450f0d145f752596329be45/resources/lib/youtube_plugin/kodion/utils/methods.py#L167

again, logging of that should happen here so long as selected_stream_data
is at least something that can be string interpolated:

https://github.com/jdf76/plugin.video.youtube/blob/284c7d105514b82dc450f0d145f752596329be45/resources/lib/youtube_plugin/kodion/utils/methods.py#L178

I notice quite a bit of code in this function and elsewhere is skipped if
you're using MPEG-DASH - is that how you run it?

Alex

**Comment by anxdpanic** [comment]
This works and is logged properly in every case I've seen. Just to reiterate, you're the only report of this and without the debug log reproducing the issue, I have no chance of assisting you. I have no reproduction or debug information other than 'don't work when logged in'. So all I could assume so far is user error, which I doubt is the case.

**Comment by AlexHarrowell** [comment]
So if there is something wrong with the logging, what's your plan to fix it?

On 17 May 2020 15:47:47 BST, anxdpanic <notifications@github.com> wrote:
>This works and is logged properly in every case I've seen. Just to
>reiterate, you're the only report of this and without the debug log
>reproducing the issue, I have no chance of assisting you. I have no
>reproduction or debug information other than 'don't work when logged
>in'. So all I could assume so far is user error, which I doubt is the
>case.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jdf76/plugin.video.youtube/issues/827#issuecomment-629810067

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anxdpanic** [comment]
There is nothing wrong with either from all other cases is what I'm saying. I can't fix something I have 0 information on.

Are you sure you've enabled debug logging? Those lines will only be logged when it's enabled.
https://kodi.wiki/view/Log_file

**Comment by AlexHarrowell** [comment]
OK so the log viewer doesn't....view logs?...and LibreELEC doesn't have a
shell but you can stat the log file from the web browser.

here's an example:


   1. 2020-05-17 21:25:42.
   2. 2020-05-17 21:25:46.346 T:140172087781120   DEBUG: Skin Helper
   Widgets --> Kodi_Monitor: sender xbmc - method: Player.OnPlay  - data:
   {"item":{"title":"Dortmund v Schalke (4-0) | Bundesliga
   highlights","type":"video","year":2020},"player":{"playerid":1,"speed":1}}
   3. 2020-05-17 21:25:46.348 T:140172289107712   DEBUG:
   [plugin.video.youtube] PlaybackMonitor active threads: ||
   4. 2020-05-17 21:25:46.350 T:140171048019712   DEBUG:
   [plugin.video.youtube] PlaybackMonitorThread[Yoidk_EM-VE]: Starting...
   5. 2020-05-17 21:25:46.399 T:140172255536896  NOTICE: Librespot: Kodi
   playback started
   6. 2020-05-17 21:25:46.419 T:140173504886912   DEBUG: ------ Window Init
   (DialogBusy.xml) ------
   7. 2020-05-17 21:25:46.441 T:140171039627008   DEBUG: CFileCache::Open -
   opening <watch> using cache
   8. 2020-05-17 21:25:46.441 T:140171039627008   DEBUG:
   CurlFile::Open(0x7f7c6c002dc0)
   https://www.youtube.com/watch?v=Yoidk_EM-VE
   9. 2020-05-17 21:25:46.485 T:140171085682432  NOTICE: Librespot:
   suspended sink 1
   10. 2020-05-17 21:25:46.485 T:140171085682432  NOTICE: Librespot:
   librespot stopped
   11. 2020-05-17 21:25:46.485 T:140171085682432  NOTICE: Librespot:
   librespot thread stopped
   12. 2020-05-17 21:25:46.581 T:140171085682432   DEBUG: Thread FileCache
   start, auto delete: false
   13. 2020-05-17 21:25:46.581 T:140171039627008  NOTICE: Creating Demuxer
   14. 2020-05-17 21:25:46.637 T:140171048019712   DEBUG:
   [plugin.video.youtube] Playback start reported: |Yoidk_EM-VE|
   15. 2020-05-17 21:25:46.638 T:140171048019712   DEBUG:
   [plugin.video.youtube] send_notification: |PlaybackStarted| -> |{"status":
   {"live": false, "family_safe": true, "crawlable": true, "unlisted": false,
   "private": false}, "channel_id": "UC4i_9WvfPRTuRWEaWyfKuFw", "video_id":
   "Yoidk_EM-VE"}|
   16. 2020-05-17 21:25:46.676 T:140172087781120   DEBUG: Skin Helper
   Widgets --> Kodi_Monitor: sender plugin.video.youtube - method:
   Other.PlaybackStarted  - data:
   ["%7B%22status%22%3A%20%7B%22live%22%3A%20false%2C%20%22family_safe%22%3A%20true%2C%20%22crawlable%22%3A%20true%2C%20%22unlisted%22%3A%20false%2C%20%22private%22%3A%20false%7D%2C%20%22channel_id%22%3A%20%22UC4i_9WvfPRTuRWEaWyfKuFw%22%2C%20%22video_id%22%3A%20%22Yoidk_EM-VE%22%7D"]
   17. 2020-05-17 21:25:46.694 T:140172289107712   DEBUG:
   [plugin.video.youtube] onNotification: |unknown method|
   18. 2020-05-17 21:25:46.929 T:140171048019712   DEBUG:
   [plugin.video.youtube] Playback reported [Yoidk_EM-VE]: 0.000 segment
   start, 0.000 segment end @ 0% state=playing
   19. *2020-05-17 21:25:47.005 T:140171085682432    INFO:
   CFileCache::Process - Source read didn't return any data! Hit eof(?)*
   20. *2020-05-17 21:25:47.233 T:140171039627008   ERROR: Open - error
   probing input format, https://www.youtube.com/watch?v=Yoidk_EM-VE
   <https://www.youtube.com/watch?v=Yoidk_EM-VE>*
   21. *2020-05-17 21:25:47.233 T:140171039627008   ERROR: OpenDemuxStream
   - Error creating demuxer*
   22. 2020-05-17 21:25:47.234 T:140171039627008  NOTICE:
   CVideoPlayer::OnExit()
   23. 2020-05-17 21:25:47.234 T:140171085682432   DEBUG: Thread FileCache
   140171085682432 terminating
   24. 2020-05-17 21:25:47.234 T:140171039627008   DEBUG: Thread
   VideoPlayer 140171039627008 terminating


I can send you the whole dump some other way.

**Comment by anxdpanic** [comment]
Thanks 👍 

From that snippet it looks like you have external player settings enabled.
- Disable YouTube Add-on Settings -> Advanced -> Use YouTube website urls
- Disable YouTube Add-on Settings -> Advanced -> Support alternative player

If that doesn't fix the issue, you can attach a complete log at the bottom of a github comment 👍

**Comment by AlexHarrowell** [comment]
Right, that works, although I only turned it on trying to get it working...

On 17 May 2020 22:53:26 BST, anxdpanic <notifications@github.com> wrote:
>Thanks 👍 >
>>
>From that snippet it looks like you have external player settings
>enabled.>
>- Disable YouTube Add-on Settings -> Advanced -> Use YouTube website
>urls>
>- Disable YouTube Add-on Settings -> Advanced -> Support alternative
>player>
>>
>If that doesn't fix the issue, you can attach a complete log at the
>bottom of a github comment 👍 >
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/jdf76/plugin.video.youtube/issues/827#issuecomment-629866422

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by anxdpanic** [comment]
Good to hear :) There was likely an overlap from when there was an issue

If the issue reappears please re-open, or open a new issue with the debug log
