### ISSUE TITLE
Error when launching app

### ISSUE THREAD

**Issue by Micro-Crackedto** [jdf76/plugin.video.youtube#829]
Hello

I am getting the following error when launching YouTube 6.8.2 on LibreELEC
![image](https://user-images.githubusercontent.com/5491930/82494337-b2708f00-9ae9-11ea-95fd-06a54f38f45d.jpeg)

I am also unable to watch anything in 1080p
I am using MPEG-DASH/Inputstream Adaptive which are both set to 1080p

Livestreams work fine in 1080p, just not the videos.

It was working fine 2 days ago.

**Comment by anxdpanic** [comment]
First thing to try:
- Disable Settings - MPEG-DASH - Use MPEG-DASH
- Restart Kodi
- Enable Settings - MPEG-DASH - Use MPEG-DASH

If that doesn't work you can also try manually changing:
- Settings - HTTP Server - Listen on IP
- Settings - HTTP Server - Port

Would need the debug log otherwise.

**Comment by Micro-Crackedto** [comment]
I fixed it by fully uninstaling YouTube and reusing my API keys.👍

**Comment by anxdpanic** [comment]
no worries, happy it's resolved for you 👍
