### ISSUE TITLE
Videos are not added to youtube history

### ISSUE THREAD

**Issue by innerspacepilot** [jdf76/plugin.video.youtube#831]
Version: 6.8.2+matrix
using api keys, all account info available inside plugin.
'Use playback history' enabled

**Comment by anxdpanic** [comment]
Use playback history is unrelated (I know a confusing name)

I'd need a debug log showing some playback, to see if there is a silent error in the log

**Comment by innerspacepilot** [comment]
Oh. It started to work somehow. Maybe a kodi restart helped.
Sorry for bothering.
