### ISSUE TITLE
Any way to initiate playback from mobile?

### ISSUE THREAD

**Issue by giaur500** [jdf76/plugin.video.youtube#855]
Sorry, I realized there's no support thread on Kodi forums (or I am unable to find it), so I am asking here. Is there any way to initiate playback from mobile phone/official YouTube app? I mean following scenario: find movie on mobile, then share it to Kodi and start playback with max quality using Kodi Youtube addon. Similar as integration with AndroidTV and its built in Youtube app, or Chromecast.

I am asking for that, because it's more handy to search clip on phone. Any way or could it be added?

BTW I know I can use dlna/airplay with 3rd party app, but it does not work in all cases, and I am getting 240p resolution, so this way does not make any sense anymore

**Comment by Twilight0** [comment]
> Sorry, I realized there's no support thread on Kodi forums (or I am unable to find it), so I am asking here.

Actually there is: https://forum.kodi.tv/showthread.php?tid=353278

> Is there any way to initiate playback from mobile phone/official YouTube app? I mean following scenario: find movie on mobile, then share it to Kodi and start playback with max quality using Kodi Youtube addon

Have a look here: https://forum.kodi.tv/showthread.php?tid=329153

**Comment by giaur500** [comment]
Thanks, TubeCast looks promising

**Comment by tylerswagar** [comment]
You can also do this with a remote control app like Kore installed.  Assuming Kore is set up properly, you can hit "share" in the YouTube app and you should see a "Play on Kodi" option.  On Android, anway.  No idea how it works with iOS.

**Comment by giaur500** [comment]
Yes, but as far as I know that's paid option in Kore. I tested TubeCast and it works just fine (with some issues, but it works). I think I can close this ticket, thanks for tips.
