### ISSUE TITLE
The request cannot be completed because you have exceeded your quota.

### ISSUE THREAD

**Issue by jedi2light** [jdf76/plugin.video.youtube#856]
After creating my own API keys for Kodi Youtube plugin I have been had an ability to watch my recommendation videos, but when I have tried to watch another one video or choose another one option from global menu (like a "History") I have got next error:
```
The request cannot be completed because you have exceeded your quota.
```

**Comment by Twilight0** [comment]
Did you share your keys? Log into google console and have a look at your available quota. https://console.developers.google.com/iam-admin/quotas

**Comment by jedi2light** [comment]
No,  I didn`t.

**Comment by MarceloBorja** [comment]
> No, I didn`t.

Did you find out the problem? I just create my API and I'm having the same problem...

**Comment by nki2bpz** [comment]
I get the same error. Have already entered my own API keys and did 2 factor auth twice on 6.8.7 All searches return the quota reached error

**Comment by mryellow** [comment]
Yeah have tried several times over the months and entering API keys never seems to work.

**Comment by ezar** [comment]
Same here!

**Comment by LuisMayo** [comment]
> Did you share your keys? Log into google console and have a look at your available quota. https://console.developers.google.com/iam-admin/quotas

Same problem here and quota seem to be ok for me
![image](https://user-images.githubusercontent.com/20229636/101399916-70b20500-38d0-11eb-8b6e-6d12d16fb16f.png)

**Comment by Bergiu** [comment]
https://github.com/anxdpanic/plugin.video.youtube/issues/50#issuecomment-727608878

you need to recreate the full project

**Comment by rulet** [comment]
How to recreate the project? I even haven't used that addon before.

**Comment by sfxworks** [comment]
The above + going into the menu and letting the plugin truncate `apps.googleusercontent.com` worked for me.
