### ISSUE TITLE
Why requiring a personal API key when youtube-dl manages to do without?

### ISSUE THREAD

**Issue by stroobandt** [jdf76/plugin.video.youtube#857]
The opensource Python application [`youtube-dl`](https://ytdl-org.github.io/youtube-dl/index.html) allows one to download entire YouTube videos without the requirement for any personal API key or for logging in.

It is available on most Linux distributions through Python's `pip3` package manager.
It works flawlessly as long as it is kept updated.

I feel that something similar should be possible with the Kodi YouTube plugin.

There are quite a number of people out there (myself included) who refrain from logging in or using any API keys.

**Comment by anxdpanic** [comment]
This has been talked about in the other issues surrounding this. You can play any videos you want without api keys, `plugin://plugin.video.youtube/play/?video_id=<video_id>` the api keys allow the add-on to grab the different listing that are available which is something that youtube-dl doesn't require. There's a much larger issue with most of the information, https://github.com/jdf76/plugin.video.youtube/issues/736

This likely won't change, unless something changes on YouTube's end. And yes, alternatives like newpipe have been suggested already. That is a request for a different add-on and belongs in the forums.

**Comment by stroobandt** [comment]
Thanks for this concise description of the real problem, which was up to now not clear to me.
Yes, adopting some of the NewPipe code looks like the way forward.
