### ISSUE TITLE
No stream available when playing any video

### ISSUE THREAD

**Issue by whisperdancer** [jdf76/plugin.video.youtube#862]
OSMC OS running on RaspPi 3B+
Youtube app V 6.8.3

The youtube app has been working flawlessly for many months. Just yesterday when I try and play any video I get a popup error message saying "No Streams Found" and a dialog "Playback failed" One or more items failed ot play. Check the log for more information about this message. Interestingly it finds videos fine. I can search for videos and it returns results. The error happens when trying to play a video.

This error happens for every video now rendering the entire app useless.

Note, I have made no changes to the app, the OS, the setup. It just started doing this on it's own. I'm unsure where the location of the log file is.

**Comment by anxdpanic** [comment]
Will need a complete debug log, working here on windows and osmc pi2.

**Comment by whisperdancer** [comment]
How do I get that debug log to you? Where is the log located?

**Comment by whisperdancer** [comment]
I uninstalled and reinstalled the add-on and working fine now. I surmise something must have gotten corrupted. I'm closing the issue.
