### ISSUE TITLE
[Request] Add back icon

### ISSUE THREAD

**Issue by Lontron** [jdf76/plugin.video.youtube#863]
![IMG_20200830_233509](https://user-images.githubusercontent.com/66425682/91668962-b5801000-eb19-11ea-94e5-d956ba48b091.jpg)

**Comment by anxdpanic** [comment]
I don't know what you're wanting here

**Comment by Lontron** [comment]
@anxdpanic Adding the back icon where I showed it.

**Comment by anxdpanic** [comment]
That would be a skin request, no way I know of to alter that element from the add-on.

**Comment by Lontron** [comment]
@anxdpanic ok
