### ISSUE TITLE
Location of API KEY

### ISSUE THREAD

**Issue by aik** [jdf76/plugin.video.youtube#87]
https://forum.kodi.tv/showthread.php?tid=267160 suggests:
- With Kodi shut down, Paste all 3 Keys into: Kodi / userdata / addon_data / plugin.video.youtube / settings.xml
in the following lines of code:

<setting id="youtube.api.enable" value="true" />
<setting id="youtube.api.id" value="Client ID" />
<setting id="youtube.api.key" value="API Key" />
<setting id="youtube.api.secret" value="Client Secret" />

However the keys are not stored in /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/settings.xml on anywhere else I could grep so where they are actually stored?

**Comment by jdf76** [comment]
The API key settings are stored in your settings when you log in to youtube plugin it creates it in the $KODIINSTALL/userdata/addon_data/plugin.video.youtube/settings.xml

Thanks
Jeff

**Comment by aik** [comment]
What would the full path on android tablet look like? Changing
/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.youtube/resources/settings.xml did not have any effect.

**Comment by jdf76** [comment]
i don’t have an android tablet but if i were to guess from your post

/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.youtube/settings.xml

the path you’re currently in is the path where the plugin’s files are used not the settings so making any changes there wont do anything.

Jeff
