### ISSUE TITLE
Unable to save watch later ID

### ISSUE THREAD

**Issue by Overbord** [jdf76/plugin.video.youtube#877]
I'm trying to get my Watch Later list working in Kodi, and I assume my watch later ID is just 'wl' - but it whenever I try to save it in settings, it refuses to save.

Any idea what I might be doing wrong?

**Comment by anxdpanic** [comment]
`wl` or ` wl` no longer work, and this repository is no longer active.
 See https://github.com/anxdpanic/plugin.video.youtube/issues/69#issuecomment-766843932
