### ISSUE TITLE
Plugin doesn't read the playlist correctly

### ISSUE THREAD

**Issue by redking974** [jdf76/plugin.video.youtube#93]
Hi, I just install the plugin on my LibreElec config but I've seen that the behaviour is different than on YouTube website. When I read a video contained into a playlist, on Kodi after the playing, it comes back to the menu but on the website it loads the next video.
Is it volontary or a limitation of Kodi (and so of the plugin) ?

Regards

**Comment by anxdpanic** [comment]
To play more than 1 video, right click (context menu) to either Play All or Play from here.
